// @generated by generate_probe.py; do not edit.

pub(crate) mod bindings {
    wit_bindgen::generate!({
        path: "wit",
        world: "rules-synced",
    });
}

pub(crate) mod callin {
    pub(crate) use super::bindings::exports::recoil::spring_api::callins_rules_synced::{
        GameFrameQuery, GameFrameResult, Guest, SpringError, UpdateQuery, UpdateResult,
    };
}
