#!/usr/bin/env python3
"""Generate the engine-to-Lua/native callin trace implementations.

The callin list and the Rust callback signatures are deliberately read from
the source tree instead of being maintained as a second hand-written list.
The generated Rust methods prepend tracing to the trait's existing default
method bodies, so the parity fixture observes callbacks without changing the
native module's default engine behavior.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CALLBACKS = ROOT / "rust/crates/spring-native/src/callbacks.rs"
NATIVE_EVENTS = ROOT / "rts/NativeInterface/NativeInterfaceEventClient.cpp"
LUA_DOC = ROOT / "rust/crates/spring-native/lua_functions.md"
RUST_OUT = ROOT / "test/native_api_parity/native/src/generated_callin_trace.rs"
LUA_OUT = ROOT / "test/native_api_parity/fixtures/game.sdd/LuaRules/Gadgets/callin_parity.lua"
LUA_UI_OUT = ROOT / "test/native_api_parity/fixtures/game.sdd/LuaUI/callin_ui_trace.lua"

# These callbacks are documented in the general Callins section because their
# C++ implementation is shared by Lua handles, but only the synced LuaRules
# handle can receive them: the watch masks used by the implementation are not
# initialized for LuaUI.
SYNCED_GENERAL_CALLINS = {"Explosion", "ProjectileCreated", "ProjectileDestroyed"}


def matching(text: str, start: int, opening: str, closing: str) -> int:
    depth = 0
    for index in range(start, len(text)):
        if text[index] == opening:
            depth += 1
        elif text[index] == closing:
            depth -= 1
            if depth == 0:
                return index
    raise ValueError(f"unclosed {opening!r} at {start}")


def split_top_level(text: str) -> list[str]:
    result: list[str] = []
    start = 0
    depth = 0
    pairs = {"(": ")", "[": "]", "{": "}"}
    closing = set(pairs.values())
    for index, char in enumerate(text):
        if char in pairs:
            depth += 1
        elif char in closing:
            depth -= 1
        elif char == "," and depth == 0:
            result.append(text[start:index].strip())
            start = index + 1
    tail = text[start:].strip()
    if tail:
        result.append(tail)
    return result


def camel_to_snake(value: str) -> str:
    value = value.replace("MiniMap", "Minimap")
    value = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", value)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value).lower()


def native_symbols() -> set[str]:
    text = NATIVE_EVENTS.read_text(encoding="utf-8")
    return set(re.findall(r"^\s*LOAD_SYMBOL\((\w+)\)", text, re.MULTILINE))


def documented_callins() -> dict[str, set[str]]:
    text = LUA_DOC.read_text(encoding="utf-8")
    result: dict[str, set[str]] = {"Callins": set(), "SyncedCallins": set(), "UnsyncedCallins": set()}
    for namespace, name in re.findall(
        r"- `((?:Callins|SyncedCallins|UnsyncedCallins)\.([A-Za-z0-9_]+))`", text
    ):
        prefix, _ = namespace.split(".", 1)
        result[prefix].add(name)
    return result


def trait_methods() -> list[tuple[str, str, int]]:
    text = CALLBACKS.read_text(encoding="utf-8")
    methods: list[tuple[str, str, int]] = []
    for match in re.finditer(r"^    fn\s+([A-Za-z0-9_]+)\s*\(", text, re.MULTILINE):
        name = match.group(1)
        open_paren = text.find("(", match.start())
        close_paren = matching(text, open_paren, "(", ")")
        brace = text.find("{", close_paren)
        if brace < 0:
            continue
        end = matching(text, brace, "{", "}")
        signature = text[match.start() : brace].rstrip()
        params = [
            item
            for item in split_top_level(text[open_paren + 1 : close_paren])
            if item.strip() not in {"self", "&mut self", "&self"}
        ]
        methods.append((name, signature, len(params)))
    return methods


def method_item(name: str, signature: str, arity: int, text: str) -> str:
    start = next(
        match.start()
        for match in re.finditer(rf"^    fn\s+{re.escape(name)}\s*\(", text, re.MULTILINE)
    )
    brace = text.find("{", start)
    end = matching(text, brace, "{", "}")
    body = text[brace + 1 : end]
    callback_name = next(
        symbol for symbol in native_symbols() if camel_to_snake(symbol) == name
    )
    return (
        f"{signature} {{\n"
        f'        self.record_callin("{callback_name}", {arity});'
        f"{body}"
        "    }\n"
    )


def generate_rust() -> str:
    text = CALLBACKS.read_text(encoding="utf-8")
    documented = documented_callins()
    shared = set().union(*documented.values()) & (native_symbols() - {"InitializeNativeModule"})
    lines = [
        "// @generated by test/native_api_parity/generate_callin_trace.py; do not edit.",
        "// Each method retains the NativeModule trait default body after recording.",
        "",
        "macro_rules! generated_callin_trace_methods {",
        "    () => {",
    ]
    for name, signature, arity in trait_methods():
        if name in {"new", "draw_screen", "handle_lua_call"}:
            continue
        symbol = next((item for item in native_symbols() if camel_to_snake(item) == name), None)
        if symbol not in shared:
            continue
        lines.append(method_item(name, signature, arity, text))
    lines.extend(["    };", "}", ""])
    return "\n".join(lines)


RETURN_DEFAULTS = {
    "CommandFallback": "false",
    "ResourceExcess": "false",
    "MoveCtrlNotify": "false",
    "UnitUnitCollision": "false",
    "UnitFeatureCollision": "false",
    "DrawUnit": "false",
    "DrawFeature": "false",
    "DrawShield": "false",
    "DrawProjectile": "false",
    "DrawMaterial": "false",
    "KeyMapChanged": "false",
    "KeyPress": "false",
    "KeyRelease": "false",
    "TextInput": "false",
    "TextEditing": "false",
    "MouseMove": "false",
    "MousePress": "false",
    "MouseWheel": "false",
    "IsAbove": "false",
    "CommandNotify": "false",
    "AddConsoleLine": "false",
    "GroupChanged": "false",
    "MapDrawCmd": "false",
    "Explosion": "false",
    "ShieldPreDamaged": "false",
    "AllowWeaponTargetCheck": "-1",
    "AllowWeaponTarget": "true, nil",
    "AllowWeaponInterceptTarget": "true",
    "AllowUnitCreation": "true, true",
    "UnitPreDamaged": "nil, nil",
    "FeaturePreDamaged": "nil, nil",
}


def generate_lua() -> str:
    documented = documented_callins()
    shared = sorted(
        (documented["SyncedCallins"] | documented["UnsyncedCallins"] | SYNCED_GENERAL_CALLINS)
        & (native_symbols() - {"InitializeNativeModule"})
    )
    lines = [
        "-- @generated by test/native_api_parity/generate_callin_trace.py; do not edit.",
        "-- This gadget records the Lua side of shared engine callins and returns",
        "-- the same neutral/default values as the C++ Lua implementation.",
        "",
        "function gadget:GetInfo()",
        "\treturn {",
        '\t\tname = "Native API Callin Parity Trace",',
        '\t\tdesc = "Traces shared engine-to-Lua/native callins",',
        '\t\tauthor = "Spring",',
        "\t\tlayer = 1000000,",
        "\t\tenabled = true,",
        "\t}",
        "end",
        "",
        'local Common = VFS.Include("LuaRules/Utilities/native_api_parity_common.lua")',
        "local synced = gadgetHandler:IsSyncedCode()",
        "local outputStream = \"callin_lua\"",
        "",
        "local function normalize(value, depth)",
        "\tlocal valueType = type(value)",
        "\tif valueType == \"nil\" then return \"nil\" end",
        "\tif valueType == \"number\" then return \"number\" end",
        "\tif valueType == \"boolean\" then return \"boolean\" end",
        "\tif valueType == \"string\" then return \"string\" end",
        "\tif valueType ~= \"table\" then return valueType end",
        "\tif (depth or 0) >= 2 then return \"table\" end",
        "\tlocal result = {}",
        "\tfor key, item in pairs(value) do",
        "\t\tresult[#result + 1] = { key = type(key), value = normalize(item, (depth or 0) + 1) }",
        "\tend",
        "\ttable.sort(result, function(a, b) return a.key .. a.value < b.key .. b.value end)",
        "\treturn result",
        "end",
        "",
        "local function forward(encoded)",
        "\tif Script.LuaUI and Script.LuaUI.NativeApiParityResult then",
        "\t\tScript.LuaUI.NativeApiParityResult(outputStream, encoded)",
        "\tend",
        "end",
        "",
        "local function trace(name, ...)",
        "\tlocal args = { ... }",
        "\tlocal normalized = {}",
        "\tfor index = 1, select(\"#\", ...) do",
        "\t\tnormalized[index] = normalize(args[index], 0)",
        "\tend",
        "\tlocal payload = {",
        "\t\tcontext = synced and \"synced_gadget\" or \"unsynced_gadget\",",
        "\t\tname = name,",
        "\t\tarity = select(\"#\", ...),",
        "\t\targs = normalized,",
        "\t}",
        "\tlocal encoded = Common.encode(payload)",
        "\tif synced then",
        "\t\tSendToUnsynced(\"native_api_callin_trace\", encoded)",
        "\telse",
        "\t\tforward(encoded)",
        "\tend",
        "end",
        "",
        "local function traceCallin(name, ...)",
        "\ttrace(name, ...)",
        "\tif name == \"AllowUnitCreation\" then return true, true end",
        "\tif name == \"UnitPreDamaged\" or name == \"FeaturePreDamaged\" then return nil, nil end",
        # gadgetHandler starts with priority=1.0 and applies math.max() to
        # every gadget result, so a neutral result must remain numeric even
        # when the engine supplied no default priority.
        "\tif name == \"AllowWeaponTarget\" then",
        "\t\tlocal args = { ... }",
        "\t\treturn true, args[5] or 1.0",
        "\tend",
        "\tif name == \"AllowWeaponTargetCheck\" then return -1 end",
        "\tlocal default = {",
    ]
    for name, value in sorted(RETURN_DEFAULTS.items()):
        if name in {"AllowUnitCreation", "UnitPreDamaged", "FeaturePreDamaged", "AllowWeaponTarget", "AllowWeaponTargetCheck"}:
            continue
        lines.append(f'\t\t["{name}"] = {{{value}}},')
    lines.extend([
        "\t}",
        "\tlocal values = default[name]",
        "\tif values then return unpack(values) end",
        "end",
        "",
        "if not synced then",
        "\tfunction gadget:RecvFromSynced(name, encoded)",
        "\t\tif name == \"native_api_callin_trace\" then",
        "\t\t\tforward(encoded)",
        "\t\tend",
        "\tend",
        "end",
        "",
    ])
    for name in shared:
        lines.extend([
            f"function gadget:{name}(...)",
            f'\treturn traceCallin("{name}", ...)',
            "end",
            "",
        ])
    return "\n".join(lines)


def generate_lua_ui() -> str:
    documented = documented_callins()
    shared = set().union(*documented.values()) & (native_symbols() - {"InitializeNativeModule"})
    ui_names = sorted(
        shared
        - documented["SyncedCallins"]
        - documented["UnsyncedCallins"]
        - SYNCED_GENERAL_CALLINS
    )
    lines = [
        "-- @generated by test/native_api_parity/generate_callin_trace.py; do not edit.",
        "-- LuaUI-side wrappers trace general Callins without replacing existing",
        "-- fixture behavior or changing any of their return values.",
        "",
        "local Common = VFS.Include(\"LuaRules/Utilities/native_api_parity_common.lua\")",
        "",
        "local function normalize(value, depth)",
        "\tlocal valueType = type(value)",
        "\tif valueType == \"nil\" then return \"nil\" end",
        "\tif valueType == \"number\" then return \"number\" end",
        "\tif valueType == \"boolean\" then return \"boolean\" end",
        "\tif valueType == \"string\" then return \"string\" end",
        "\tif valueType ~= \"table\" then return valueType end",
        "\tif (depth or 0) >= 2 then return \"table\" end",
        "\tlocal result = {}",
        "\tfor key, item in pairs(value) do",
        "\t\tresult[#result + 1] = { key = type(key), value = normalize(item, (depth or 0) + 1) }",
        "\tend",
        "\ttable.sort(result, function(a, b) return a.key .. a.value < b.key .. b.value end)",
        "\treturn result",
        "end",
        "",
        "local function defaultResult(name)",
        "\tif name == \"AllowWeaponTargetCheck\" then return -1 end",
        "\tif name == \"AllowWeaponTarget\" then return true, 1.0 end",
        "\tif name == \"AllowUnitCreation\" then return true, true end",
        "\tif name == \"UnitPreDamaged\" or name == \"FeaturePreDamaged\" then return nil, nil end",
        "\tlocal defaults = {",
    ]
    for name, value in sorted(RETURN_DEFAULTS.items()):
        if name in {"AllowUnitCreation", "UnitPreDamaged", "FeaturePreDamaged", "AllowWeaponTarget", "AllowWeaponTargetCheck"}:
            continue
        lines.append(f'\t\t["{name}"] = {{{value}}},')
    lines.extend([
        "\t}",
        "\tlocal values = defaults[name]",
        "\tif values then return unpack(values) end",
        "end",
        "",
        "local function trace(name, ...)",
        "\tlocal args = { ... }",
        "\tlocal normalized = {}",
        "\tfor index = 1, select(\"#\", ...) do",
        "\t\tnormalized[index] = normalize(args[index], 0)",
        "\tend",
        "\tCommon.appendJsonLine(Common.outputDir() .. \"/callin_lua.jsonl\", {",
        "\t\tcontext = \"lua_ui\",",
        "\t\tname = name,",
        "\t\tarity = select(\"#\", ...),",
        "\t\targs = normalized,",
        "\t})",
        "end",
        "",
    ])
    for name in ui_names:
        lines.extend([
            f'local previous_{name} = _G["{name}"]',
            f'_G["{name}"] = function(...)',
            f'\ttrace("{name}", ...)',
            f'\tif previous_{name} then return previous_{name}(...) end',
            f'\treturn defaultResult("{name}")',
            "end",
            "",
        ])
    return "\n".join(lines)


def main() -> int:
    RUST_OUT.write_text(generate_rust(), encoding="utf-8")
    LUA_OUT.write_text(generate_lua(), encoding="utf-8")
    LUA_UI_OUT.write_text(generate_lua_ui(), encoding="utf-8")
    documented = documented_callins()
    shared = set().union(*documented.values()) & (native_symbols() - {"InitializeNativeModule"})
    print(f"generated {len(shared)} shared callin trace entries")
    print(RUST_OUT)
    print(LUA_OUT)
    print(LUA_UI_OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
