-- @generated by test/native_api_parity/generate_callin_trace.py; do not edit.
-- This gadget records the Lua side of shared engine callins and returns
-- the same neutral/default values as the C++ Lua implementation.

function gadget:GetInfo()
	return {
		name = "Native API Callin Parity Trace",
		desc = "Traces shared engine-to-Lua/native callins",
		author = "Spring",
		layer = 1000000,
		enabled = true,
	}
end

local Common = VFS.Include("LuaRules/Utilities/native_api_parity_common.lua")
local synced = gadgetHandler:IsSyncedCode()
local outputStream = "callin_lua"

local function roundNumber(value)
	return math.floor(value * 100000 + 0.5) / 100000
end

local function normalize(value, depth)
	local valueType = type(value)
	if valueType == "nil" then return { type = "nil" } end
	if valueType == "number" then return roundNumber(value) end
	if valueType == "boolean" or valueType == "string" then return value end
	if valueType ~= "table" then return valueType end
	if (depth or 0) >= 5 then return { type = "table" } end
	local result = {}
	for key, item in pairs(value) do
		result[#result + 1] = { key = normalize(key, (depth or 0) + 1), value = normalize(item, (depth or 0) + 1) }
	end
	table.sort(result, function(a, b) return Common.encode(a.key) .. Common.encode(a.value) < Common.encode(b.key) .. Common.encode(b.value) end)
	return result
end

local function forward(encoded)
	if Script.LuaUI and Script.LuaUI.NativeApiParityResult then
		Script.LuaUI.NativeApiParityResult(outputStream, encoded)
	end
end

local function trace(name, ...)
	local args = { ... }
	local normalized = {}
	for index = 1, select("#", ...) do
		normalized[index] = normalize(args[index], 0)
	end
	local payload = {
		context = synced and "synced_gadget" or "unsynced_gadget",
		name = name,
		arity = select("#", ...),
		args = normalized,
	}
	local encoded = Common.encode(payload)
	if synced then
		SendToUnsynced("native_api_callin_trace", encoded)
	else
		forward(encoded)
	end
end

local function traceCallin(name, ...)
	trace(name, ...)
	if name == "AllowUnitCreation" then return true, true end
	if name == "UnitPreDamaged" or name == "FeaturePreDamaged" then return nil, nil end
	if name == "AllowWeaponTarget" then
		local args = { ... }
		return true, args[5] or 1.0
	end
	if name == "AllowWeaponTargetCheck" then return -1 end
	local default = {
		["AddConsoleLine"] = {false},
		["AllowWeaponInterceptTarget"] = {true},
		["CommandFallback"] = {false},
		["CommandNotify"] = {false},
		["DrawFeature"] = {false},
		["DrawMaterial"] = {false},
		["DrawProjectile"] = {false},
		["DrawShield"] = {false},
		["DrawUnit"] = {false},
		["Explosion"] = {false},
		["GroupChanged"] = {false},
		["IsAbove"] = {false},
		["KeyMapChanged"] = {false},
		["KeyPress"] = {false},
		["KeyRelease"] = {false},
		["MapDrawCmd"] = {false},
		["MouseMove"] = {false},
		["MousePress"] = {false},
		["MouseWheel"] = {false},
		["MoveCtrlNotify"] = {false},
		["ResourceExcess"] = {false},
		["ShieldPreDamaged"] = {false},
		["TextEditing"] = {false},
		["TextInput"] = {false},
		["UnitFeatureCollision"] = {false},
		["UnitUnitCollision"] = {false},
	}
	local values = default[name]
	if values then return unpack(values) end
end

if not synced then
	function gadget:RecvFromSynced(name, encoded)
		if name == "native_api_callin_trace" then
			forward(encoded)
		elseif name == "native_api_callin_phase" then
			forward(Common.encode({ context = "callin_phase", name = encoded }))
		end
	end
end

function gadget:AllowBuilderHoldFire(...)
	return traceCallin("AllowBuilderHoldFire", ...)
end

function gadget:AllowCommand(...)
	return traceCallin("AllowCommand", ...)
end

function gadget:AllowDirectUnitControl(...)
	return traceCallin("AllowDirectUnitControl", ...)
end

function gadget:AllowFeatureBuildStep(...)
	return traceCallin("AllowFeatureBuildStep", ...)
end

function gadget:AllowFeatureCreation(...)
	return traceCallin("AllowFeatureCreation", ...)
end

function gadget:AllowResourceLevel(...)
	return traceCallin("AllowResourceLevel", ...)
end

function gadget:AllowResourceTransfer(...)
	return traceCallin("AllowResourceTransfer", ...)
end

function gadget:AllowStartPosition(...)
	return traceCallin("AllowStartPosition", ...)
end

function gadget:AllowUnitBuildStep(...)
	return traceCallin("AllowUnitBuildStep", ...)
end

function gadget:AllowUnitCaptureStep(...)
	return traceCallin("AllowUnitCaptureStep", ...)
end

function gadget:AllowUnitCloak(...)
	return traceCallin("AllowUnitCloak", ...)
end

function gadget:AllowUnitCreation(...)
	return traceCallin("AllowUnitCreation", ...)
end

function gadget:AllowUnitDecloak(...)
	return traceCallin("AllowUnitDecloak", ...)
end

function gadget:AllowUnitKamikaze(...)
	return traceCallin("AllowUnitKamikaze", ...)
end

function gadget:AllowUnitTransfer(...)
	return traceCallin("AllowUnitTransfer", ...)
end

function gadget:AllowUnitTransport(...)
	return traceCallin("AllowUnitTransport", ...)
end

function gadget:AllowUnitTransportLoad(...)
	return traceCallin("AllowUnitTransportLoad", ...)
end

function gadget:AllowUnitTransportUnload(...)
	return traceCallin("AllowUnitTransportUnload", ...)
end

function gadget:AllowWeaponInterceptTarget(...)
	return traceCallin("AllowWeaponInterceptTarget", ...)
end

function gadget:AllowWeaponTarget(...)
	return traceCallin("AllowWeaponTarget", ...)
end

function gadget:AllowWeaponTargetCheck(...)
	return traceCallin("AllowWeaponTargetCheck", ...)
end

function gadget:CommandFallback(...)
	return traceCallin("CommandFallback", ...)
end

function gadget:DrawFeature(...)
	return traceCallin("DrawFeature", ...)
end

function gadget:DrawMaterial(...)
	return traceCallin("DrawMaterial", ...)
end

function gadget:DrawProjectile(...)
	return traceCallin("DrawProjectile", ...)
end

function gadget:DrawShield(...)
	return traceCallin("DrawShield", ...)
end

function gadget:DrawUnit(...)
	return traceCallin("DrawUnit", ...)
end

function gadget:Explosion(...)
	return traceCallin("Explosion", ...)
end

function gadget:FeatureDamaged(...)
	return traceCallin("FeatureDamaged", ...)
end

function gadget:FeaturePreDamaged(...)
	return traceCallin("FeaturePreDamaged", ...)
end

function gadget:MoveCtrlNotify(...)
	return traceCallin("MoveCtrlNotify", ...)
end

function gadget:ProjectileCreated(...)
	return traceCallin("ProjectileCreated", ...)
end

function gadget:ProjectileDestroyed(...)
	return traceCallin("ProjectileDestroyed", ...)
end

function gadget:ResourceExcess(...)
	return traceCallin("ResourceExcess", ...)
end

function gadget:ShieldPreDamaged(...)
	return traceCallin("ShieldPreDamaged", ...)
end

function gadget:TerraformComplete(...)
	return traceCallin("TerraformComplete", ...)
end

function gadget:UnitPreDamaged(...)
	return traceCallin("UnitPreDamaged", ...)
end
