[package]
name = "recoil-wasm-parity-guest"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
core = []
core_rules_synced = []
core_rules_unsynced = []
core_gaia_synced = []
core_gaia_unsynced = []
core_ui = []

[dependencies]
spring = { path = "../../../../rust/crates/spring", features = ["alloc"] }
