//! Generate the validator registry for Core imports that have executable host
//! callbacks. This is intentionally narrower than the diagnostic ABI plan.
//!
//! Performance policy: generic variable-input renderers are useful scaffolding,
//! but they currently allocate/copy host vectors. Do not advertise them as the
//! production Core path until their borrowed/scratch lowering is reviewed.

use serde::Serialize;
use std::collections::BTreeMap;

use crate::model::{ApiModel, FieldModel, RecordModel, SemanticType};
use crate::render_core_wasm::{self, FunctionPlan, InputStrategy, ResultStrategy};
use crate::render_core_wasm_option_host;
use crate::render_core_wasm_variable_output_host;

pub fn render(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = plan_index(model);

    let mut output = String::from(
        "/* @generated by spring-api-codegen; do not edit. */\n#pragma once\n\n#include <cstdint>\n#include <string_view>\n\nnamespace recoil::wasm::core::generated_registry {\n\nstruct ImportDescriptor {\n    std::string_view module;\n    std::string_view name;\n    std::string_view signature;\n    std::uint32_t environmentMask;\n};\n\ninline constexpr ImportDescriptor kImports[] = {\n",
    );

    for module in &model.modules {
        for function in &module.functions {
            let Some(plan) = plans.get(&(module.name.clone(), function.name.clone())) else {
                continue;
            };
            if executable_class(plan, &function.inputs, &function.outputs, &records).is_none() {
                continue;
            }
            output.push_str(&format!(
                "    {{\"{}\", \"{}\", \"{}\", {}u}},\n",
                escape(&plan.import_module),
                escape(&plan.import_name),
                escape(&plan.signature),
                plan.environment_mask,
            ));
        }
    }

    output.push_str(
        "};\n\ninline const ImportDescriptor* Find(std::string_view module, std::string_view name)\n{\n    for (const ImportDescriptor& import : kImports) {\n        if (import.module == module && import.name == name)\n            return &import;\n    }\n    return nullptr;\n}\n\n} // namespace recoil::wasm::core::generated_registry\n",
    );
    output
}

#[derive(Serialize)]
struct CoverageEntry {
    module: String,
    function: String,
    import_module: String,
    import_name: String,
    class: Option<String>,
    reason: Option<String>,
}

#[derive(Serialize)]
struct CoverageReport {
    executable_total: usize,
    by_class: BTreeMap<String, usize>,
    executable: Vec<CoverageEntry>,
    pending: Vec<CoverageEntry>,
}

pub fn render_coverage_json(model: &ApiModel) -> anyhow::Result<String> {
    let records = record_index(model);
    let plans = plan_index(model);
    let mut by_class = BTreeMap::<String, usize>::new();
    let mut executable = Vec::new();
    let mut pending = Vec::new();

    for module in &model.modules {
        for function in &module.functions {
            let Some(plan) = plans.get(&(module.name.clone(), function.name.clone())) else {
                continue;
            };
            if let Some(class) = executable_class(plan, &function.inputs, &function.outputs, &records) {
                *by_class.entry(class.to_owned()).or_default() += 1;
                executable.push(CoverageEntry {
                    module: module.name.clone(),
                    function: function.name.clone(),
                    import_module: plan.import_module.clone(),
                    import_name: plan.import_name.clone(),
                    class: Some(class.to_owned()),
                    reason: None,
                });
            } else {
                pending.push(CoverageEntry {
                    module: module.name.clone(),
                    function: function.name.clone(),
                    import_module: plan.import_module.clone(),
                    import_name: plan.import_name.clone(),
                    class: None,
                    reason: Some(pending_reason(plan)),
                });
            }
        }
    }

    let report = CoverageReport {
        executable_total: executable.len(),
        by_class,
        executable,
        pending,
    };
    Ok(serde_json::to_string_pretty(&report)? + "\n")
}

fn executable_class<'a>(
    plan: &FunctionPlan,
    inputs: &[FieldModel],
    outputs: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<&'a str> {
    if fixed_executable(plan, inputs, outputs, records) {
        return Some("fixed");
    }
    if render_core_wasm_option_host::eligible(plan, inputs, outputs, records) {
        return Some("fixed-option");
    }
    if render_core_wasm_variable_output_host::eligible(plan, inputs, outputs, records) {
        return Some("variable-output-caller-owned");
    }

    // Deliberately exclude InputStrategy::VariableInputBuffer here. The current
    // generic renderers allocate/copy host storage. Specialized bindings can
    // still expose reviewed zero-/low-allocation forms through the handwritten
    // registry, but generated coverage must not call the generic form "fast".
    None
}

fn pending_reason(plan: &FunctionPlan) -> String {
    if matches!(plan.input_strategy, InputStrategy::VariableInputBuffer) {
        return "variable input awaits allocation-free/reviewed lowering".to_owned();
    }
    if plan.source_status == "manual" {
        return "semantic/manual lowering required".to_owned();
    }
    if plan.source_status == "unsupported"
        || matches!(plan.input_strategy, InputStrategy::Unsupported)
        || matches!(plan.result_strategy, ResultStrategy::Unsupported)
    {
        return "unsupported Core shape".to_owned();
    }
    "no executable generated fast-path renderer".to_owned()
}

fn fixed_executable(
    plan: &FunctionPlan,
    inputs: &[FieldModel],
    outputs: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    if plan.source_status != "automatic"
        || !matches!(
            plan.input_strategy,
            InputStrategy::Direct | InputStrategy::FixedInputBuffer
        )
    {
        return false;
    }
    if inputs
        .iter()
        .any(|field| !direct_type(&field.ty) && !wire_type(&field.ty, records))
    {
        return false;
    }
    match plan.result_strategy {
        ResultStrategy::Status => true,
        ResultStrategy::Packed32 => {
            outputs.len() == 1
                && matches!(
                    outputs[0].ty,
                    SemanticType::Scalar { .. } | SemanticType::Enum { .. }
                )
        }
        ResultStrategy::FixedOutputBuffer { .. } => {
            outputs.iter().all(|field| wire_type(&field.ty, records))
        }
        ResultStrategy::VariableOutputBuffer | ResultStrategy::Unsupported => false,
    }
}

fn direct_type(ty: &SemanticType) -> bool {
    matches!(
        ty,
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. }
    )
}

fn wire_type(ty: &SemanticType, records: &BTreeMap<String, RecordModel>) -> bool {
    match ty {
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. } => true,
        SemanticType::FixedArray { element, length } => {
            *length <= 64 && wire_type(element, records)
        }
        SemanticType::Record { name } => records
            .get(name)
            .is_some_and(|record| record.fields.iter().all(|field| wire_type(&field.ty, records))),
        _ => false,
    }
}

fn plan_index(model: &ApiModel) -> BTreeMap<(String, String), FunctionPlan> {
    render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect()
}

fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records.entry(record.name.clone()).or_insert_with(|| record.clone());
        }
    }
    records
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
