//! C++ host generation for direct/fixed Core-Wasm callins.

use heck::ToKebabCase;

use crate::model::{ApiModel, SemanticType};

use super::exec_model::{
    executable_callin, expanded_callins, record_index, ExecutableCallin, ResultAbi,
};

pub(super) fn render_header(model: &ApiModel) -> String {
    let slot_count = expanded_callins(model).len() + 1;
    format!(
        r#"/* @generated by spring-api-codegen; do not edit. */
#pragma once

#include <array>
#include <cstdint>
#include <string>

#include "WasmInterface/WasmCoreAbi.h"

class WasmExecutionBudget;

namespace recoil::wasm::core::generated {{

// Slot zero is WasmCoreCallin::Invalid. All other slots use exactly the
// generated WasmCallinRegistry.h ordering, aliases included.
inline constexpr std::size_t kGeneratedCallinSlotCount = {slot_count}u;

class GeneratedCallinBindings {{
public:
    bool Bind(wasmtime_context_t* context, const wasmtime_instance_t& instance,
        std::string& error);
    bool Has(std::uint16_t ordinal) const;
    bool Invoke(std::uint16_t ordinal, wasmtime_context_t* context,
        ::WasmExecutionBudget& budget, Memory& memory, std::string& stringStorage,
        const void* query, void* result, std::string& error) const;

private:
    std::array<RawExport, kGeneratedCallinSlotCount> exports{{}};
    mutable bool stringResultInUse = false;
}};

}} // namespace recoil::wasm::core::generated
"#,
        slot_count = slot_count,
    )
}

pub(super) fn render_cpp(model: &ApiModel) -> String {
    let records = record_index(model);
    let executable = expanded_callins(model)
        .into_iter()
        .filter_map(|entry| executable_callin(entry, &records))
        .collect::<Vec<_>>();

    let mut bind = String::new();
    let mut invoke_cases = String::new();
    for callin in &executable {
        bind.push_str(&render_bind(callin));
        invoke_cases.push_str(&render_invoke_case(callin));
    }

    format!(
        r#"/* @generated by spring-api-codegen; do not edit. */

#include "wasm/generated/WasmCoreGeneratedCallinBindings.h"

#include <array>
#include <bit>
#include <cstdint>
#include <limits>
#include <span>
#include <type_traits>

#include "NativeInterface/api/Callins.h"
#include "WasmInterface/WasmResources.h"

namespace recoil::wasm::core::generated {{

bool GeneratedCallinBindings::Bind(wasmtime_context_t* context,
    const wasmtime_instance_t& instance, std::string& error)
{{
    if (context == nullptr) {{
        error = "cannot bind generated Core callins without a Wasmtime context";
        return false;
    }}
{bind}
    return true;
}}

bool GeneratedCallinBindings::Has(std::uint16_t ordinal) const
{{
    return ordinal < exports.size() && exports[ordinal].Present();
}}

bool GeneratedCallinBindings::Invoke(std::uint16_t ordinal,
    wasmtime_context_t* context, ::WasmExecutionBudget& budget, Memory& memory,
    std::string& stringStorage, const void* query, void* result,
    std::string& error) const
{{
    if (!Has(ordinal))
        return true;

    switch (ordinal) {{
{invoke_cases}        default:
            error = "Core callin is present but has no generated invoker";
            return false;
    }}
}}

static_assert(kGeneratedCallinSlotCount == {slot_count}u,
    "generated Core callin slot count drifted");
static_assert({eligible_count}u <= kGeneratedCallinSlotCount,
    "generated Core callin coverage count");

}} // namespace recoil::wasm::core::generated
"#,
        bind = bind,
        invoke_cases = invoke_cases,
        slot_count = expanded_callins(model).len() + 1,
        eligible_count = executable.len(),
    )
}

fn render_bind(callin: &ExecutableCallin<'_>) -> String {
    let params = callin
        .query_leaves
        .iter()
        .map(|leaf| wasm_kind(&leaf.ty))
        .collect::<Vec<_>>();
    let results = result_wasm_kinds(&callin.result);
    let export_name = format!("spring:callin/{}", callin.entry.name.to_kebab_case());
    format!(
        "    {{\n        const std::array<wasm_valkind_t, {param_count}> params{{{params}}};\n        const std::array<wasm_valkind_t, {result_count}> results{{{results}}};\n        if (!exports[{ordinal}].Resolve(context, instance, \"{export_name}\", {export_len}u,\n                params, results, true, error))\n            return false;\n    }}\n",
        param_count = params.len(),
        params = params.join(", "),
        result_count = results.len(),
        results = results.join(", "),
        ordinal = callin.entry.ordinal,
        export_name = export_name,
        export_len = export_name.len(),
    )
}

fn render_invoke_case(callin: &ExecutableCallin<'_>) -> String {
    let result_count = result_wasm_kinds(&callin.result).len();
    let slot_count = callin.query_leaves.len().max(result_count);
    let storage_count = slot_count.max(1);
    let mut body = format!("        case {}u: {{\n", callin.entry.ordinal);

    if !callin.query_leaves.is_empty() {
        body.push_str(&format!(
            "            const auto* typedQuery = static_cast<const {}*>(query);\n            if (typedQuery == nullptr) {{\n                error = \"generated Core {} query is null\";\n                return false;\n            }}\n",
            callin.entry.callin.query, callin.entry.name,
        ));
    }

    body.push_str(&format!(
        "            std::array<wasmtime_val_raw_t, {storage_count}> slots{{}};\n"
    ));
    for (slot, leaf) in callin.query_leaves.iter().enumerate() {
        body.push_str("            ");
        body.push_str(&cpp_slot_write(
            slot,
            &leaf.ty,
            &format!("typedQuery->{}", leaf.cpp_path),
        ));
        body.push('\n');
    }

    if matches!(callin.result, ResultAbi::String { .. }) {
        body.push_str(&format!(
            "            if (stringResultInUse) {{\n                error = \"nested generated Core string-result callin would overwrite guest result storage\";\n                return false;\n            }}\n            stringResultInUse = true;\n            const bool callSucceeded = exports[{ordinal}].Call(context, {slot_ptr}, {slot_count}u, error);\n            stringResultInUse = false;\n            if (!callSucceeded)\n                return false;\n",
            ordinal = callin.entry.ordinal,
            slot_ptr = if slot_count == 0 { "nullptr" } else { "slots.data()" },
            slot_count = slot_count,
        ));
    } else {
        body.push_str(&format!(
            "            if (!exports[{ordinal}].Call(context, {slot_ptr}, {slot_count}u, error))\n                return false;\n",
            ordinal = callin.entry.ordinal,
            slot_ptr = if slot_count == 0 { "nullptr" } else { "slots.data()" },
            slot_count = slot_count,
        ));
    }

    match &callin.result {
        ResultAbi::Empty => {}
        ResultAbi::Direct { field } => {
            body.push_str(&format!(
                "            if (result != nullptr) {{\n                auto* typedResult = static_cast<{}*>(result);\n                typedResult->error = nullptr;\n                {}\n            }}\n",
                callin.entry.callin.result,
                cpp_result_write(&field.ty, &format!("typedResult->{}", field.name)),
            ));
        }
        ResultAbi::PackedFixed { leaves } => {
            body.push_str(&format!(
                "            if (result != nullptr) {{\n                auto* typedResult = static_cast<{}*>(result);\n                typedResult->error = nullptr;\n                const std::uint64_t packed = static_cast<std::uint64_t>(slots[0].i64);\n",
                callin.entry.callin.result,
            ));
            for (index, leaf) in leaves.iter().enumerate() {
                body.push_str(&format!(
                    "                const std::uint32_t raw{index} = static_cast<std::uint32_t>(packed >> {shift}u);\n                {}\n",
                    cpp_unpack_packed32(
                        &leaf.ty,
                        &format!("typedResult->{}", leaf.cpp_path),
                        &format!("raw{index}"),
                    ),
                    shift = index * 32,
                ));
            }
            body.push_str("            }\n");
        }
        ResultAbi::String { field } => {
            body.push_str(&format!(
                "            if (result != nullptr) {{\n                auto* typedResult = static_cast<{}*>(result);\n                typedResult->error = nullptr;\n                const std::uint64_t packed = static_cast<std::uint64_t>(slots[0].i64);\n                const std::uint32_t pointer = static_cast<std::uint32_t>(packed);\n                const std::uint32_t length = static_cast<std::uint32_t>(packed >> 32);\n                if (length == std::numeric_limits<std::uint32_t>::max()) {{\n                    error = \"generated Core string-result handler reported an invalid output length\";\n                    return false;\n                }}\n                if (!budget.CheckResultSize(length)) {{\n                    error = \"generated Core string result exceeds the configured result-byte limit\";\n                    return false;\n                }}\n                if (length == 0) {{\n                    stringStorage.clear();\n                }} else {{\n                    std::span<const std::uint8_t> bytes;\n                    if (!memory.View(pointer, length, bytes)) {{\n                        error = \"generated Core string-result range is outside guest memory\";\n                        return false;\n                    }}\n                    stringStorage.assign(reinterpret_cast<const char*>(bytes.data()), bytes.size());\n                }}\n                typedResult->{field_name} = stringStorage.c_str();\n            }}\n",
                callin.entry.callin.result,
                field_name = field.name,
            ));
        }
    }
    body.push_str("            return true;\n        }\n");
    body
}

fn result_wasm_kinds(result: &ResultAbi) -> Vec<&'static str> {
    match result {
        ResultAbi::Empty => Vec::new(),
        ResultAbi::Direct { field } => vec![wasm_kind(&field.ty)],
        ResultAbi::PackedFixed { .. } | ResultAbi::String { .. } => vec!["WASM_I64"],
    }
}

fn wasm_kind(ty: &SemanticType) -> &'static str {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "f32" => "WASM_F32",
            "f64" => "WASM_F64",
            "i64" | "u64" | "isize" | "usize" => "WASM_I64",
            _ => "WASM_I32",
        },
        SemanticType::Enum { .. } => "WASM_I32",
        SemanticType::Handle { .. } => "WASM_I64",
        _ => unreachable!("non-numeric Core callin type"),
    }
}

fn cpp_slot_write(slot: usize, ty: &SemanticType, value: &str) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!("slots[{slot}].i32 = {value} ? 1 : 0;"),
            "f32" => format!("slots[{slot}].f32 = {value};"),
            "f64" => format!("slots[{slot}].f64 = {value};"),
            "i64" | "u64" | "isize" | "usize" => {
                format!("slots[{slot}].i64 = static_cast<std::int64_t>({value});")
            }
            _ => format!("slots[{slot}].i32 = static_cast<std::int32_t>({value});"),
        },
        SemanticType::Enum { .. } => {
            format!("slots[{slot}].i32 = static_cast<std::int32_t>({value});")
        }
        SemanticType::Handle { .. } => {
            format!("slots[{slot}].i64 = static_cast<std::int64_t>({value});")
        }
        _ => unreachable!(),
    }
}

fn cpp_result_write(ty: &SemanticType, destination: &str) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!("{destination} = slots[0].i32 != 0;"),
            "f32" => format!("{destination} = slots[0].f32;"),
            "f64" => format!("{destination} = slots[0].f64;"),
            "i64" | "u64" | "isize" | "usize" => format!(
                "{destination} = static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>(slots[0].i64);"
            ),
            _ => format!(
                "{destination} = static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>(slots[0].i32);"
            ),
        },
        SemanticType::Enum { .. } => format!(
            "{destination} = static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>(slots[0].i32);"
        ),
        SemanticType::Handle { .. } => format!(
            "{destination} = static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>(slots[0].i64);"
        ),
        _ => unreachable!(),
    }
}

fn cpp_unpack_packed32(ty: &SemanticType, destination: &str, raw: &str) -> String {
    match ty {
        SemanticType::Scalar { name } if name == "bool" =>
            format!("{destination} = {raw} != 0u;"),
        SemanticType::Scalar { name } if name == "f32" =>
            format!("{destination} = std::bit_cast<float>({raw});"),
        SemanticType::Scalar { name } if matches!(name.as_str(), "i8" | "i16" | "i32") => {
            let signed = match name.as_str() {
                "i8" => "std::int8_t",
                "i16" => "std::int16_t",
                _ => "std::int32_t",
            };
            format!(
                "{destination} = static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>(static_cast<{signed}>({raw}));"
            )
        }
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } => format!(
            "{destination} = static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>({raw});"
        ),
        _ => unreachable!(),
    }
}
