//! Guest-side raw imports for the adapted variable-input Core fallback.
//!
//! The ordinary generated Core guest module and the borrowed fragment cover the
//! zero-copy/common cases. This fragment exists only for variable-input shapes
//! whose NativeInterface representation requires host adaptation (for example
//! list<string> pointer tables or fixed-layout record lists). Keeping it
//! separate makes the allocation boundary explicit and avoids duplicating the
//! preferred borrowed API surface.

use heck::ToSnakeCase;
use std::collections::BTreeMap;

use crate::model::{ApiModel, RecordModel};
use crate::render_core_wasm::{self, CoreType};
use crate::render_core_wasm_borrowed_host;
use crate::render_core_wasm_variable_host;

pub fn render(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();

    let mut modules = String::new();
    let mut total = 0usize;

    for module in &model.modules {
        let functions = module
            .functions
            .iter()
            .filter_map(|function| {
                let plan = plans.get(&(module.name.clone(), function.name.clone()))?;
                let adapted = render_core_wasm_variable_host::eligible(
                    plan,
                    &function.inputs,
                    &function.outputs,
                    &records,
                );
                let borrowed = render_core_wasm_borrowed_host::eligible(
                    plan,
                    &function.inputs,
                    &function.outputs,
                    &records,
                );
                (adapted && !borrowed).then_some(plan)
            })
            .collect::<Vec<_>>();
        if functions.is_empty() {
            continue;
        }

        total += functions.len();
        let module_ident = rust_ident(&module.name.to_snake_case());
        modules.push_str(&format!("    pub mod {module_ident} {{\n"));
        modules.push_str("        #[cfg(target_arch = \"wasm32\")]\n");
        modules.push_str("        pub mod raw {\n");
        for plan in functions {
            modules.push_str(&render_raw(plan));
        }
        modules.push_str("        }\n");
        modules.push_str("    }\n\n");
    }

    format!(
        "// @generated by spring-api-codegen; do not edit.\n\
         // Raw ABI for adapted variable-input callouts. Prefer the ordinary\n\
         // generated/borrowed safe wrappers when available.\n\n\
         pub mod adapted {{\n{modules}\
             #[doc(hidden)]\n\
             pub const __GENERATED_ADAPTED_VARIABLE_CALLOUT_COUNT: usize = {total};\n\
         }}\n",
        modules = modules,
        total = total,
    )
}

fn render_raw(plan: &render_core_wasm::FunctionPlan) -> String {
    debug_assert!(plan.direct_results.len() <= 1);
    let function_ident = rust_ident(&plan.function.to_snake_case());
    let params = plan
        .direct_params
        .iter()
        .enumerate()
        .map(|(index, ty)| format!("p{index}: {}", rust_core_type(*ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let result = plan
        .direct_results
        .first()
        .map(|ty| format!(" -> {}", rust_core_type(*ty)))
        .unwrap_or_default();

    format!(
        "            #[link(wasm_import_module = \"{module}\")]\n\
                     extern \"C\" {{\n\
                         #[link_name = \"{name}\"]\n\
                         pub fn {function_ident}({params}){result};\n\
                     }}\n",
        module = plan.import_module,
        name = plan.import_name,
        function_ident = function_ident,
        params = params,
        result = result,
    )
}

fn rust_core_type(ty: CoreType) -> &'static str {
    match ty {
        CoreType::I32 => "i32",
        CoreType::I64 => "i64",
        CoreType::F32 => "f32",
        CoreType::F64 => "f64",
    }
}

fn rust_ident(value: &str) -> String {
    match value {
        "type" | "match" | "move" | "ref" | "self" | "Self" | "super" | "crate" | "where"
        | "loop" | "in" | "mod" | "fn" | "struct" | "enum" | "use" | "pub" | "impl" | "trait"
        | "const" | "static" | "async" | "await" | "dyn" | "abstract" | "become" | "box" | "do"
        | "final" | "macro" | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield"
        | "try" => {
            format!("r#{value}")
        }
        _ => value.to_owned(),
    }
}

fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records
                .entry(record.name.clone())
                .or_insert_with(|| record.clone());
        }
    }
    records
}
