//! Core-WebAssembly ABI planning and generated inventory.
//!
//! This renderer is intentionally independent of Wasmtime. It converts the
//! transport-neutral semantic API into a Spring-owned Core ABI description.
//! Runtime-specific C++ and Rust renderers can consume this plan without
//! changing the guest-visible ABI.

use heck::ToKebabCase;
use serde::Serialize;
use std::collections::{BTreeMap, BTreeSet};

use crate::model::{
    ApiModel, Environment, FieldModel, FunctionModel, LoweringStatus, RecordModel, SemanticType,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum CoreType {
    I32,
    I64,
    F32,
    F64,
}

impl CoreType {
    fn signature(self) -> &'static str {
        match self {
            Self::I32 => "i32",
            Self::I64 => "i64",
            Self::F32 => "f32",
            Self::F64 => "f64",
        }
    }

    fn byte_width(self) -> u32 {
        match self {
            Self::I32 | Self::F32 => 4,
            Self::I64 | Self::F64 => 8,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ResultStrategy {
    /// No successful payload; return one i32 native error/status code.
    Status,
    /// Successful payload fits in 32 bits; return value/status packed in i64.
    Packed32,
    /// Successful payload is written to a guest-owned fixed-size buffer and
    /// the function returns one i32 status.
    FixedOutputBuffer { bytes: u32, alignment: u32 },
    /// Variable-size result uses caller-owned ptr/capacity and reports the
    /// required/written length. Concrete list/string layout is generated by
    /// the type-specific renderer rather than inferred by the runtime.
    VariableOutputBuffer,
    Unsupported,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum InputStrategy {
    /// All inputs flatten directly to Core numeric parameters.
    Direct,
    /// At least one fixed aggregate must be read from guest memory.
    FixedInputBuffer,
    /// At least one string/list/bytes input uses ptr+len.
    VariableInputBuffer,
    Unsupported,
}

#[derive(Debug, Clone, Serialize)]
pub struct FunctionPlan {
    pub module: String,
    pub function: String,
    pub import_module: String,
    pub import_name: String,
    pub environment_mask: u32,
    pub mutating: bool,
    pub visibility_sensitive: bool,
    pub source_status: String,
    pub input_strategy: InputStrategy,
    pub result_strategy: ResultStrategy,
    pub direct_params: Vec<CoreType>,
    pub direct_results: Vec<CoreType>,
    pub signature: String,
    pub notes: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct CoreAbiPlan {
    pub abi_version: u32,
    pub functions: Vec<FunctionPlan>,
    pub automatic_count: usize,
    pub manual_count: usize,
    pub unsupported_count: usize,
}

pub fn plan(model: &ApiModel) -> CoreAbiPlan {
    let records = records(model);
    let mut functions = Vec::new();
    let mut automatic_count = 0;
    let mut manual_count = 0;
    let mut unsupported_count = 0;

    for module in &model.modules {
        for function in &module.functions {
            let function_plan = plan_function(&module.name, function, &records);
            match function_plan.result_strategy {
                ResultStrategy::Unsupported => unsupported_count += 1,
                _ if matches!(function.status, LoweringStatus::Manual | LoweringStatus::Annotated) => {
                    manual_count += 1
                }
                _ => automatic_count += 1,
            }
            functions.push(function_plan);
        }
    }

    functions.sort_by(|left, right| {
        left.module
            .cmp(&right.module)
            .then_with(|| left.function.cmp(&right.function))
    });

    CoreAbiPlan {
        abi_version: 1,
        functions,
        automatic_count,
        manual_count,
        unsupported_count,
    }
}

pub fn render_json(model: &ApiModel) -> anyhow::Result<String> {
    Ok(serde_json::to_string_pretty(&plan(model))? + "\n")
}

/// Render a C++ inventory containing every planned function. It is diagnostic
/// until a corresponding generated host callback exists: runtime validation
/// must continue to use only the executable registry, not this candidate list.
pub fn render_inventory_header(model: &ApiModel) -> String {
    let plan = plan(model);
    let mut output = String::from(
        "/* @generated by spring-api-codegen; do not edit. */\n#pragma once\n\n#include <cstdint>\n#include <string_view>\n\nnamespace recoil::wasm::core::generated {\n\n",
    );
    output.push_str(
        "enum class Strategy : std::uint8_t { direct, fixedInput, variableInput, fixedOutput, variableOutput, manual, unsupported };\n\n",
    );
    output.push_str(
        "struct Candidate { std::string_view module; std::string_view name; std::string_view signature; std::uint32_t environmentMask; Strategy strategy; };\n\ninline constexpr Candidate kCandidates[] = {\n",
    );

    for function in &plan.functions {
        let strategy = cpp_strategy(function);
        output.push_str(&format!(
            "\t{{\"{}\", \"{}\", \"{}\", {}u, Strategy::{}}},\n",
            escape_cpp(&function.import_module),
            escape_cpp(&function.import_name),
            escape_cpp(&function.signature),
            function.environment_mask,
            strategy,
        ));
    }
    output.push_str("};\n\n} // namespace recoil::wasm::core::generated\n");
    output
}

fn cpp_strategy(function: &FunctionPlan) -> &'static str {
    if matches!(function.result_strategy, ResultStrategy::Unsupported)
        || matches!(function.input_strategy, InputStrategy::Unsupported)
    {
        return "unsupported";
    }
    if function.source_status == "manual" || function.source_status == "annotated" {
        return "manual";
    }
    match (&function.input_strategy, &function.result_strategy) {
        (InputStrategy::VariableInputBuffer, _) => "variableInput",
        (InputStrategy::FixedInputBuffer, _) => "fixedInput",
        (_, ResultStrategy::VariableOutputBuffer) => "variableOutput",
        (_, ResultStrategy::FixedOutputBuffer { .. }) => "fixedOutput",
        _ => "direct",
    }
}

fn plan_function(
    module: &str,
    function: &FunctionModel,
    records: &BTreeMap<String, RecordModel>,
) -> FunctionPlan {
    let mut notes = function.notes.clone();
    let mut direct_params = Vec::new();
    let input_strategy = classify_inputs(&function.inputs, records, &mut direct_params, &mut notes);
    let (result_strategy, mut direct_results) = classify_outputs(&function.outputs, records, &mut notes);

    // Fixed/variable outputs receive an extra wasm32 output pointer. Variable
    // renderers may append capacity after this planner has selected an element
    // layout; this base plan records the mandatory pointer now.
    if matches!(
        result_strategy,
        ResultStrategy::FixedOutputBuffer { .. } | ResultStrategy::VariableOutputBuffer
    ) {
        direct_params.push(CoreType::I32);
        direct_results = vec![CoreType::I32];
    }

    // Fixed aggregate inputs are represented by one wasm32 pointer each by the
    // detailed renderer. At planning level we append a single pointer marker;
    // functions containing multiple aggregates remain conservative/manual.
    if matches!(input_strategy, InputStrategy::FixedInputBuffer | InputStrategy::VariableInputBuffer)
        && !direct_params.ends_with(&[CoreType::I32])
    {
        direct_params.push(CoreType::I32);
    }

    let signature = signature(&direct_params, &direct_results);
    FunctionPlan {
        module: module.to_string(),
        function: function.name.clone(),
        import_module: format!("spring:{}", module.replace('_', "-")),
        import_name: function.name.to_kebab_case(),
        environment_mask: environment_mask(&function.environments),
        mutating: function.mutating,
        visibility_sensitive: function.visibility_sensitive,
        source_status: lowering_status(function.status).to_string(),
        input_strategy,
        result_strategy,
        direct_params,
        direct_results,
        signature,
        notes,
    }
}

fn classify_inputs(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
    direct: &mut Vec<CoreType>,
    notes: &mut Vec<String>,
) -> InputStrategy {
    let mut aggregate_count = 0usize;
    let mut variable = false;
    for field in fields {
        if let Some(core) = direct_core_type(&field.ty) {
            direct.push(core);
            continue;
        }
        if is_fixed(&field.ty, records) {
            aggregate_count += 1;
            continue;
        }
        if field.ty.is_variable_size() {
            aggregate_count += 1;
            variable = true;
            continue;
        }
        notes.push(format!("unsupported Core input field {}", field.name));
        return InputStrategy::Unsupported;
    }
    if aggregate_count == 0 {
        InputStrategy::Direct
    } else if aggregate_count > 1 {
        notes.push("multiple aggregate inputs require a generated query wire record".to_string());
        if variable {
            InputStrategy::VariableInputBuffer
        } else {
            InputStrategy::FixedInputBuffer
        }
    } else if variable {
        InputStrategy::VariableInputBuffer
    } else {
        InputStrategy::FixedInputBuffer
    }
}

fn classify_outputs(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
    notes: &mut Vec<String>,
) -> (ResultStrategy, Vec<CoreType>) {
    if fields.is_empty() {
        return (ResultStrategy::Status, vec![CoreType::I32]);
    }
    if fields.len() == 1 {
        let ty = &fields[0].ty;
        if let Some(core) = direct_core_type(ty) {
            // i32/f32 payload + signed status fits exactly in one i64. 64-bit
            // payloads use memory so errors remain unambiguous and portable.
            if matches!(core, CoreType::I32 | CoreType::F32) {
                return (ResultStrategy::Packed32, vec![CoreType::I64]);
            }
            let bytes = core.byte_width();
            return (
                ResultStrategy::FixedOutputBuffer {
                    bytes,
                    alignment: bytes.min(8),
                },
                vec![CoreType::I32],
            );
        }
        if let Some((bytes, alignment)) = fixed_layout(ty, records) {
            return (
                ResultStrategy::FixedOutputBuffer { bytes, alignment },
                vec![CoreType::I32],
            );
        }
        if ty.is_variable_size() {
            return (ResultStrategy::VariableOutputBuffer, vec![CoreType::I32]);
        }
    } else {
        let mut bytes = 0u32;
        let mut alignment = 1u32;
        for field in fields {
            let Some((field_bytes, field_alignment)) = fixed_layout(&field.ty, records) else {
                if field.ty.is_variable_size() {
                    return (ResultStrategy::VariableOutputBuffer, vec![CoreType::I32]);
                }
                notes.push(format!("unsupported Core output field {}", field.name));
                return (ResultStrategy::Unsupported, Vec::new());
            };
            let padding = (field_alignment - (bytes % field_alignment)) % field_alignment;
            bytes = bytes.saturating_add(padding).saturating_add(field_bytes);
            alignment = alignment.max(field_alignment);
        }
        let tail = (alignment - (bytes % alignment)) % alignment;
        bytes = bytes.saturating_add(tail);
        return (
            ResultStrategy::FixedOutputBuffer { bytes, alignment },
            vec![CoreType::I32],
        );
    }

    notes.push("result requires a manual Core ABI lowering".to_string());
    (ResultStrategy::Unsupported, Vec::new())
}

fn direct_core_type(ty: &SemanticType) -> Option<CoreType> {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i8" | "u8" | "char" | "i16" | "u16" | "i32" | "u32" | "bool" => {
                Some(CoreType::I32)
            }
            "i64" | "u64" | "isize" | "usize" => Some(CoreType::I64),
            "f32" => Some(CoreType::F32),
            "f64" => Some(CoreType::F64),
            _ => None,
        },
        // Native enums are integer values. Core keeps them numeric rather than
        // stringifying variant names as the Component Model renderer does.
        SemanticType::Enum { .. } => Some(CoreType::I32),
        SemanticType::Handle { .. } => Some(CoreType::I64),
        SemanticType::Callback { .. } => Some(CoreType::I32),
        _ => None,
    }
}

fn is_fixed(ty: &SemanticType, records: &BTreeMap<String, RecordModel>) -> bool {
    fixed_layout(ty, records).is_some()
}

fn fixed_layout(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    if let Some(core) = direct_core_type(ty) {
        let width = core.byte_width();
        return Some((width, width.min(8)));
    }
    match ty {
        SemanticType::FixedArray { element, length } => {
            let (element_bytes, element_alignment) = fixed_layout(element, records)?;
            let bytes = element_bytes.checked_mul(u32::try_from(*length).ok()?)?;
            Some((bytes, element_alignment))
        }
        SemanticType::Record { name } => {
            let record = records.get(name)?;
            layout_fields(&record.fields, records)
        }
        SemanticType::Option { inner } => {
            let (payload_bytes, payload_alignment) = fixed_layout(inner, records)?;
            // Canonical Spring wire option: u32 present tag followed by payload
            // aligned to its natural wire alignment.
            let payload_offset = align_up(4, payload_alignment);
            let alignment = payload_alignment.max(4);
            Some((align_up(payload_offset.checked_add(payload_bytes)?, alignment), alignment))
        }
        _ => None,
    }
}

fn layout_fields(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    let mut bytes = 0u32;
    let mut alignment = 1u32;
    for field in fields {
        let (field_bytes, field_alignment) = fixed_layout(&field.ty, records)?;
        bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
        alignment = alignment.max(field_alignment);
    }
    Some((align_up(bytes, alignment), alignment))
}

fn align_up(value: u32, alignment: u32) -> u32 {
    debug_assert!(alignment.is_power_of_two());
    (value + alignment - 1) & !(alignment - 1)
}

fn records(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut result = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            result.entry(record.name.clone()).or_insert_with(|| record.clone());
        }
    }
    result
}

fn environment_mask(environments: &BTreeSet<Environment>) -> u32 {
    environments.iter().fold(0u32, |mask, environment| {
        let bit = match environment {
            Environment::RulesSynced => 0,
            Environment::RulesUnsynced => 1,
            Environment::GaiaSynced => 2,
            Environment::GaiaUnsynced => 3,
            Environment::Ui => 4,
        };
        mask | (1u32 << bit)
    })
}

fn lowering_status(status: LoweringStatus) -> &'static str {
    match status {
        LoweringStatus::Automatic => "automatic",
        LoweringStatus::Annotated => "annotated",
        LoweringStatus::Manual => "manual",
        LoweringStatus::Unsupported => "unsupported",
    }
}

fn signature(params: &[CoreType], results: &[CoreType]) -> String {
    let mut output = params
        .iter()
        .map(|value| value.signature())
        .collect::<Vec<_>>()
        .join(",");
    output.push_str("->");
    output.push_str(
        &results
            .iter()
            .map(|value| value.signature())
            .collect::<Vec<_>>()
            .join(","),
    );
    output
}

fn escape_cpp(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn signature_is_stable() {
        assert_eq!(
            signature(&[CoreType::I32, CoreType::F32], &[CoreType::I64]),
            "i32,f32->i64"
        );
    }

    #[test]
    fn scalar_outputs_choose_packed_or_buffer() {
        let records = BTreeMap::new();
        let i32_field = FieldModel {
            name: "value".into(),
            ty: SemanticType::Scalar { name: "i32".into() },
            status: LoweringStatus::Automatic,
            metadata: Vec::new(),
        };
        let i64_field = FieldModel {
            name: "value".into(),
            ty: SemanticType::Scalar { name: "i64".into() },
            status: LoweringStatus::Automatic,
            metadata: Vec::new(),
        };
        assert!(matches!(
            classify_outputs(&[i32_field], &records, &mut Vec::new()).0,
            ResultStrategy::Packed32
        ));
        assert!(matches!(
            classify_outputs(&[i64_field], &records, &mut Vec::new()).0,
            ResultStrategy::FixedOutputBuffer { bytes: 8, .. }
        ));
    }
}
