//! Generate the validator registry for Core imports that have executable host
//! callbacks. This is intentionally narrower than the diagnostic ABI plan.

use std::collections::BTreeMap;

use crate::model::{ApiModel, FieldModel, RecordModel, SemanticType};
use crate::render_core_wasm::{self, FunctionPlan, InputStrategy, ResultStrategy};
use crate::render_core_wasm_variable_host;

pub fn render(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();

    let mut output = String::from(
        "/* @generated by spring-api-codegen; do not edit. */\n#pragma once\n\n#include <cstdint>\n#include <string_view>\n\nnamespace recoil::wasm::core::generated_registry {\n\nstruct ImportDescriptor {\n    std::string_view module;\n    std::string_view name;\n    std::string_view signature;\n    std::uint32_t environmentMask;\n};\n\ninline constexpr ImportDescriptor kImports[] = {\n",
    );

    for module in &model.modules {
        for function in &module.functions {
            let Some(plan) = plans.get(&(module.name.clone(), function.name.clone())) else {
                continue;
            };
            if !fixed_executable(plan, &function.inputs, &function.outputs, &records)
                && !render_core_wasm_variable_host::eligible(
                    plan,
                    &function.inputs,
                    &function.outputs,
                    &records,
                )
            {
                continue;
            }
            output.push_str(&format!(
                "    {{\"{}\", \"{}\", \"{}\", {}u}},\n",
                escape(&plan.import_module),
                escape(&plan.import_name),
                escape(&plan.signature),
                plan.environment_mask,
            ));
        }
    }

    output.push_str(
        "};\n\ninline const ImportDescriptor* Find(std::string_view module, std::string_view name)\n{\n    for (const ImportDescriptor& import : kImports) {\n        if (import.module == module && import.name == name)\n            return &import;\n    }\n    return nullptr;\n}\n\n} // namespace recoil::wasm::core::generated_registry\n",
    );
    output
}

fn fixed_executable(
    plan: &FunctionPlan,
    inputs: &[FieldModel],
    outputs: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    if plan.source_status != "automatic"
        || !matches!(
            plan.input_strategy,
            InputStrategy::Direct | InputStrategy::FixedInputBuffer
        )
    {
        return false;
    }
    if inputs
        .iter()
        .any(|field| !direct_type(&field.ty) && !wire_type(&field.ty, records))
    {
        return false;
    }
    match plan.result_strategy {
        ResultStrategy::Status => true,
        ResultStrategy::Packed32 => {
            outputs.len() == 1
                && matches!(
                    outputs[0].ty,
                    SemanticType::Scalar { .. } | SemanticType::Enum { .. }
                )
        }
        ResultStrategy::FixedOutputBuffer { .. } => {
            outputs.iter().all(|field| wire_type(&field.ty, records))
        }
        ResultStrategy::VariableOutputBuffer | ResultStrategy::Unsupported => false,
    }
}

fn direct_type(ty: &SemanticType) -> bool {
    matches!(
        ty,
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. }
    )
}

fn wire_type(ty: &SemanticType, records: &BTreeMap<String, RecordModel>) -> bool {
    match ty {
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. } => true,
        SemanticType::FixedArray { element, length } => {
            *length <= 64 && wire_type(element, records)
        }
        SemanticType::Record { name } => records
            .get(name)
            .is_some_and(|record| record.fields.iter().all(|field| wire_type(&field.ty, records))),
        _ => false,
    }
}

fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records.entry(record.name.clone()).or_insert_with(|| record.clone());
        }
    }
    records
}

fn escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
