//! Guest-side caller-owned wrappers for recursively dynamic Core results.
//!
//! The host encodes these results into one schema-driven byte blob. These
//! wrappers keep wasm32 pointer construction inside generated code and expose
//! the host-reported required length so callers can resize and retry.

use heck::ToSnakeCase;
use std::collections::BTreeMap;

use crate::model::{ApiModel, RecordModel};
use crate::render_core_wasm::{self, CoreType};
use crate::render_core_wasm_dynamic_output_host;

pub fn render(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();

    let mut modules = String::new();
    let mut total = 0usize;

    for module in &model.modules {
        let functions = module
            .functions
            .iter()
            .filter_map(|function| {
                let plan = plans.get(&(module.name.clone(), function.name.clone()))?;
                render_core_wasm_dynamic_output_host::eligible(
                    plan,
                    &function.inputs,
                    &function.outputs,
                    &records,
                )
                .then_some((function, plan))
            })
            .collect::<Vec<_>>();
        if functions.is_empty() {
            continue;
        }

        total += functions.len();
        let module_ident = rust_ident(&module.name.to_snake_case());
        modules.push_str(&format!("    pub mod {module_ident} {{\n"));
        modules.push_str("        #[cfg(target_arch = \"wasm32\")]\n");
        modules.push_str("        mod raw {\n");
        for (_, plan) in &functions {
            modules.push_str(&render_raw(plan));
        }
        modules.push_str("        }\n\n");
        for (_, plan) in functions {
            modules.push_str(&render_wrapper(plan));
            modules.push('\n');
        }
        modules.push_str("    }\n\n");
    }

    format!(
        "// @generated by spring-api-codegen; do not edit.\n\
         pub mod dynamic_output {{\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             pub struct DynamicOutputError {{\n\
                 pub error: crate::ApiError,\n\
                 pub required: usize,\n\
             }}\n\n\
         {modules}\
             #[doc(hidden)]\n\
             pub const __GENERATED_DYNAMIC_OUTPUT_CALLOUT_COUNT: usize = {total};\n\
         }}\n",
        modules = modules,
        total = total,
    )
}

fn render_raw(plan: &render_core_wasm::FunctionPlan) -> String {
    let function_ident = rust_ident(&plan.function.to_snake_case());
    let params = plan
        .direct_params
        .iter()
        .enumerate()
        .map(|(index, ty)| format!("p{index}: {}", rust_core_type(*ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let result = plan
        .direct_results
        .first()
        .map(|ty| format!(" -> {}", rust_core_type(*ty)))
        .unwrap_or_default();
    format!(
        "            #[link(wasm_import_module = \"{module}\")]\n\
                     extern \"C\" {{\n\
                         #[link_name = \"{name}\"]\n\
                         pub fn {function_ident}({params}){result};\n\
                     }}\n",
        module = plan.import_module,
        name = plan.import_name,
        function_ident = function_ident,
        params = params,
        result = result,
    )
}

fn render_wrapper(plan: &render_core_wasm::FunctionPlan) -> String {
    debug_assert_eq!(plan.direct_results, vec![CoreType::I32]);
    debug_assert!(!plan.direct_params.is_empty());
    let function_ident = rust_ident(&plan.function.to_snake_case());
    let input_types = &plan.direct_params[..plan.direct_params.len() - 1];
    let params = input_types
        .iter()
        .enumerate()
        .map(|(index, ty)| format!("p{index}: {}", rust_core_type(*ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let call_params = (0..input_types.len())
        .map(|index| format!("p{index}"))
        .collect::<Vec<_>>();
    let call_prefix = if call_params.is_empty() {
        String::new()
    } else {
        format!("{}, ", call_params.join(", "))
    };
    let ignored = if input_types.is_empty() {
        String::new()
    } else {
        format!("        let _ = ({});\n", call_params.join(", "))
    };
    let signature_params = if params.is_empty() {
        "output: &mut [u8]".to_owned()
    } else {
        format!("{params}, output: &mut [u8]")
    };
    let arity_lint = too_many_arguments_attribute(input_types.len() + 1, 20);

    format!(
        "        #[inline]\n\
                 {arity_lint}pub fn {function_ident}({signature_params})\n\
                     -> core::result::Result<usize, super::DynamicOutputError>\n\
                 {{\n\
                     #[cfg(target_arch = \"wasm32\")]\n\
                     {{\n\
                         let output_pointer = output.as_mut_ptr() as usize;\n\
                         if output_pointer > u32::MAX as usize || output.len() > u32::MAX as usize {{\n\
                             return Err(super::DynamicOutputError {{\n\
                                 error: crate::ApiError::new(crate::ErrorCode::OutOfBounds as i32),\n\
                                 required: 0,\n\
                             }});\n\
                         }}\n\
                         let mut descriptor = [\n\
                             output_pointer as u32,\n\
                             output.len() as u32,\n\
                             0u32,\n\
                         ];\n\
                         let descriptor_pointer = descriptor.as_mut_ptr() as usize;\n\
                         if descriptor_pointer > u32::MAX as usize {{\n\
                             return Err(super::DynamicOutputError {{\n\
                                 error: crate::ApiError::new(crate::ErrorCode::OutOfBounds as i32),\n\
                                 required: 0,\n\
                             }});\n\
                         }}\n\
                         let status = unsafe {{ raw::{function_ident}({call_prefix}descriptor_pointer as u32 as i32) }};\n\
                         let required = descriptor[2] as usize;\n\
                         if status == 0 {{\n\
                             Ok(required)\n\
                         }} else {{\n\
                             Err(super::DynamicOutputError {{\n\
                                 error: crate::ApiError::new(status),\n\
                                 required,\n\
                             }})\n\
                         }}\n\
                     }}\n\
                     #[cfg(not(target_arch = \"wasm32\"))]\n\
                     {{\n\
         {ignored}\
                         let _ = output;\n\
                         Err(super::DynamicOutputError {{\n\
                             error: unreachable!(),\n\
                             required: 0,\n\
                         }})\n\
                     }}\n\
                 }}\n",
        function_ident = function_ident,
        signature_params = signature_params,
        call_prefix = call_prefix,
        ignored = ignored,
    )
}

fn too_many_arguments_attribute(count: usize, indent: usize) -> String {
    if count > 7 {
        format!(
            "#[expect(clippy::too_many_arguments, reason = \"Core function preserves the corresponding Lua API arity\")]\n{}",
            " ".repeat(indent)
        )
    } else {
        String::new()
    }
}

fn rust_core_type(ty: CoreType) -> &'static str {
    match ty {
        CoreType::I32 => "i32",
        CoreType::I64 => "i64",
        CoreType::F32 => "f32",
        CoreType::F64 => "f64",
    }
}

fn rust_ident(value: &str) -> String {
    match value {
        "type" | "match" | "move" | "ref" | "self" | "Self" | "super" | "crate" | "where"
        | "loop" | "in" | "mod" | "fn" | "struct" | "enum" | "use" | "pub" | "impl" | "trait"
        | "const" | "static" | "async" | "await" | "dyn" | "abstract" | "become" | "box" | "do"
        | "final" | "macro" | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield"
        | "try" => {
            format!("r#{value}")
        }
        _ => value.to_owned(),
    }
}

fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records
                .entry(record.name.clone())
                .or_insert_with(|| record.clone());
        }
    }
    records
}
