//! WIT/Component Model renderer for the normalized API model.

use heck::ToKebabCase;

// WIT reserves these spellings even when they occur as a field, parameter,
// function, or user-defined type name.  `%name` is WIT's explicit-identifier
// escape and preserves the semantic name after parsing.  Keep this mapping in
// the renderer rather than changing the canonical C/Rust model: the native
// ABI really does have fields such as `type`.
pub(crate) fn wit_identifier(name: &str) -> String {
    let name = name.to_kebab_case();
    if matches!(
        name.as_str(),
        "use"
            | "type"
            | "func"
            | "u8"
            | "u16"
            | "u32"
            | "u64"
            | "s8"
            | "s16"
            | "s32"
            | "s64"
            | "f32"
            | "f64"
            | "char"
            | "own"
            | "borrow"
            | "resource"
            | "record"
            | "flags"
            | "variant"
            | "enum"
            | "bool"
            | "string"
            | "option"
            | "result"
            | "future"
            | "stream"
            | "error-context"
            | "list"
            | "map"
            | "_"
            | "as"
            | "from"
            | "static"
            | "interface"
            | "tuple"
            | "import"
            | "export"
            | "world"
            | "package"
            | "constructor"
            | "include"
            | "with"
            | "async"
    ) {
        format!("%{name}")
    } else {
        name
    }
}

/// Return the semantic field/variant name exposed by the Component Model.
///
/// WIT source escapes reserved identifiers with a leading `%`, but that
/// escape is syntax rather than part of the runtime name carried by a
/// component record or enum value.
pub(crate) fn wit_runtime_identifier(name: &str) -> String {
	let identifier = wit_identifier(name);
	identifier
		.strip_prefix('%')
		.unwrap_or(identifier.as_str())
		.to_owned()
}
use std::collections::{BTreeMap, BTreeSet};

use crate::model::{ApiModel, ApiModule, Environment, FunctionModel, RecordModel, SemanticType};

pub fn render_module(module: &ApiModule) -> String {
    // Keep the marker after the package declaration.  WIT treats comments
    // before `package` as package documentation; repeating that documentation
    // in every split interface file makes the directory package invalid.
    let mut output = String::from(
        "package recoil:spring-api@1.0.0;\n\n/* @generated by spring-api-codegen; do not edit. */\n\n",
    );
    output.push_str(&format!("interface {} {{\n", wit_identifier(&module.name)));
    output.push_str("  record spring-error { code: s32 }\n\n");

    for record in module_records(module) {
        if record.name == "Error" {
            continue;
        }
        output.push_str(&format!("  record {} {{\n", wit_identifier(&record.name)));
        for field in &record.fields {
            output.push_str(&format!(
                "    {}: {},\n",
                wit_identifier(&field.name),
                wit_type(&field.ty)
            ));
        }
        output.push_str("  }\n\n");
    }

    for enum_def in module_enums(module) {
        output.push_str(&format!("  enum {} {{\n", wit_identifier(&enum_def.name)));
        for variant in enum_def.variants.keys() {
            output.push_str(&format!("    {},\n", wit_identifier(variant)));
        }
        output.push_str("  }\n\n");
    }

    for function in &module.functions {
        if function.outputs.len() > 1 {
            output.push_str(&format!(
                "  record {}-value {{\n",
                wit_identifier(&function.name)
            ));
            for field in &function.outputs {
                output.push_str(&format!(
                    "    {}: {},\n",
                    wit_identifier(&field.name),
                    wit_type(&field.ty)
                ));
            }
            output.push_str("  }\n\n");
        }
        output.push_str(&render_function(function));
    }
    output.push_str("}\n");
    output
}

/// Split one semantic module into interfaces that can safely be imported by
/// different worlds. A WIT interface is an all-or-nothing capability, so a
/// mixed read/control interface cannot be imported into an unsynced world.
pub fn interface_variants(module: &ApiModule) -> Vec<(String, ApiModule)> {
    if module.functions.is_empty() {
        return Vec::new();
    }

    let mut groups: BTreeMap<BTreeSet<Environment>, Vec<FunctionModel>> = BTreeMap::new();
    for function in &module.functions {
        groups
            .entry(function.environments.clone())
            .or_default()
            .push(function.clone());
    }

    let split = groups.len() > 1;
    groups
        .into_iter()
        .map(|(environments, mut functions)| {
            functions.sort_by(|left, right| left.name.cmp(&right.name));
            let name = if split {
                format!(
                    "{}-{}",
                    module.name,
                    environments
                        .iter()
                        .map(|environment| environment.as_str())
                        .collect::<Vec<_>>()
                        .join("-")
                )
            } else {
                module.name.clone()
            };
            let mut variant = module.clone();
            variant.name = name.clone();
            variant.functions = functions;
            (name, variant)
        })
        .collect()
}

fn module_records(module: &ApiModule) -> Vec<&RecordModel> {
    let mut names = BTreeSet::new();
    for function in &module.functions {
        names.insert(function.query.clone());
        names.insert(function.result.clone());
        for field in function.inputs.iter().chain(&function.outputs) {
            collect_record_names(&field.ty, &mut names);
        }
    }
    let mut cursor = 0;
    let mut ordered = names.iter().cloned().collect::<Vec<_>>();
    while cursor < ordered.len() {
        if let Some(record) = module
            .records
            .iter()
            .find(|record| record.name == ordered[cursor])
        {
            for field in &record.fields {
                collect_record_names(&field.ty, &mut names);
            }
        }
        ordered = names.iter().cloned().collect();
        cursor += 1;
    }
    let mut records = module
        .records
        .iter()
        .filter(|record| {
            names.contains(&record.name) && record.name != "Error" && !record.fields.is_empty()
        })
        .collect::<Vec<_>>();
    records.sort_by(|left, right| left.name.cmp(&right.name));
    records
}

fn module_enums(module: &ApiModule) -> Vec<&crate::model::EnumModel> {
    let records = module_records(module);
    let mut names = BTreeSet::new();
    for record in records {
        for field in &record.fields {
            collect_enum_names(&field.ty, &mut names);
        }
    }
    for function in &module.functions {
        for field in function.inputs.iter().chain(&function.outputs) {
            collect_enum_names(&field.ty, &mut names);
        }
    }
    let mut enums = module
        .enums
        .iter()
        .filter(|enum_def| names.contains(&enum_def.name))
        .collect::<Vec<_>>();
    enums.sort_by(|left, right| left.name.cmp(&right.name));
    enums
}

fn collect_record_names(ty: &SemanticType, names: &mut BTreeSet<String>) {
    match ty {
        SemanticType::Record { name } => {
            names.insert(name.clone());
        }
        SemanticType::List { element }
        | SemanticType::FixedArray { element, .. }
        | SemanticType::Option { inner: element }
        | SemanticType::Pointer {
            pointee: element, ..
        } => collect_record_names(element, names),
        SemanticType::Result { ok, error } => {
            if let Some(ok) = ok {
                collect_record_names(ok, names);
            }
            if let Some(error) = error {
                collect_record_names(error, names);
            }
        }
        _ => {}
    }
}

fn collect_enum_names(ty: &SemanticType, names: &mut BTreeSet<String>) {
    match ty {
        SemanticType::Enum { name } => {
            names.insert(name.clone());
        }
        SemanticType::List { element }
        | SemanticType::FixedArray { element, .. }
        | SemanticType::Option { inner: element }
        | SemanticType::Pointer {
            pointee: element, ..
        } => collect_enum_names(element, names),
        SemanticType::Result { ok, error } => {
            if let Some(ok) = ok {
                collect_enum_names(ok, names);
            }
            if let Some(error) = error {
                collect_enum_names(error, names);
            }
        }
        _ => {}
    }
}

pub fn render_world(model: &ApiModel, environment: Environment) -> String {
    let mut output = String::from(
        "package recoil:spring-api@1.0.0;\n\n/* @generated by spring-api-codegen; do not edit. */\n\n",
    );
    output.push_str(&format!(
        "world {} {{\n",
        wit_identifier(environment.as_str())
    ));
    for module in &model.modules {
        for (name, variant) in interface_variants(module) {
            if variant
                .functions
                .iter()
                .any(|function| function.environments.contains(&environment))
            {
                output.push_str(&format!("  import {};\n", wit_identifier(&name)));
            }
        }
    }
    output.push_str(&format!(
        "  export callins-{};\n",
        wit_identifier(environment.as_str())
    ));
    output.push_str("}\n");
    output
}

/// Validate the generated interface/world topology before artifacts are
/// written. These are generator invariants, not runtime diagnostics: an
/// empty or unimported interface is almost always a stale module split.
pub fn validate_world_graph(model: &ApiModel) -> anyhow::Result<()> {
    let mut errors = Vec::new();
    for module in &model.modules {
        for (name, variant) in interface_variants(module) {
            if variant.functions.is_empty() {
                errors.push(format!("{name}: emitted interface has zero functions"));
            }
            let imported_by_world = Environment::ALL.iter().any(|environment| {
                variant
                    .functions
                    .iter()
                    .any(|function| function.environments.contains(environment))
            });
            if !imported_by_world {
                errors.push(format!("{name}: emitted interface is imported by no world"));
            }
            for function in &variant.functions {
                if function.mutating
                    && function
                        .environments
                        .iter()
                        .any(|environment| !environment.is_synced())
                {
                    errors.push(format!(
                        "{name}::{}: mutating function appears in an unsynced or UI world",
                        function.name
                    ));
                }
            }
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(anyhow::anyhow!(errors.join("\n")))
    }
}

fn render_function(function: &FunctionModel) -> String {
    let inputs = function
        .inputs
        .iter()
        .map(|field| format!("{}: {}", wit_identifier(&field.name), wit_type(&field.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let outputs = function
        .outputs
        .iter()
        .map(|field| wit_type(&field.ty))
        .collect::<Vec<_>>();
    let result = match outputs.as_slice() {
        // WIT spells an empty successful result as `result<_, error>`; `()`
        // is a Rust façade type, not a valid WIT type expression.
        [] => "result<_, spring-error>".to_string(),
        [single] => format!("result<{single}, spring-error>"),
        _ => format!(
            "result<{}-value, spring-error>",
            wit_identifier(&function.name)
        ),
    };
    format!(
        "  /// {}\n  {}: func({}) -> {};\n\n",
        if function.mutating {
            "mutating"
        } else {
            "read-only"
        },
        wit_identifier(&function.name),
        inputs,
        result
    )
}

pub(crate) fn wit_type(ty: &SemanticType) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i8" => "s8".to_string(),
            "i16" => "s16".to_string(),
            "i32" => "s32".to_string(),
            "u8" | "char" => "u8".to_string(),
            "u16" => "u16".to_string(),
            "u32" => "u32".to_string(),
            "u64" => "u64".to_string(),
            "f32" => "f32".to_string(),
            "bool" => "bool".to_string(),
            _ => "s64".to_string(),
        },
        SemanticType::Enum { name } => wit_identifier(name),
        SemanticType::Record { name } if name == "Error" => "spring-error".to_string(),
        SemanticType::Record { name } => wit_identifier(name),
        SemanticType::String => "string".to_string(),
        SemanticType::Bytes => "list<u8>".to_string(),
        SemanticType::List { element } => format!("list<{}>", wit_type(element)),
        SemanticType::FixedArray { element, .. } => format!("list<{}>", wit_type(element)),
        SemanticType::Option { inner } => format!("option<{}>", wit_type(inner)),
        SemanticType::Result { ok, .. } => ok
            .as_deref()
            .map(wit_type)
            .unwrap_or_else(|| "unit".to_string()),
        SemanticType::Handle { .. } => "u64".to_string(),
        SemanticType::Callback { .. } => "u32".to_string(),
        SemanticType::Pointer { .. } | SemanticType::Unknown { .. } => "u32".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{ApiModule, FunctionModel, LoweringStatus};
    use std::collections::BTreeSet;

    #[test]
    fn renders_semantic_result_and_world() {
        let module = ApiModule {
            name: "test_api".to_string(),
            interface_version: "1.0".to_string(),
            functions: vec![FunctionModel {
                name: "GetValue".to_string(),
                query: "GetValueQuery".to_string(),
                result: "GetValueResult".to_string(),
                inputs: Vec::new(),
                outputs: Vec::new(),
                environments: BTreeSet::from([Environment::RulesSynced]),
                mutating: false,
                visibility_sensitive: false,
                status: LoweringStatus::Automatic,
                notes: Vec::new(),
            }],
            records: Vec::new(),
            enums: Vec::new(),
        };
        let model = ApiModel {
            model_version: 1,
            native_api_version: None,
            modules: vec![module],
            callins: Vec::new(),
        };
        assert!(render_module(&model.modules[0]).contains("get-value"));
        assert!(render_world(&model, Environment::RulesSynced).contains("test-api"));
    }
}
