//! Spring Core-WebAssembly ABI planning.
//!
//! This module has no Wasmtime dependency. It converts the shared semantic API
//! model into a runtime-neutral Core ABI plan which later renderers can use for
//! C++ host callbacks, validation metadata and guest SDK bindings.

use heck::ToKebabCase;
use serde::Serialize;
use std::collections::{BTreeMap, BTreeSet};

use crate::model::{
    ApiModel, Environment, FieldModel, FunctionModel, LoweringStatus, RecordModel, SemanticType,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum CoreType {
    I32,
    I64,
    F32,
    F64,
}

impl CoreType {
    const fn signature(self) -> &'static str {
        match self {
            Self::I32 => "i32",
            Self::I64 => "i64",
            Self::F32 => "f32",
            Self::F64 => "f64",
        }
    }

    const fn bytes(self) -> u32 {
        match self {
            Self::I32 | Self::F32 => 4,
            Self::I64 | Self::F64 => 8,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum InputStrategy {
    Direct,
    FixedInputBuffer,
    VariableInputBuffer,
    Unsupported,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ResultStrategy {
    Status,
    Packed32,
    FixedOutputBuffer { bytes: u32, alignment: u32 },
    VariableOutputBuffer,
    Unsupported,
}

#[derive(Debug, Clone, Serialize)]
pub struct FunctionPlan {
    pub module: String,
    pub function: String,
    pub import_module: String,
    pub import_name: String,
    pub environment_mask: u32,
    pub mutating: bool,
    pub visibility_sensitive: bool,
    pub source_status: String,
    pub input_strategy: InputStrategy,
    pub result_strategy: ResultStrategy,
    pub direct_params: Vec<CoreType>,
    pub direct_results: Vec<CoreType>,
    pub signature: String,
    pub notes: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct CoreAbiPlan {
    pub abi_version: u32,
    pub functions: Vec<FunctionPlan>,
    pub automatic_count: usize,
    pub manual_count: usize,
    pub unsupported_count: usize,
}

pub fn plan(model: &ApiModel) -> CoreAbiPlan {
    let records = record_index(model);
    let mut functions = model
        .modules
        .iter()
        .flat_map(|module| {
            module
                .functions
                .iter()
                .map(|function| plan_function(&module.name, function, &records))
        })
        .collect::<Vec<_>>();
    functions.sort_by(|a, b| a.module.cmp(&b.module).then_with(|| a.function.cmp(&b.function)));

    let mut automatic_count = 0;
    let mut manual_count = 0;
    let mut unsupported_count = 0;
    for function in &functions {
        if matches!(function.input_strategy, InputStrategy::Unsupported)
            || matches!(function.result_strategy, ResultStrategy::Unsupported)
            || function.source_status == "unsupported"
        {
            unsupported_count += 1;
        } else if function.source_status == "manual" || function.source_status == "annotated" {
            manual_count += 1;
        } else {
            automatic_count += 1;
        }
    }

    CoreAbiPlan {
        abi_version: 1,
        functions,
        automatic_count,
        manual_count,
        unsupported_count,
    }
}

pub fn render_json(model: &ApiModel) -> anyhow::Result<String> {
    Ok(serde_json::to_string_pretty(&plan(model))? + "\n")
}

/// Diagnostic candidate inventory. The runtime must continue to validate
/// against only callbacks actually compiled into its executable registry.
pub fn render_inventory_header(model: &ApiModel) -> String {
    let mut output = String::from(
        "/* @generated by spring-api-codegen; do not edit. */\n#pragma once\n\n#include <cstdint>\n#include <string_view>\n\nnamespace recoil::wasm::core::generated {\n\nenum class Strategy : std::uint8_t { direct, fixedInput, variableInput, fixedOutput, variableOutput, manual, unsupported };\nstruct Candidate { std::string_view module; std::string_view name; std::string_view signature; std::uint32_t environmentMask; Strategy strategy; };\n\ninline constexpr Candidate kCandidates[] = {\n",
    );
    for function in plan(model).functions {
        output.push_str(&format!(
            "\t{{\"{}\", \"{}\", \"{}\", {}u, Strategy::{}}},\n",
            cpp_escape(&function.import_module),
            cpp_escape(&function.import_name),
            cpp_escape(&function.signature),
            function.environment_mask,
            strategy_name(&function),
        ));
    }
    output.push_str("};\n\n} // namespace recoil::wasm::core::generated\n");
    output
}

fn strategy_name(plan: &FunctionPlan) -> &'static str {
    if plan.source_status == "unsupported"
        || matches!(plan.input_strategy, InputStrategy::Unsupported)
        || matches!(plan.result_strategy, ResultStrategy::Unsupported)
    {
        return "unsupported";
    }
    if plan.source_status == "manual" || plan.source_status == "annotated" {
        return "manual";
    }
    match (plan.input_strategy, plan.result_strategy) {
        (InputStrategy::VariableInputBuffer, _) => "variableInput",
        (InputStrategy::FixedInputBuffer, _) => "fixedInput",
        (_, ResultStrategy::VariableOutputBuffer) => "variableOutput",
        (_, ResultStrategy::FixedOutputBuffer { .. }) => "fixedOutput",
        _ => "direct",
    }
}

fn plan_function(
    module: &str,
    function: &FunctionModel,
    records: &BTreeMap<String, RecordModel>,
) -> FunctionPlan {
    let mut notes = function.notes.clone();
    let mut direct_params = Vec::new();
    let input_strategy = classify_inputs(&function.inputs, records, &mut direct_params, &mut notes);
    let (result_strategy, mut direct_results) = classify_outputs(&function.outputs, records, &mut notes);
    let string_list = function
        .inputs
        .iter()
        .chain(function.outputs.iter())
        .any(|field| contains_string_list(&field.ty));
    if string_list {
        notes.push(
            "list<string> requires a reviewed flat Core ABI; per-element host allocation is forbidden"
                .to_owned(),
        );
    }

    match input_strategy {
        InputStrategy::Direct | InputStrategy::Unsupported => {}
        InputStrategy::FixedInputBuffer => {
            // Generic fixed aggregate input: one pointer to the generated query
            // wire record. A specialized renderer may flatten/bit-pack known
            // records (e.g. flags) without changing semantic API behavior.
            direct_params.push(CoreType::I32);
        }
        InputStrategy::VariableInputBuffer => {
            // Generic variable input record begins with a wasm32 descriptor
            // pointer. The descriptor contains ptr/len pairs for variable data.
            direct_params.push(CoreType::I32);
        }
    }

    match result_strategy {
        ResultStrategy::FixedOutputBuffer { .. } | ResultStrategy::VariableOutputBuffer => {
            direct_params.push(CoreType::I32);
            direct_results = vec![CoreType::I32];
        }
        _ => {}
    }

    FunctionPlan {
        module: module.to_owned(),
        function: function.name.clone(),
        import_module: format!("spring:{}", module.replace('_', "-")),
        import_name: function.name.to_kebab_case(),
        environment_mask: environment_mask(&function.environments),
        mutating: function.mutating,
        visibility_sensitive: function.visibility_sensitive,
        source_status: if string_list {
            "manual".to_owned()
        } else {
            status_name(function.status).to_owned()
        },
        input_strategy,
        result_strategy,
        signature: core_signature(&direct_params, &direct_results),
        direct_params,
        direct_results,
        notes,
    }
}

fn contains_string_list(ty: &SemanticType) -> bool {
    match ty {
        SemanticType::List { element } => {
            matches!(element.as_ref(), SemanticType::String) || contains_string_list(element)
        }
        SemanticType::FixedArray { element, .. } | SemanticType::Option { inner: element } => {
            contains_string_list(element)
        }
        SemanticType::Result { ok, error } => {
            ok.as_deref().is_some_and(contains_string_list)
                || error.as_deref().is_some_and(contains_string_list)
        }
        SemanticType::Pointer { pointee, .. } => contains_string_list(pointee),
        _ => false,
    }
}

fn classify_inputs(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
    direct: &mut Vec<CoreType>,
    notes: &mut Vec<String>,
) -> InputStrategy {
    let mut has_fixed = false;
    let mut has_variable = false;
    for field in fields {
        if let Some(core) = direct_type(&field.ty) {
            direct.push(core);
        } else if fixed_layout(&field.ty, records).is_some() {
            has_fixed = true;
        } else if field.ty.is_variable_size() {
            has_variable = true;
        } else {
            notes.push(format!("unsupported Core input field {}", field.name));
            return InputStrategy::Unsupported;
        }
    }
    if has_variable {
        InputStrategy::VariableInputBuffer
    } else if has_fixed {
        InputStrategy::FixedInputBuffer
    } else {
        InputStrategy::Direct
    }
}

fn classify_outputs(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
    notes: &mut Vec<String>,
) -> (ResultStrategy, Vec<CoreType>) {
    if fields.is_empty() {
        return (ResultStrategy::Status, vec![CoreType::I32]);
    }
    if fields.len() == 1 {
        let ty = &fields[0].ty;
        if let Some(core) = direct_type(ty) {
            return if matches!(core, CoreType::I32 | CoreType::F32) {
                (ResultStrategy::Packed32, vec![CoreType::I64])
            } else {
                (
                    ResultStrategy::FixedOutputBuffer {
                        bytes: core.bytes(),
                        alignment: core.bytes().min(8),
                    },
                    vec![CoreType::I32],
                )
            };
        }
        if let Some((bytes, alignment)) = fixed_layout(ty, records) {
            return (
                ResultStrategy::FixedOutputBuffer { bytes, alignment },
                vec![CoreType::I32],
            );
        }
        if ty.is_variable_size() {
            return (ResultStrategy::VariableOutputBuffer, vec![CoreType::I32]);
        }
    } else if let Some((bytes, alignment)) = layout_fields(fields, records) {
        return (
            ResultStrategy::FixedOutputBuffer { bytes, alignment },
            vec![CoreType::I32],
        );
    } else if fields.iter().any(|field| field.ty.is_variable_size()) {
        return (ResultStrategy::VariableOutputBuffer, vec![CoreType::I32]);
    }

    notes.push("result requires manual Core ABI lowering".to_owned());
    (ResultStrategy::Unsupported, Vec::new())
}

fn direct_type(ty: &SemanticType) -> Option<CoreType> {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i8" | "u8" | "char" | "i16" | "u16" | "i32" | "u32" | "bool" => {
                Some(CoreType::I32)
            }
            "i64" | "u64" | "isize" | "usize" => Some(CoreType::I64),
            "f32" => Some(CoreType::F32),
            "f64" => Some(CoreType::F64),
            _ => None,
        },
        SemanticType::Enum { .. } => Some(CoreType::I32),
        SemanticType::Handle { .. } => Some(CoreType::I64),
        SemanticType::Callback { .. } => Some(CoreType::I32),
        _ => None,
    }
}

fn fixed_layout(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    if let Some(core) = direct_type(ty) {
        return Some((core.bytes(), core.bytes().min(8)));
    }
    match ty {
        SemanticType::FixedArray { element, length } => {
            let (bytes, alignment) = fixed_layout(element, records)?;
            Some((bytes.checked_mul(u32::try_from(*length).ok()?)?, alignment))
        }
        SemanticType::Record { name } => layout_fields(&records.get(name)?.fields, records),
        SemanticType::Option { inner } => {
            let (payload_bytes, payload_alignment) = fixed_layout(inner, records)?;
            let alignment = payload_alignment.max(4);
            let payload_offset = align_up(4, payload_alignment);
            Some((align_up(payload_offset.checked_add(payload_bytes)?, alignment), alignment))
        }
        _ => None,
    }
}

fn layout_fields(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    let mut bytes = 0u32;
    let mut alignment = 1u32;
    for field in fields {
        let (field_bytes, field_alignment) = fixed_layout(&field.ty, records)?;
        bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
        alignment = alignment.max(field_alignment);
    }
    Some((align_up(bytes, alignment), alignment))
}

fn align_up(value: u32, alignment: u32) -> u32 {
    debug_assert!(alignment.is_power_of_two());
    (value + alignment - 1) & !(alignment - 1)
}

fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records.entry(record.name.clone()).or_insert_with(|| record.clone());
        }
    }
    records
}

fn environment_mask(environments: &BTreeSet<Environment>) -> u32 {
    environments.iter().fold(0, |mask, environment| {
        let bit = match environment {
            Environment::RulesSynced => 0,
            Environment::RulesUnsynced => 1,
            Environment::GaiaSynced => 2,
            Environment::GaiaUnsynced => 3,
            Environment::Ui => 4,
        };
        mask | (1 << bit)
    })
}

fn status_name(status: LoweringStatus) -> &'static str {
    match status {
        LoweringStatus::Automatic => "automatic",
        LoweringStatus::Annotated => "annotated",
        LoweringStatus::Manual => "manual",
        LoweringStatus::Unsupported => "unsupported",
    }
}

fn core_signature(params: &[CoreType], results: &[CoreType]) -> String {
    format!(
        "{}->{}",
        params
            .iter()
            .map(|value| value.signature())
            .collect::<Vec<_>>()
            .join(","),
        results
            .iter()
            .map(|value| value.signature())
            .collect::<Vec<_>>()
            .join(",")
    )
}

fn cpp_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn signatures_are_stable() {
        assert_eq!(
            core_signature(&[CoreType::I32, CoreType::F32], &[CoreType::I64]),
            "i32,f32->i64"
        );
    }
}
