//! Generate Core-Wasm host callbacks for calls that have both variable-size
//! input and caller-owned variable-size output. Input and output descriptors
//! are separate wasm32 pointers so guest wrappers can prepare/retry outputs
//! without rebuilding input payloads.

use heck::{ToLowerCamelCase, ToSnakeCase};
use std::collections::BTreeMap;

use crate::model::{ApiModel, FieldModel, RecordModel, SemanticType};
use crate::render_core_wasm::{self, CoreType, FunctionPlan, InputStrategy, ResultStrategy};

pub fn render_header() -> String {
    r#"/* @generated by spring-api-codegen; do not edit. */
#pragma once

#include <string>

#include "WasmInterface/WasmCoreBindings.h"

namespace recoil::wasm::core::generated {

bool RegisterGeneratedVariableIoImports(wasmtime_linker_t* linker, HostState* state,
    std::string& error);

} // namespace recoil::wasm::core::generated
"#
    .to_owned()
}

pub fn render_cpp(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();
    let mut callbacks = String::new();
    let mut registrations = String::new();
    let mut generated_count = 0usize;

    for module in &model.modules {
        for function in &module.functions {
            let Some(plan) = plans.get(&(module.name.clone(), function.name.clone())) else {
                continue;
            };
            if !eligible(plan, &function.inputs, &function.outputs, &records) {
                continue;
            }
            generated_count += 1;
            callbacks.push_str(&render_callback(&module.name, function, plan, &records));
            callbacks.push('\n');
            registrations.push_str(&render_registration(
                plan,
                &callback_name(&module.name, &function.name),
            ));
        }
    }

    format!(
        r#"/* @generated by spring-api-codegen; do not edit. */

#include "wasm/generated/WasmCoreGeneratedVariableIoBindings.h"

#include <array>
#include <bit>
#include <cstdint>
#include <limits>
#include <span>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

#include "NativeInterface/NativeInterface.h"
#include "WasmInterface/WasmCoreAbi.h"
#include "WasmInterface/WasmCoreGeneratedSupport.h"
#include "WasmInterface/WasmCoreWire.h"

namespace recoil::wasm::core::generated {{
namespace {{

template<typename T>
bool AssignCoreCount(std::uint32_t value, T& output)
{{
    using Native = std::remove_cv_t<std::remove_reference_t<T>>;
    if constexpr (std::numeric_limits<Native>::is_signed) {{
        if (static_cast<std::uint64_t>(value) >
            static_cast<std::uint64_t>(std::numeric_limits<Native>::max()))
            return false;
    }}
    output = static_cast<Native>(value);
    return true;
}}

bool WriteCoreU32(std::span<std::uint8_t> bytes, std::size_t offset, std::uint32_t value)
{{
    if (offset > bytes.size() || bytes.size() - offset < 4)
        return false;
    bytes[offset + 0] = static_cast<std::uint8_t>(value);
    bytes[offset + 1] = static_cast<std::uint8_t>(value >> 8);
    bytes[offset + 2] = static_cast<std::uint8_t>(value >> 16);
    bytes[offset + 3] = static_cast<std::uint8_t>(value >> 24);
    return true;
}}

bool DefineGeneratedVariableIo(wasmtime_linker_t* linker, const char* moduleName,
    const char* functionName, wasm_functype_t* type,
    wasmtime_func_unchecked_callback_t callback, HostState* state, std::string& error)
{{
    wasmtime_error_t* defineError = wasmtime_linker_define_func_unchecked(
        linker,
        moduleName, std::char_traits<char>::length(moduleName),
        functionName, std::char_traits<char>::length(functionName),
        type, callback, state, nullptr);
    wasm_functype_delete(type);
    if (defineError == nullptr)
        return true;
    error = ErrorMessage(defineError);
    return false;
}}

{callbacks}
}} // namespace

bool RegisterGeneratedVariableIoImports(wasmtime_linker_t* linker, HostState* state,
    std::string& error)
{{
    if (linker == nullptr || state == nullptr || state->native == nullptr) {{
        error = "cannot register generated variable-I/O Core imports without linker/host/native API";
        return false;
    }}
{registrations}
    return true;
}}

static_assert({generated_count} >= 0, "generated variable-I/O Core callback count");

}} // namespace recoil::wasm::core::generated
"#,
        callbacks = callbacks,
        registrations = registrations,
        generated_count = generated_count,
    )
}

pub(crate) fn eligible(
    plan: &FunctionPlan,
    inputs: &[FieldModel],
    outputs: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    if matches!(plan.source_status.as_str(), "manual" | "unsupported")
        || !matches!(plan.input_strategy, InputStrategy::VariableInputBuffer)
        || !matches!(plan.result_strategy, ResultStrategy::VariableOutputBuffer)
    {
        return false;
    }
    input_descriptor_layout(inputs, records).is_some()
        && inputs.iter().all(|field| input_field_supported(field, records))
        && output_descriptor_layout(outputs, records).is_some()
        && outputs.iter().all(|field| output_field_supported(field, records))
        && outputs.iter().any(|field| variable_type(&field.ty))
}

fn direct_type(ty: &SemanticType) -> bool {
    matches!(
        ty,
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. }
    )
}

fn input_field_supported(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> bool {
    if direct_type(&field.ty) || fixed_wire_type(&field.ty, records) {
        return true;
    }
    match &field.ty {
        SemanticType::String => true,
        SemanticType::Bytes => count_field(field).is_some(),
        SemanticType::List { element } => {
            count_field(field).is_some() && input_list_element_supported(element, records)
        }
        _ => false,
    }
}

fn input_list_element_supported(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    match ty {
        SemanticType::String => true,
        SemanticType::Scalar { name }
            if !matches!(name.as_str(), "bool" | "isize" | "usize") => true,
        SemanticType::Enum { .. } => true,
        SemanticType::Record { .. } => fixed_wire_type(ty, records),
        _ => false,
    }
}

fn output_field_supported(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> bool {
    match &field.ty {
        SemanticType::String => true,
        SemanticType::Bytes => count_field(field).is_some(),
        SemanticType::List { element } => {
            count_field(field).is_some() && output_list_element_supported(element, records)
        }
        other => fixed_wire_type(other, records),
    }
}

fn output_list_element_supported(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    match ty {
        SemanticType::Scalar { name }
            if !matches!(name.as_str(), "bool" | "isize" | "usize") => true,
        SemanticType::Enum { .. } => true,
        SemanticType::Record { .. } => fixed_wire_type(ty, records),
        _ => false,
    }
}

fn variable_type(ty: &SemanticType) -> bool {
    matches!(ty, SemanticType::String | SemanticType::Bytes | SemanticType::List { .. })
}

fn fixed_wire_type(ty: &SemanticType, records: &BTreeMap<String, RecordModel>) -> bool {
    match ty {
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. } => true,
        SemanticType::FixedArray { element, length } => {
            *length <= 64 && fixed_wire_type(element, records)
        }
        SemanticType::Record { name } => records
            .get(name)
            .is_some_and(|record| record.fields.iter().all(|field| fixed_wire_type(&field.ty, records))),
        _ => false,
    }
}

fn fixed_wire_layout(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i64" | "u64" | "isize" | "usize" | "f64" => Some((8, 8)),
            _ => Some((4, 4)),
        },
        SemanticType::Enum { .. } => Some((4, 4)),
        SemanticType::Handle { .. } => Some((8, 8)),
        SemanticType::FixedArray { element, length } => {
            let (bytes, alignment) = fixed_wire_layout(element, records)?;
            Some((bytes.checked_mul(u32::try_from(*length).ok()?)?, alignment))
        }
        SemanticType::Record { name } => layout_fields(&records.get(name)?.fields, records),
        _ => None,
    }
}

fn layout_fields(fields: &[FieldModel], records: &BTreeMap<String, RecordModel>) -> Option<(u32, u32)> {
    let mut bytes = 0u32;
    let mut alignment = 1u32;
    for field in fields {
        let (field_bytes, field_alignment) = fixed_wire_layout(&field.ty, records)?;
        bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
        alignment = alignment.max(field_alignment);
    }
    Some((align_up(bytes, alignment), alignment))
}

fn input_descriptor_field_layout(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    if variable_type(ty) {
        Some((8, 4))
    } else {
        fixed_wire_layout(ty, records)
    }
}

fn input_descriptor_layout(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    let mut bytes = 0u32;
    let mut alignment = 1u32;
    let mut any = false;
    for field in fields.iter().filter(|field| !direct_type(&field.ty)) {
        let (field_bytes, field_alignment) = input_descriptor_field_layout(&field.ty, records)?;
        bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
        alignment = alignment.max(field_alignment);
        any = true;
    }
    any.then(|| (align_up(bytes, alignment), alignment))
}

#[derive(Clone, Copy)]
struct OutputLayout {
    descriptor_bytes: u32,
    fixed_offset: u32,
    fixed_bytes: u32,
    fixed_alignment: u32,
}

fn output_descriptor_layout(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<OutputLayout> {
    let variable_count = fields.iter().filter(|field| variable_type(&field.ty)).count();
    let header_bytes = u32::try_from(variable_count).ok()?.checked_mul(12)?;
    let fixed = fields
        .iter()
        .filter(|field| !variable_type(&field.ty))
        .cloned()
        .collect::<Vec<_>>();
    let (fixed_bytes, fixed_alignment) = if fixed.is_empty() {
        (0, 1)
    } else {
        layout_fields(&fixed, records)?
    };
    let fixed_offset = align_up(header_bytes, fixed_alignment);
    Some(OutputLayout {
        descriptor_bytes: fixed_offset.checked_add(fixed_bytes)?,
        fixed_offset,
        fixed_bytes,
        fixed_alignment,
    })
}

fn align_up(value: u32, alignment: u32) -> u32 {
    (value + alignment - 1) & !(alignment - 1)
}

fn render_callback(
    module_name: &str,
    function: &crate::model::FunctionModel,
    plan: &FunctionPlan,
    records: &BTreeMap<String, RecordModel>,
) -> String {
    let callback = callback_name(module_name, &function.name);
    let api_member = native_member(module_name);
    let api_guard = native_guard(module_name);
    let slot_count = plan.direct_params.len().max(plan.direct_results.len());
    let direct_input_count = function.inputs.iter().filter(|field| direct_type(&field.ty)).count();
    let input_descriptor_index = direct_input_count;
    let output_descriptor_index = plan.direct_params.len() - 1;
    let (input_bytes, input_alignment) =
        input_descriptor_layout(&function.inputs, records).expect("eligible input descriptor");
    let output_layout =
        output_descriptor_layout(&function.outputs, records).expect("eligible output descriptor");
    let mut body = format!(
        "wasm_trap_t* {callback}(void* environment, wasmtime_caller_t* caller,\n    wasmtime_val_raw_t* slots, std::size_t slotCount)\n{{\n    auto* state = static_cast<HostState*>(environment);\n    if (state == nullptr || state->native == nullptr || {api_guard} ||\n        state->native->{api_member}->{function_name} == nullptr)\n        return Trap(\"{function_name} generated Core binding is unavailable\");\n    if (slots == nullptr || slotCount != {slot_count})\n        return Trap(\"{function_name} generated Core ABI signature mismatch\");\n\n    std::string budgetError;\n    ImportGuard guard(state, {work}u, budgetError);\n    if (!guard.Ok())\n        return Trap(budgetError);\n\n    std::string memoryError;\n    if (!EnsureMemory(state, caller, memoryError))\n        return Trap(memoryError);\n    const std::uint32_t inputDescriptor = static_cast<std::uint32_t>(slots[{input_index}].i32);\n    const std::uint32_t outputDescriptor = static_cast<std::uint32_t>(slots[{output_index}].i32);\n    std::span<const std::uint8_t> inputWire;\n    std::span<std::uint8_t> outputWire;\n    if (!state->memory.View(inputDescriptor, {input_bytes}u, inputWire) ||\n        !state->memory.MutableView(outputDescriptor, {output_bytes}u, outputWire)) {{\n        slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds);\n        return nullptr;\n    }}\n    WireReader reader(inputWire);\n",
        callback = callback,
        api_member = api_member,
        api_guard = api_guard,
        function_name = function.name,
        slot_count = slot_count,
        work = 1 + plan.direct_params.len(),
        input_index = input_descriptor_index,
        output_index = output_descriptor_index,
        input_bytes = input_bytes,
        output_bytes = output_layout.descriptor_bytes,
    );

    let mut variable_output_index = 0usize;
    for field in &function.outputs {
        if !variable_type(&field.ty) {
            continue;
        }
        let stem = sanitize(&field.name);
        let offset = variable_output_index * 12;
        body.push_str(&format!(
            "    WireReader {stem}Control(std::span<const std::uint8_t>(outputWire.data() + {offset}u, 12));\n    std::uint32_t {stem}Pointer = 0;\n    std::uint32_t {stem}Capacity = 0;\n    std::uint32_t {stem}IgnoredLength = 0;\n    if (!{stem}Control.U32({stem}Pointer) || !{stem}Control.U32({stem}Capacity) ||\n        !{stem}Control.U32({stem}IgnoredLength) || !{stem}Control.Finish(4)) {{\n        slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument);\n        return nullptr;\n    }}\n",
            stem = stem,
            offset = offset,
        ));
        body.push_str(&render_capacity_validation(field, records, &stem));
        variable_output_index += 1;
    }

    body.push_str(&format!("\n    {} query{{}};\n", function.query));
    let mut direct_slot = 0usize;
    for field in &function.inputs {
        if direct_type(&field.ty) {
            body.push_str(&format!(
                "    query.{field} = {expr};\n",
                field = field.name,
                expr = query_expr(&field.ty, direct_slot, &format!("query.{}", field.name)),
            ));
            direct_slot += 1;
        } else if variable_type(&field.ty) {
            body.push_str(&render_input_variable(field, records));
        } else {
            body.push_str(&render_wire_read(
                &field.ty,
                &format!("query.{}", field.name),
                records,
                "reader",
                1,
            ));
        }
    }
    body.push_str(&format!(
        "    if (!reader.Finish({input_alignment}u)) {{\n        slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument);\n        return nullptr;\n    }}\n",
    ));

    body.push_str(&format!(
        "    {} result{{}};\n    state->native->{api_member}->{function_name}(&query, &result);\n    const std::int32_t errorCode = NativeErrorCode(result.error);\n    if (errorCode != 0) {{ slots[0].i32 = errorCode; return nullptr; }}\n    bool outputTooSmall = false;\n",
        function.result,
        api_member = api_member,
        function_name = function.name,
    ));

    variable_output_index = 0;
    for field in &function.outputs {
        if !variable_type(&field.ty) {
            continue;
        }
        let stem = sanitize(&field.name);
        let length_offset = variable_output_index * 12 + 8;
        body.push_str(&render_required_length(field, &stem));
        body.push_str(&format!(
            "    if (!WriteCoreU32(outputWire, {length_offset}u, {stem}Required))\n        return Trap(\"generated Core output descriptor changed unexpectedly\");\n    outputTooSmall = outputTooSmall || {stem}Capacity < {stem}Required;\n",
            length_offset = length_offset,
            stem = stem,
        ));
        variable_output_index += 1;
    }
    body.push_str("    if (outputTooSmall) { slots[0].i32 = static_cast<std::int32_t>(Status::BufferOverflow); return nullptr; }\n");

    for field in &function.outputs {
        if variable_type(&field.ty) {
            body.push_str(&render_output_copy(field, records));
        }
    }

    if output_layout.fixed_bytes != 0 {
        body.push_str(&format!(
            "    std::span<std::uint8_t> fixedWire = outputWire.subspan({fixed_offset}u, {fixed_bytes}u);\n    WireWriter writer(fixedWire);\n",
            fixed_offset = output_layout.fixed_offset,
            fixed_bytes = output_layout.fixed_bytes,
        ));
        for field in function.outputs.iter().filter(|field| !variable_type(&field.ty)) {
            body.push_str(&render_wire_write(
                &field.ty,
                &format!("result.{}", field.name),
                records,
                "writer",
                1,
            ));
        }
        body.push_str(&format!(
            "    if (!writer.Finish({alignment}u)) return Trap(\"generated Core fixed output layout mismatch\");\n",
            alignment = output_layout.fixed_alignment,
        ));
    }
    body.push_str("    slots[0].i32 = 0;\n    return nullptr;\n}\n");
    body
}

fn render_input_variable(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> String {
    let stem = sanitize(&field.name);
    let mut output = format!(
        "    std::uint32_t {stem}InputPointer = 0;\n    std::uint32_t {stem}InputCount = 0;\n    if (!reader.U32({stem}InputPointer) || !reader.U32({stem}InputCount)) {{\n        slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument);\n        return nullptr;\n    }}\n"
    );
    match &field.ty {
        SemanticType::String => output.push_str(&format!(
            "    std::span<const std::uint8_t> {stem}InputBytes;\n    if (!state->memory.View({stem}InputPointer, {stem}InputCount, {stem}InputBytes)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n    std::string {stem}InputStorage(reinterpret_cast<const char*>({stem}InputBytes.data()), {stem}InputBytes.size());\n    query.{field_name} = {stem}InputStorage.c_str();\n",
            field_name = field.name,
        )),
        SemanticType::Bytes => {
            let count = count_field(field).expect("eligible bytes input count");
            output.push_str(&format!(
                "    std::span<const std::uint8_t> {stem}InputBytes;\n    if (!state->memory.View({stem}InputPointer, {stem}InputCount, {stem}InputBytes)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n    std::vector<std::uint8_t> {stem}InputStorage({stem}InputBytes.begin(), {stem}InputBytes.end());\n    query.{field_name} = reinterpret_cast<std::remove_reference_t<decltype(query.{field_name})>>({stem}InputStorage.data());\n    if (!AssignCoreCount({stem}InputCount, query.{count})) {{ slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument); return nullptr; }}\n",
                field_name = field.name,
            ));
        }
        SemanticType::List { element } if matches!(element.as_ref(), SemanticType::String) => {
            let count = count_field(field).expect("eligible string list input count");
            output.push_str(&format!(
                "    const std::uint64_t {stem}InputDescriptorBytes = static_cast<std::uint64_t>({stem}InputCount) * 8u;\n    if ({stem}InputDescriptorBytes > std::numeric_limits<std::size_t>::max()) {{ slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument); return nullptr; }}\n    std::span<const std::uint8_t> {stem}InputWire;\n    if (!state->memory.View({stem}InputPointer, static_cast<std::size_t>({stem}InputDescriptorBytes), {stem}InputWire)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n    WireReader {stem}InputReader({stem}InputWire);\n    std::vector<std::string> {stem}InputStrings;\n    std::vector<const char*> {stem}InputPointers;\n    {stem}InputStrings.reserve({stem}InputCount);\n    for (std::uint32_t coreIndex = 0; coreIndex < {stem}InputCount; ++coreIndex) {{\n        std::uint32_t itemPointer = 0, itemLength = 0;\n        if (!{stem}InputReader.U32(itemPointer) || !{stem}InputReader.U32(itemLength)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument); return nullptr; }}\n        std::span<const std::uint8_t> itemBytes;\n        if (!state->memory.View(itemPointer, itemLength, itemBytes)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n        {stem}InputStrings.emplace_back(reinterpret_cast<const char*>(itemBytes.data()), itemBytes.size());\n    }}\n    {stem}InputPointers.reserve({stem}InputStrings.size());\n    for (const auto& item : {stem}InputStrings) {stem}InputPointers.push_back(item.c_str());\n    query.{field_name} = {stem}InputPointers.data();\n    if (!AssignCoreCount({stem}InputCount, query.{count})) {{ slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument); return nullptr; }}\n",
                field_name = field.name,
            ));
        }
        SemanticType::List { element } => {
            let count = count_field(field).expect("eligible list input count");
            let (element_bytes, element_alignment) = fixed_wire_layout(element, records).expect("eligible list input element");
            let cpp = native_cpp_type(element);
            let item_read = render_wire_read(element, "item", records, &format!("{stem}InputReader"), 2);
            output.push_str(&format!(
                "    const std::uint64_t {stem}InputBytes64 = static_cast<std::uint64_t>({stem}InputCount) * {element_bytes}u;\n    if ({stem}InputBytes64 > std::numeric_limits<std::size_t>::max()) {{ slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument); return nullptr; }}\n    std::span<const std::uint8_t> {stem}InputWire;\n    if (!state->memory.View({stem}InputPointer, static_cast<std::size_t>({stem}InputBytes64), {stem}InputWire)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n    WireReader {stem}InputReader({stem}InputWire);\n    std::vector<{cpp}> {stem}InputStorage;\n    {stem}InputStorage.reserve({stem}InputCount);\n    for (std::uint32_t coreIndex = 0; coreIndex < {stem}InputCount; ++coreIndex) {{\n        {cpp} item{{}};\n{item_read}        {stem}InputStorage.push_back(item);\n    }}\n    if (!{stem}InputReader.Finish({element_alignment}u)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument); return nullptr; }}\n    query.{field_name} = {stem}InputStorage.data();\n    if (!AssignCoreCount({stem}InputCount, query.{count})) {{ slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument); return nullptr; }}\n",
                field_name = field.name,
            ));
        }
        _ => unreachable!(),
    }
    output
}

fn render_capacity_validation(field: &FieldModel, records: &BTreeMap<String, RecordModel>, stem: &str) -> String {
    match &field.ty {
        SemanticType::String | SemanticType::Bytes => format!(
            "    if (!state->memory.Contains({stem}Pointer, {stem}Capacity)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n"
        ),
        SemanticType::List { element } => {
            let (bytes, _) = fixed_wire_layout(element, records).expect("eligible output list element");
            format!(
                "    const std::uint64_t {stem}CapacityBytes = static_cast<std::uint64_t>({stem}Capacity) * {bytes}u;\n    if ({stem}CapacityBytes > std::numeric_limits<std::size_t>::max() || !state->memory.Contains({stem}Pointer, static_cast<std::size_t>({stem}CapacityBytes))) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n"
            )
        }
        _ => String::new(),
    }
}

fn render_required_length(field: &FieldModel, stem: &str) -> String {
    match &field.ty {
        SemanticType::String => format!(
            "    if (result.{field_name} == nullptr) {{\n        const std::uint32_t {stem}Required = 0;\n    }}\n    const std::size_t {stem}RequiredSize = result.{field_name} == nullptr ? 0u : std::char_traits<char>::length(result.{field_name});\n    if ({stem}RequiredSize > std::numeric_limits<std::uint32_t>::max()) {{ slots[0].i32 = static_cast<std::int32_t>(Status::BufferOverflow); return nullptr; }}\n    const std::uint32_t {stem}Required = static_cast<std::uint32_t>({stem}RequiredSize);\n",
            field_name = field.name,
        ),
        SemanticType::Bytes | SemanticType::List { .. } => {
            let count = count_field(field).expect("eligible variable output count");
            format!(
                "    if (static_cast<std::uint64_t>(result.{count}) > std::numeric_limits<std::uint32_t>::max()) {{ slots[0].i32 = static_cast<std::int32_t>(Status::BufferOverflow); return nullptr; }}\n    const std::uint32_t {stem}Required = static_cast<std::uint32_t>(result.{count});\n    if ({stem}Required != 0 && result.{field_name} == nullptr) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OperationFailed); return nullptr; }}\n",
                field_name = field.name,
            )
        }
        _ => unreachable!(),
    }
}

fn render_output_copy(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> String {
    let stem = sanitize(&field.name);
    match &field.ty {
        SemanticType::String | SemanticType::Bytes => format!(
            "    if ({stem}Required != 0 && !state->memory.Write({stem}Pointer, result.{field_name}, {stem}Required)) return Trap(\"generated Core variable output range changed unexpectedly\");\n",
            field_name = field.name,
        ),
        SemanticType::List { element } => {
            let (element_bytes, element_alignment) = fixed_wire_layout(element, records).expect("eligible output list element");
            let item_write = render_wire_write(element, &format!("result.{}[coreIndex]", field.name), records, &format!("{stem}Writer"), 2);
            format!(
                "    if ({stem}Required != 0) {{\n        const std::size_t {stem}Bytes = static_cast<std::size_t>({stem}Required) * {element_bytes}u;\n        std::span<std::uint8_t> {stem}Wire;\n        if (!state->memory.MutableView({stem}Pointer, {stem}Bytes, {stem}Wire)) return Trap(\"generated Core variable output range changed unexpectedly\");\n        WireWriter {stem}Writer({stem}Wire);\n        for (std::uint32_t coreIndex = 0; coreIndex < {stem}Required; ++coreIndex) {{\n{item_write}        }}\n        if (!{stem}Writer.Finish({element_alignment}u)) return Trap(\"generated Core list output layout mismatch\");\n    }}\n"
            )
        }
        _ => unreachable!(),
    }
}

fn native_cast(destination: &str, value: &str) -> String {
    format!("static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>({value})")
}

fn query_expr(ty: &SemanticType, slot: usize, destination: &str) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!("slots[{slot}].i32 != 0"),
            "f32" => format!("slots[{slot}].f32"),
            "f64" => format!("slots[{slot}].f64"),
            "i64" | "u64" | "isize" | "usize" => native_cast(destination, &format!("slots[{slot}].i64")),
            _ => native_cast(destination, &format!("slots[{slot}].i32")),
        },
        SemanticType::Enum { .. } => native_cast(destination, &format!("slots[{slot}].i32")),
        SemanticType::Handle { .. } => native_cast(destination, &format!("slots[{slot}].i64")),
        _ => unreachable!(),
    }
}

fn render_wire_read(ty: &SemanticType, destination: &str, records: &BTreeMap<String, RecordModel>, reader: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!("{pad}if (!{reader}.Bool({destination})) return Trap(\"generated Core wire underflow\");\n"),
            "f32" => format!("{pad}if (!{reader}.F32({destination})) return Trap(\"generated Core wire underflow\");\n"),
            "f64" => format!("{pad}if (!{reader}.F64({destination})) return Trap(\"generated Core wire underflow\");\n"),
            "i64" | "isize" => scalar_read(reader, "I64", "std::int64_t", destination, &pad),
            "u64" | "usize" => scalar_read(reader, "U64", "std::uint64_t", destination, &pad),
            "i8" | "i16" | "i32" => scalar_read(reader, "I32", "std::int32_t", destination, &pad),
            _ => scalar_read(reader, "U32", "std::uint32_t", destination, &pad),
        },
        SemanticType::Enum { .. } => scalar_read(reader, "I32", "std::int32_t", destination, &pad),
        SemanticType::Handle { .. } => scalar_read(reader, "U64", "std::uint64_t", destination, &pad),
        SemanticType::Record { name } => records[name].fields.iter().map(|field| render_wire_read(&field.ty, &format!("{destination}.{}", field.name), records, reader, indent)).collect::<String>(),
        SemanticType::FixedArray { element, length } => {
            let index = format!("coreReadIndex{indent}");
            let nested = render_wire_read(element, &format!("{destination}[{index}]"), records, reader, indent + 1);
            format!("{pad}for (std::size_t {index} = 0; {index} < {length}u; ++{index}) {{\n{nested}{pad}}}\n")
        }
        _ => unreachable!(),
    }
}

fn scalar_read(reader: &str, method: &str, raw: &str, destination: &str, pad: &str) -> String {
    format!("{pad}{{ {raw} coreRaw = 0; if (!{reader}.{method}(coreRaw)) return Trap(\"generated Core wire underflow\"); {destination} = {cast}; }}\n", cast = native_cast(destination, "coreRaw"))
}

fn render_wire_write(ty: &SemanticType, value: &str, records: &BTreeMap<String, RecordModel>, writer: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    match ty {
        SemanticType::Scalar { name } => {
            let method = match name.as_str() { "bool"=>"Bool", "f32"=>"F32", "f64"=>"F64", "i64"|"isize"=>"I64", "u64"|"usize"=>"U64", "i8"|"i16"|"i32"=>"I32", _=>"U32" };
            format!("{pad}if (!{writer}.{method}({value})) return Trap(\"generated Core wire overflow\");\n")
        }
        SemanticType::Enum { .. } => format!("{pad}if (!{writer}.I32(static_cast<std::int32_t>({value}))) return Trap(\"generated Core wire overflow\");\n"),
        SemanticType::Handle { .. } => format!("{pad}if (!{writer}.U64(static_cast<std::uint64_t>({value}))) return Trap(\"generated Core wire overflow\");\n"),
        SemanticType::Record { name } => records[name].fields.iter().map(|field| render_wire_write(&field.ty, &format!("{value}.{}", field.name), records, writer, indent)).collect::<String>(),
        SemanticType::FixedArray { element, length } => {
            let index = format!("coreWriteIndex{indent}");
            let nested = render_wire_write(element, &format!("{value}[{index}]"), records, writer, indent + 1);
            format!("{pad}for (std::size_t {index} = 0; {index} < {length}u; ++{index}) {{\n{nested}{pad}}}\n")
        }
        _ => unreachable!(),
    }
}

fn native_cpp_type(ty: &SemanticType) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i8"=>"std::int8_t".to_owned(), "i16"=>"std::int16_t".to_owned(), "i32"=>"std::int32_t".to_owned(), "i64"=>"std::int64_t".to_owned(),
            "u8"|"char"=>"std::uint8_t".to_owned(), "u16"=>"std::uint16_t".to_owned(), "u32"=>"std::uint32_t".to_owned(), "u64"=>"std::uint64_t".to_owned(),
            "f32"=>"float".to_owned(), "f64"=>"double".to_owned(), _=>unreachable!("unsupported list scalar type"),
        },
        SemanticType::Enum { name } | SemanticType::Record { name } => name.clone(),
        _ => unreachable!("unsupported variable list element C++ type"),
    }
}

fn count_field(field: &FieldModel) -> Option<String> {
    field.metadata.iter().find_map(|metadata| metadata.strip_prefix("count-field:").map(ToString::to_string))
}

fn render_registration(plan: &FunctionPlan, callback: &str) -> String {
    let params = kind_array("params", &plan.direct_params);
    let results = kind_array("results", &plan.direct_results);
    format!("    {{\n{params}{results}        if (!DefineGeneratedVariableIo(linker, \"{module}\", \"{name}\",\n                MakeFuncType(params, {pc}, results, {rc}), {callback}, state, error))\n            return false;\n    }}\n",
        params=params, results=results, module=plan.import_module, name=plan.import_name, pc=plan.direct_params.len(), rc=plan.direct_results.len(), callback=callback)
}

fn kind_array(name: &str, kinds: &[CoreType]) -> String {
    if kinds.is_empty() { return format!("        const wasm_valkind_t* {name} = nullptr;\n"); }
    format!("        const wasm_valkind_t {name}[] = {{{}}};\n", kinds.iter().map(|kind| match kind { CoreType::I32=>"WASM_I32", CoreType::I64=>"WASM_I64", CoreType::F32=>"WASM_F32", CoreType::F64=>"WASM_F64" }).collect::<Vec<_>>().join(", "))
}

fn native_member(module: &str) -> String {
    spring_native_codegen::render_host::core_native_member(module)
        .unwrap_or_else(|| panic!("no NativeInterface member mapped for module {module}"))
}

fn native_guard(module: &str) -> String {
    spring_native_codegen::render_host::core_native_guard(module)
        .unwrap_or_else(|| panic!("no NativeInterface member mapped for module {module}"))
}
fn callback_name(module: &str, function: &str) -> String { format!("CoreVariableIo_{}_{}", module.to_snake_case(), function.to_snake_case()) }
fn sanitize(value: &str) -> String { value.chars().map(|c| if c.is_ascii_alphanumeric(){c}else{'_'}).collect() }
fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records=BTreeMap::new(); for module in &model.modules { for record in &module.records { records.entry(record.name.clone()).or_insert_with(||record.clone()); } } records
}
