//! Generate the semantic, allocation-owning Core-Wasm guest façade.
//!
//! The transport renderers intentionally expose caller-owned buffers and
//! descriptor blobs.  Probe and application code should not have to know which
//! lowering a function uses, so this fragment provides the stable semantic
//! namespace used by Core guests.  Functions not yet eligible for the owned
//! lowering still have a typed entry point; keeping that surface generated
//! makes the missing transport explicit at the call site and prevents a
//! second hand-maintained API inventory.

use heck::{ToKebabCase, ToSnakeCase};
use std::collections::BTreeMap;

use crate::model::{ApiModel, EnumModel, Environment, FunctionModel, RecordModel, SemanticType};
use crate::render_core_wasm::{self, FunctionPlan};

pub fn render(model: &ApiModel) -> String {
    let mut output = render_owned_prelude();

    for (_, module_source) in render_owned_shards(model) {
        output.push_str(&module_source);
    }
    output.push_str(&render_owned_footer(model));
    output
}

pub fn render_owned_prelude() -> String {
    let mut output = String::from(
        "// @generated by spring-api-codegen; do not edit.\n\n\
         #[cfg(feature = \"alloc\")]\n\
         pub mod owned {\n\
             extern crate alloc;\n\
             use alloc::{string::String, vec::Vec};\n\
             use crate::Result;\n\n",
    );
    output.push_str(
        r#"    #[inline]
    fn decode_core_string(bytes: Vec<u8>) -> String {
        match String::from_utf8(bytes) {
            Ok(value) => value,
            Err(error) => error
                .into_bytes()
                .into_iter()
                .map(char::from)
                .collect(),
        }
    }

"#,
    );
    output
}

pub fn render_owned_shards(model: &ApiModel) -> Vec<(String, String)> {
    let records = model
        .modules
        .iter()
        .flat_map(|module| {
            module
                .records
                .iter()
                .map(|record| (record.name.clone(), record.clone()))
        })
        .collect::<BTreeMap<_, _>>();
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();
    model
        .modules
        .iter()
        .map(|module| {
            let mut source = String::new();
            render_module(&mut source, module, &records, &plans);
            (rust_ident(&module.name), source)
        })
        .collect()
}

pub fn render_owned_footer(model: &ApiModel) -> String {
    format!(
        "    #[doc(hidden)]\n    pub const __GENERATED_OWNED_CORE_MODULES: usize = {};\n}}\n",
        model.modules.len()
    )
}

/// Render environment SDK namespaces as selective re-exports of the shared
/// owned implementation. Keeping the bodies in one module is important: the
/// five environment projections must not multiply the guest code size.
pub fn render_environment_modules(model: &ApiModel) -> String {
    const ENVIRONMENTS: [(&str, &str, u32, Environment); 5] = [
        (
            "rules_synced",
            "rules-synced",
            1u32,
            Environment::RulesSynced,
        ),
        (
            "rules_unsynced",
            "rules-unsynced",
            2u32,
            Environment::RulesUnsynced,
        ),
        ("gaia_synced", "gaia-synced", 4u32, Environment::GaiaSynced),
        (
            "gaia_unsynced",
            "gaia-unsynced",
            8u32,
            Environment::GaiaUnsynced,
        ),
        ("ui", "ui", 16u32, Environment::Ui),
    ];
    let all_plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();
    let mut output = String::from("// @generated by spring-api-codegen; do not edit.\n\n");
    for (module_name, environment_name, environment_mask, _environment) in ENVIRONMENTS {
        output.push_str(&format!(
            "#[cfg(feature = \"alloc\")]\npub mod {module_name} {{\n    pub const ENVIRONMENT_NAME: &str = \"{environment_name}\";\n    pub const ENVIRONMENT_MASK: u32 = {environment_mask};\n    pub use crate::export_environment_mask;\n\n"
        ));
        for module in &model.modules {
            let module_ident = rust_ident(&module.name);
            output.push_str(&format!("    pub mod {module_ident} {{\n"));
            let mut exports = Vec::new();
            exports.extend(
                module
                    .enums
                    .iter()
                    .map(|enum_model| enum_model.name.clone()),
            );
            exports.extend(module.records.iter().map(|record| record.name.clone()));
            exports.extend(
                module
                    .functions
                    .iter()
                    .filter(|function| function.outputs.len() > 1)
                    .map(|function| format!("{}Value", function.name)),
            );
            exports.sort();
            exports.dedup();
            if !exports.is_empty() {
                output.push_str(&format!(
                    "        pub use super::super::owned::{module_ident}::{{{}}};\n",
                    exports.join(", ")
                ));
            }
            for function in &module.functions {
                if all_plans
                    .get(&(module.name.clone(), function.name.clone()))
                    .is_some_and(|plan| plan.environment_mask & environment_mask != 0)
                {
                    output.push_str(&format!(
                        "        pub use super::super::owned::{module_ident}::{};\n",
                        rust_ident(&function.name)
                    ));
                }
            }
            output.push_str("    }\n\n");
        }
        output.push_str("}\n\n");
    }
    output
}

/// Validate the generated owned/environment projection itself. This is kept
/// beside the renderer so `--strict` checks the artifact that will actually
/// be written, rather than only checking the transport planner.
pub fn coverage_errors(model: &ApiModel, owned: &str, environments: &str) -> Vec<String> {
    const ENVIRONMENTS: [(&str, u32); 5] = [
        ("rules_synced", 1u32),
        ("rules_unsynced", 2u32),
        ("gaia_synced", 4u32),
        ("gaia_unsynced", 8u32),
        ("ui", 16u32),
    ];
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();
    let mut errors = Vec::new();
    for module in &model.modules {
        let module_ident = rust_ident(&module.name);
        for function in &module.functions {
            let name = rust_ident(&function.name);
            let safe_marker = format!("        pub fn {name}(");
            let raw_marker = format!("        pub unsafe fn {name}(");
            if !owned_module_contains(owned, &module_ident, &safe_marker)
                && !owned_module_contains(owned, &module_ident, &raw_marker)
            {
                errors.push(format!(
                    "owned surface omits {}::{}",
                    module.name, function.name
                ));
            }
            let Some(plan) = plans.get(&(module.name.clone(), function.name.clone())) else {
                errors.push(format!(
                    "{}::{} has no Core environment plan",
                    module.name, function.name
                ));
                continue;
            };
            for (environment, bit) in ENVIRONMENTS {
                if plan.environment_mask & bit == 0 {
                    continue;
                }
                let marker =
                    format!("        pub use super::super::owned::{module_ident}::{name};");
                if !environment_module_contains(environments, environment, &marker) {
                    errors.push(format!(
                        "{}::{} missing from {environment} environment SDK",
                        module.name, function.name
                    ));
                }
            }
        }
    }
    errors
}

fn owned_module_contains(source: &str, module: &str, marker: &str) -> bool {
    let start_marker = format!("    pub mod {module} {{");
    let Some(start) = source.find(&start_marker) else {
        return false;
    };
    let body = &source[start..];
    let end = body[1..]
        .find("\n    pub mod ")
        .map(|offset| offset + 1)
        .unwrap_or(body.len());
    body[..end].contains(marker)
}

fn environment_module_contains(source: &str, environment: &str, marker: &str) -> bool {
    let start_marker = format!("pub mod {environment} {{");
    let Some(start) = source.find(&start_marker) else {
        return false;
    };
    let body = &source[start..];
    let end = body[1..]
        .find("\npub mod ")
        .map(|offset| offset + 1)
        .unwrap_or(body.len());
    body[..end].contains(marker)
}

fn render_module(
    output: &mut String,
    module: &crate::model::ApiModule,
    all_records: &BTreeMap<String, RecordModel>,
    plans: &BTreeMap<(String, String), FunctionPlan>,
) {
    let module_ident = rust_ident(&module.name);
    output.push_str(&format!("    pub mod {module_ident} {{\n"));
    output.push_str("        use super::{Result, String, Vec};\n\n");

    let records = module
        .records
        .iter()
        .map(|record| (record.name.clone(), record))
        .collect::<BTreeMap<_, _>>();
    let enums = module
        .enums
        .iter()
        .map(|enum_model| (enum_model.name.clone(), enum_model))
        .collect::<BTreeMap<_, _>>();

    for enum_model in enums.values() {
        render_enum(output, enum_model);
    }
    for record in records.values() {
        render_record(output, record, &records, &enums);
    }

    for function in &module.functions {
        if variable_output_forward_supported(function, &module.name, plans, all_records) {
            render_variable_list_raw(output, function, &module.name);
        }
    }

    for function in &module.functions {
        if function.outputs.len() > 1 {
            render_output_record(output, function, &records, &enums);
        }
    }
    for function in &module.functions {
        let plan = plans
            .get(&(module.name.clone(), function.name.clone()))
            .expect("Core plan contains every API function");
        if module.name == "math_extra" && function.name == "Normalize" {
            render_normalize_forward(output);
            continue;
        }
        if render_special_forward(output, module, function) {
            continue;
        }
        if render_variable_output_forward(output, function, &module.name, plans, all_records) {
            continue;
        }
        if render_borrowed_forward(
            output,
            function,
            &module_ident,
            &records,
            &enums,
            all_records,
            plan,
        ) {
            continue;
        }
        if crate::render_core_wasm_guest::fixed_executable(
            plan,
            &function.inputs,
            &function.outputs,
            all_records,
        ) {
            render_fixed_forward(output, function, &records, &enums, &module_ident);
        } else {
            render_function(output, function, &records, &enums, plan);
        }
    }
    output.push_str("    }\n\n");
}

fn variable_list_forward_supported(
    function: &FunctionModel,
    module: &str,
    plans: &BTreeMap<(String, String), FunctionPlan>,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    let Some(plan) = plans.get(&(module.to_owned(), function.name.clone())) else {
        return false;
    };
    if !crate::render_core_wasm_variable_output_host::eligible(
        plan,
        &function.inputs,
        &function.outputs,
        records,
    ) || function.outputs.len() != 1
    {
        return false;
    }
    let SemanticType::List { element } = &function.outputs[0].ty else {
        return false;
    };
    matches!(element.as_ref(), SemanticType::Scalar { name } if !matches!(name.as_str(), "bool" | "isize" | "usize"))
        && function.inputs.iter().all(|field| {
            matches!(
                field.ty,
                SemanticType::Scalar { .. }
                    | SemanticType::Enum { .. }
                    | SemanticType::Handle { .. }
            )
        })
}

fn variable_output_forward_supported(
    function: &FunctionModel,
    module: &str,
    plans: &BTreeMap<(String, String), FunctionPlan>,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    if variable_list_forward_supported(function, module, plans, records) {
        return true;
    }
    let Some(plan) = plans.get(&(module.to_owned(), function.name.clone())) else {
        return false;
    };
    crate::render_core_wasm_variable_output_host::eligible(
        plan,
        &function.inputs,
        &function.outputs,
        records,
    ) && function.outputs.len() == 1
        && matches!(function.outputs[0].ty, SemanticType::String)
        && function.inputs.iter().all(|field| {
            matches!(
                field.ty,
                SemanticType::Scalar { .. }
                    | SemanticType::Enum { .. }
                    | SemanticType::Handle { .. }
            )
        })
}

fn render_variable_list_raw(output: &mut String, function: &FunctionModel, module: &str) {
    let raw_module = format!("__core_variable_output_{}", rust_ident(&function.name));
    let params = function
        .inputs
        .iter()
        .map(|field| {
            format!(
                "p{}: {}",
                rust_ident(&field.name),
                rust_core_abi_type(&field.ty),
            )
        })
        .chain(std::iter::once("output: i32".to_owned()))
        .collect::<Vec<_>>()
        .join(", ");
    output.push_str(&format!(
        "        #[cfg(target_arch = \"wasm32\")]\n        mod {raw_module} {{\n            #[link(wasm_import_module = \"spring:{module}\")]\n            extern \"C\" {{\n                #[link_name = \"{}\"]\n                pub fn call({params}) -> i32;\n            }}\n        }}\n\n",
        function.name.to_kebab_case(),
        raw_module = raw_module,
        module = module.to_kebab_case(),
        params = params,
    ));
}

fn render_variable_list_forward(
    output: &mut String,
    function: &FunctionModel,
    _module: &str,
    plans: &BTreeMap<(String, String), FunctionPlan>,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    if !variable_list_forward_supported(function, _module, plans, records) {
        return false;
    }
    let params = function
        .inputs
        .iter()
        .map(|field| {
            format!(
                "{}: {}",
                rust_ident(&field.name),
                rust_param_type(&field.ty, &BTreeMap::new(), &BTreeMap::new()),
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let args = function.inputs.iter().map(core_abi_arg).collect::<Vec<_>>();
    let raw_module = format!("__core_variable_output_{}", rust_ident(&function.name));
    let call_args = args
        .iter()
        .cloned()
        .chain(std::iter::once(
            "descriptor.as_mut_ptr() as usize as u32 as i32".to_owned(),
        ))
        .collect::<Vec<_>>()
        .join(", ");
    let name = rust_ident(&function.name);
    let element_type = match &function.outputs[0].ty {
        SemanticType::List { element } => rust_type(element, &BTreeMap::new(), &BTreeMap::new()),
        _ => unreachable!(),
    };
    let return_type = rust_type(&function.outputs[0].ty, &BTreeMap::new(), &BTreeMap::new());
    output.push_str(&format!(
        r#"        #[inline]
        pub fn {name}({params}) -> Result<{return_type}> {{
            #[cfg(target_arch = "wasm32")]
            {{
                let mut descriptor = [0u32; 3];
                let mut output = Vec::<{element_type}>::new();
                loop {{
                    let status = unsafe {{ {raw_module}::call({call_args}) }};
                    let required = descriptor[2] as usize;
                    if status == 0 {{
                        output.truncate(required);
                        return Ok(output);
                    }}
                    if status != crate::ErrorCode::BufferOverflow as i32 {{
                        return Err(crate::ApiError::new(status));
                    }}
                    output.resize(required, Default::default());
                    descriptor[0] = output.as_mut_ptr() as usize as u32;
                    descriptor[1] = output.len() as u32;
                    descriptor[2] = 0;
                }}
            }}
            #[cfg(not(target_arch = "wasm32"))]
            {{
                let _ = ({args});
                Err(unreachable!())
            }}
        }}

"#,
        name = name,
        params = params,
        return_type = return_type,
        element_type = element_type,
        raw_module = raw_module,
        call_args = call_args,
        args = args.join(", "),
    ));
    true
}

fn render_variable_output_forward(
    output: &mut String,
    function: &FunctionModel,
    module: &str,
    plans: &BTreeMap<(String, String), FunctionPlan>,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    if variable_list_forward_supported(function, module, plans, records) {
        return render_variable_list_forward(output, function, module, plans, records);
    }
    if !variable_output_forward_supported(function, module, plans, records) {
        return false;
    }
    let params = function
        .inputs
        .iter()
        .map(|field| {
            format!(
                "{}: {}",
                rust_ident(&field.name),
                rust_param_type(&field.ty, &BTreeMap::new(), &BTreeMap::new()),
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let args = function.inputs.iter().map(core_abi_arg).collect::<Vec<_>>();
    let raw_module = format!("__core_variable_output_{}", rust_ident(&function.name));
    let call_args = args
        .iter()
        .cloned()
        .chain(std::iter::once(
            "descriptor.as_mut_ptr() as usize as u32 as i32".to_owned(),
        ))
        .collect::<Vec<_>>()
        .join(", ");
    output.push_str(&format!(
        r#"        #[inline]
        pub fn {name}({params}) -> Result<String> {{
            #[cfg(target_arch = "wasm32")]
            {{
                let mut descriptor = [0u32; 3];
                let mut output = Vec::<u8>::new();
                loop {{
                    let status = unsafe {{ {raw_module}::call({call_args}) }};
                    let required = descriptor[2] as usize;
                    if status == 0 {{
                        output.truncate(required);
                        return Ok(super::decode_core_string(output));
                    }}
                    if status != crate::ErrorCode::BufferOverflow as i32 {{
                        return Err(crate::ApiError::new(status));
                    }}
                    output.resize(required, 0);
                    descriptor[0] = output.as_mut_ptr() as usize as u32;
                    descriptor[1] = output.len() as u32;
                    descriptor[2] = 0;
                }}
            }}
            #[cfg(not(target_arch = "wasm32"))]
            {{
                let _ = ({args});
                Err(unreachable!())
            }}
        }}

"#,
        name = rust_ident(&function.name),
        params = params,
        raw_module = raw_module,
        call_args = call_args,
        args = args.join(", "),
    ));
    true
}

fn rust_core_abi_type(ty: &SemanticType) -> &'static str {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "f32" => "f32",
            "f64" => "f64",
            "i64" | "u64" | "isize" | "usize" => "i64",
            _ => "i32",
        },
        SemanticType::Enum { .. } => "i32",
        SemanticType::Handle { .. } => "i64",
        _ => unreachable!("variable-output forward requires a direct input"),
    }
}

fn core_abi_arg(field: &crate::model::FieldModel) -> String {
    let name = rust_ident(&field.name);
    match &field.ty {
        SemanticType::Scalar { name: ty } if ty == "bool" => {
            format!("u32::from({name}) as i32")
        }
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. } => {
            format!("{name} as {}", rust_core_abi_type(&field.ty))
        }
        _ => unreachable!("variable-output forward requires a direct input"),
    }
}

fn render_borrowed_forward(
    output: &mut String,
    function: &FunctionModel,
    module_ident: &str,
    records: &BTreeMap<String, &RecordModel>,
    enums: &BTreeMap<String, &EnumModel>,
    all_records: &BTreeMap<String, RecordModel>,
    plan: &FunctionPlan,
) -> bool {
    if function.outputs.len() != 1
        || !matches!(
            plan.result_strategy,
            crate::render_core_wasm::ResultStrategy::Packed32
        )
        || !function.inputs.iter().all(borrowed_forward_input_supported)
        || !crate::render_core_wasm_borrowed_host::eligible(
            plan,
            &function.inputs,
            &function.outputs,
            all_records,
        )
    {
        return false;
    }

    let params = function
        .inputs
        .iter()
        .map(|field| {
            format!(
                "{}: {}",
                rust_ident(&field.name),
                rust_param_type(&field.ty, records, enums),
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let mut setup = String::new();
    let mut args = Vec::new();
    for field in &function.inputs {
        let name = rust_ident(&field.name);
        match &field.ty {
            SemanticType::String => {
                setup.push_str(&format!(
                    "            let mut {name}_bytes = {name}.as_bytes().to_vec();\n"
                ));
                setup.push_str(&format!(
                    "            if {name}_bytes.contains(&0) {{ return Err(crate::ApiError::new(crate::ErrorCode::InvalidArgument as i32)); }}\n"
                ));
                setup.push_str(&format!("            {name}_bytes.push(0);\n"));
                setup.push_str(&format!(
                    "            let {name}_cstr = core::ffi::CStr::from_bytes_with_nul(&{name}_bytes).map_err(|_| crate::ApiError::new(crate::ErrorCode::InvalidArgument as i32))?;\n"
                ));
                args.push(format!("&{name}_cstr"));
            }
            SemanticType::Bytes | SemanticType::List { .. } => {
                args.push(format!("{name}.as_slice()"));
            }
            _ => args.push(name),
        }
    }
    let core_path = format!(
        "crate::generated::borrowed::{module_ident}::{}",
        rust_ident(&function.name)
    );
    let return_type = rust_type(&function.outputs[0].ty, records, enums);
    output.push_str(&format!(
        "        #[inline]\n        pub fn {}({params}) -> Result<{return_type}> {{\n{setup}            {core_path}({})\n        }}\n\n",
        rust_ident(&function.name),
        args.join(", "),
    ));
    true
}

fn borrowed_forward_input_supported(field: &crate::model::FieldModel) -> bool {
    match &field.ty {
        SemanticType::Scalar { .. }
        | SemanticType::Enum { .. }
        | SemanticType::Handle { .. }
        | SemanticType::String
        | SemanticType::Bytes => true,
        SemanticType::List { element } => matches!(
            element.as_ref(),
            SemanticType::Scalar { .. } | SemanticType::Enum { .. }
        ),
        _ => false,
    }
}

fn render_special_forward(
    output: &mut String,
    module: &crate::model::ApiModule,
    function: &FunctionModel,
) -> bool {
    if module.name == "units_info" && rust_ident(&function.name) == "get_unit_last_attacked_piece" {
        output.push_str(
            r#"        #[inline]
        pub fn get_unit_last_attacked_piece(unit_id: i32) -> Result<LastHitPiece> {
            #[cfg(target_arch = "wasm32")]
            {
                let mut output = Vec::<u8>::new();
                loop {
                    match crate::generated::dynamic_output::units_info::get_unit_last_attacked_piece(unit_id, &mut output) {
                        Ok(required) => {
                            output.truncate(required);
                            let mut cursor = 0usize;
                            let name_length = crate::generated::__core_wire::u32(&output, &mut cursor)
                                .ok_or(crate::ApiError::new(crate::ErrorCode::Internal as i32))? as usize;
                            let name_end = cursor.checked_add(name_length)
                                .ok_or(crate::ApiError::new(crate::ErrorCode::Internal as i32))?;
                            let name = super::decode_core_string(output.get(cursor..name_end)
                                .ok_or(crate::ApiError::new(crate::ErrorCode::Internal as i32))?
                                .to_vec());
                            cursor = name_end;
                            let piece_num = crate::generated::__core_wire::i32(&output, &mut cursor)
                                .ok_or(crate::ApiError::new(crate::ErrorCode::Internal as i32))?;
                            let frame = crate::generated::__core_wire::i32(&output, &mut cursor)
                                .ok_or(crate::ApiError::new(crate::ErrorCode::Internal as i32))?;
                            let was_hit = crate::generated::__core_wire::boolean(&output, &mut cursor)
                                .ok_or(crate::ApiError::new(crate::ErrorCode::Internal as i32))?;
                            if !crate::generated::__core_wire::finish(&output, &mut cursor, 8) {
                                return Err(crate::ApiError::new(crate::ErrorCode::Internal as i32));
                            }
                            return Ok(LastHitPiece { name, piece_num, frame, was_hit });
                        }
                        Err(error) if error.error.code == crate::ErrorCode::BufferOverflow as i32 => {
                            output.resize(error.required, 0);
                        }
                        Err(error) => return Err(error.error),
                    }
                }
            }
            #[cfg(not(target_arch = "wasm32"))]
            {
                let _ = unit_id;
                Err(unreachable!())
            }
        }

"#,
        );
        return true;
    }
    if module.name == "units_query"
        && matches!(rust_ident(&function.name).as_str(), "get_all_units")
    {
        let params = "unused: u8";
        let args = "let _ = unused; crate::get_all_units()";
        output.push_str(&format!(
            "        #[inline]\n        pub fn {}({params}) -> Result<Vec<i32>> {{\n            {args}\n        }}\n\n",
            rust_ident(&function.name),
        ));
        return true;
    }
    if module.name == "units_query" && rust_ident(&function.name) == "get_team_units" {
        output.push_str(
            "        #[inline]\n        pub fn get_team_units(team_id: i32) -> Result<Vec<i32>> {\n            crate::get_team_units(team_id)\n        }\n\n",
        );
        return true;
    }
    if module.name == "units_query" && rust_ident(&function.name) == "get_unit_nearest_enemy" {
        output.push_str(
            "        #[inline]\n        pub fn get_unit_nearest_enemy(unit_id: i32, range: f32, options: GetUnitNearestEnemyOptions) -> Result<i32> {\n            crate::get_unit_nearest_enemy(unit_id, range, options.use_los, options.sphere_dist_test, options.check_sight_dist)\n        }\n\n",
        );
        return true;
    }
    if module.name == "units_query" && rust_ident(&function.name) == "get_unit_separation" {
        output.push_str(
            "        #[inline]\n        pub fn get_unit_separation(unit_id1: i32, unit_id2: i32, options: GetUnitSeparationOptions) -> Result<f32> {\n            crate::get_unit_separation(unit_id1, unit_id2, options.positional, options.check_map)\n        }\n\n",
        );
        return true;
    }
    if module.name == "units_info" && rust_ident(&function.name) == "get_unit_nano_pieces" {
        output.push_str(
            "        #[inline]\n        pub fn get_unit_nano_pieces(unit_id: i32) -> Result<Vec<i32>> {\n            #[cfg(target_arch = \"wasm32\")]\n            {\n                let mut output = Vec::<i32>::new();\n                loop {\n                    let packed = unsafe { __core_units_info_nano_pieces::call(unit_id, output.as_mut_ptr() as usize as u32 as i32, output.len() as i32) } as u64;\n                    let status = (packed >> 32) as u32 as i32;\n                    let required = packed as u32 as usize;\n                    if status == 0 { output.truncate(required); return Ok(output); }\n                    if status != crate::ErrorCode::BufferOverflow as i32 { return Err(crate::ApiError::new(status)); }\n                    output.resize(required, 0);\n                }\n            }\n            #[cfg(not(target_arch = \"wasm32\"))]\n            { let _ = unit_id; Err(unreachable!()) }\n        }\n\n        #[cfg(target_arch = \"wasm32\")]\n        mod __core_units_info_nano_pieces {\n            #[link(wasm_import_module = \"spring:units-info\")]\n            extern \"C\" {\n                #[link_name = \"get-unit-nano-pieces\"]\n                pub fn call(unit_id: i32, output: i32, capacity: i32) -> i64;\n            }\n        }\n\n",
        );
        return true;
    }
    if module.name == "units_info" && rust_ident(&function.name) == "get_unit_is_transporting" {
        output.push_str(
            "        #[inline]\n        pub fn get_unit_is_transporting(unit_id: i32) -> Result<GetUnitIsTransportingValue> {\n            #[cfg(target_arch = \"wasm32\")]\n            {\n                let mut output = Vec::<i32>::new();\n                let mut state = [0u8; 4];\n                loop {\n                    let packed = unsafe { __core_units_info_is_transporting::call(unit_id, output.as_mut_ptr() as usize as u32 as i32, output.len() as i32, state.as_mut_ptr() as usize as u32 as i32) } as u64;\n                    let status = (packed >> 32) as u32 as i32;\n                    let required = packed as u32 as usize;\n                    if status == 0 {\n                        output.truncate(required);\n                        return Ok(GetUnitIsTransportingValue { unit_i_ds: output, is_transporting: u32::from_le_bytes(state) != 0 });\n                    }\n                    if status != crate::ErrorCode::BufferOverflow as i32 { return Err(crate::ApiError::new(status)); }\n                    output.resize(required, 0);\n                }\n            }\n            #[cfg(not(target_arch = \"wasm32\"))]\n            { let _ = unit_id; Err(unreachable!()) }\n        }\n\n        #[cfg(target_arch = \"wasm32\")]\n        mod __core_units_info_is_transporting {\n            #[link(wasm_import_module = \"spring:units-info\")]\n            extern \"C\" {\n                #[link_name = \"get-unit-is-transporting\"]\n                pub fn call(unit_id: i32, output: i32, capacity: i32, state: i32) -> i64;\n            }\n        }\n\n",
        );
        return true;
    }
    if module.name == "projectiles" && rust_ident(&function.name) == "get_all_projectiles" {
        output.push_str(
            "        #[inline]\n        pub fn get_all_projectiles(options: GetAllProjectilesOptions) -> Result<Vec<i32>> {\n            #[cfg(target_arch = \"wasm32\")]\n            {\n                let mut input = [0u8; 8];\n                input[0..4].copy_from_slice(&u32::from(options.exclude_weapon_projectiles).to_le_bytes());\n                input[4..8].copy_from_slice(&u32::from(options.exclude_piece_projectiles).to_le_bytes());\n                let mut descriptor = [0u32; 3];\n                let mut output = Vec::<i32>::new();\n                loop {\n                    let status = unsafe { crate::generated::projectiles::raw::core_get_all_projectiles(input.as_ptr() as usize as u32 as i32, descriptor.as_mut_ptr() as usize as u32 as i32) };\n                    let required = descriptor[2] as usize;\n                    if status == 0 {\n                        output.truncate(required);\n                        return Ok(output);\n                    }\n                    if status != crate::ErrorCode::BufferOverflow as i32 {\n                        return Err(crate::ApiError::new(status));\n                    }\n                    output.resize(required, 0);\n                    descriptor[0] = output.as_mut_ptr() as usize as u32;\n                    descriptor[1] = output.len() as u32;\n                    descriptor[2] = 0;\n                }\n            }\n            #[cfg(not(target_arch = \"wasm32\"))]\n            {\n                let _ = options;\n                Err(unreachable!())\n            }\n        }\n\n",
        );
        return true;
    }
    if module.name == "terrain" {
        match rust_ident(&function.name).as_str() {
            "get_water_plane_level" => output.push_str(
                "        #[inline]\n        pub fn get_water_plane_level(_unused: u8) -> Result<f32> {\n            #[cfg(target_arch = \"wasm32\")]\n            {\n                let packed = unsafe { __core_terrain_water_plane_level::call() } as u64;\n                let status = (packed >> 32) as u32 as i32;\n                if status != 0 { return Err(crate::ApiError::new(status)); }\n                return Ok(f32::from_bits(packed as u32));\n            }\n            #[cfg(not(target_arch = \"wasm32\"))]\n            { Err(unreachable!()) }\n        }\n\n        #[cfg(target_arch = \"wasm32\")]\n        mod __core_terrain_water_plane_level {\n            #[link(wasm_import_module = \"spring:terrain\")]\n            extern \"C\" {\n                #[link_name = \"get-water-plane-level\"]\n                pub fn call() -> i64;\n            }\n        }\n\n",
            ),
            "is_pos_in_map" => output.push_str(
                "        #[inline]\n        pub fn is_pos_in_map(x: f32, z: f32) -> Result<IsPosInMapValue> {\n            #[cfg(target_arch = \"wasm32\")]\n            {\n                let packed = unsafe { __core_terrain_is_pos_in_map::call(x, z) } as u64;\n                let status = (packed >> 32) as u32 as i32;\n                if status != 0 { return Err(crate::ApiError::new(status)); }\n                let flags = packed as u32;\n                return Ok(IsPosInMapValue { in_map: flags & 1 != 0, in_play_area: flags & 2 != 0 });\n            }\n            #[cfg(not(target_arch = \"wasm32\"))]\n            { let _ = (x, z); Err(unreachable!()) }\n        }\n\n        #[cfg(target_arch = \"wasm32\")]\n        mod __core_terrain_is_pos_in_map {\n            #[link(wasm_import_module = \"spring:terrain\")]\n            extern \"C\" {\n                #[link_name = \"is-pos-in-map\"]\n                pub fn call(x: f32, z: f32) -> i64;\n            }\n        }\n\n",
            ),
            "get_ground_extremes" => output.push_str(
                "        #[inline]\n        pub fn get_ground_extremes(_unused: u8) -> Result<GetGroundExtremesValue> {\n            #[cfg(target_arch = \"wasm32\")]\n            {\n                let mut output = [0u8; 16];\n                let status = unsafe { __core_terrain_ground_extremes::call(output.as_mut_ptr() as usize as u32 as i32) };\n                if status != 0 { return Err(crate::ApiError::new(status)); }\n                return Ok(GetGroundExtremesValue {\n                    init_min_height: f32::from_le_bytes(output[0..4].try_into().unwrap()),\n                    init_max_height: f32::from_le_bytes(output[4..8].try_into().unwrap()),\n                    curr_min_height: f32::from_le_bytes(output[8..12].try_into().unwrap()),\n                    curr_max_height: f32::from_le_bytes(output[12..16].try_into().unwrap()),\n                });\n            }\n            #[cfg(not(target_arch = \"wasm32\"))]\n            { Err(unreachable!()) }\n        }\n\n        #[cfg(target_arch = \"wasm32\")]\n        mod __core_terrain_ground_extremes {\n            #[link(wasm_import_module = \"spring:terrain\")]\n            extern \"C\" {\n                #[link_name = \"get-ground-extremes\"]\n                pub fn call(output: i32) -> i32;\n            }\n        }\n\n",
            ),
            "get_height_map_size" => output.push_str(
                "        #[inline]\n        pub fn get_height_map_size(_unused: u8) -> Result<GetHeightMapSizeValue> {\n            #[cfg(target_arch = \"wasm32\")]\n            {\n                let mut output = [0u8; 8];\n                let status = unsafe { __core_terrain_height_map_size::call(output.as_mut_ptr() as usize as u32 as i32) };\n                if status != 0 { return Err(crate::ApiError::new(status)); }\n                return Ok(GetHeightMapSizeValue {\n                    points_x: i32::from_le_bytes(output[0..4].try_into().unwrap()),\n                    points_z: i32::from_le_bytes(output[4..8].try_into().unwrap()),\n                });\n            }\n            #[cfg(not(target_arch = \"wasm32\"))]\n            { Err(unreachable!()) }\n        }\n\n        #[cfg(target_arch = \"wasm32\")]\n        mod __core_terrain_height_map_size {\n            #[link(wasm_import_module = \"spring:terrain\")]\n            extern \"C\" {\n                #[link_name = \"get-height-map-size\"]\n                pub fn call(output: i32) -> i32;\n            }\n        }\n\n",
            ),
            _ => return false,
        }
        return true;
    }
    // These imports are deliberately owned by the reviewed handwritten SDK;
    // the generated Core registry excludes their generic transports.  Keep
    // the semantic façade routed through that same implementation.
    if module.name != "messages"
        || !matches!(
            rust_ident(&function.name).as_str(),
            "echo"
                | "log"
                | "send_ally_chat"
                | "send_commands"
                | "send_lua_gaia_msg"
                | "send_lua_menu_msg"
                | "send_lua_rules_msg"
                | "send_lua_ui_msg"
                | "send_message"
                | "send_message_to_ally_team"
                | "send_message_to_player"
                | "send_message_to_spectators"
                | "send_private_chat"
                | "send_public_chat"
                | "send_skirmish_ai_message"
                | "send_spectator_chat"
                | "send_to_unsynced"
        )
    {
        return false;
    }
    let params = function
        .inputs
        .iter()
        .map(|field| {
            format!(
                "{}: {}",
                rust_ident(&field.name),
                rust_param_type(&field.ty, &BTreeMap::new(), &BTreeMap::new(),)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let args = function
        .inputs
        .iter()
        .map(|field| rust_ident(&field.name))
        .collect::<Vec<_>>()
        .join(", ");
    let return_type = match function.outputs.as_slice() {
        [] => "()".to_owned(),
        [field] => rust_type_simple(&field.ty),
        _ => return false,
    };
    output.push_str(&format!(
        "        #[inline]\n        pub fn {}({params}) -> Result<{return_type}> {{\n            crate::messages::{}({args})\n        }}\n\n",
        rust_ident(&function.name),
        rust_ident(&function.name),
    ));
    true
}

fn rust_type_simple(ty: &SemanticType) -> String {
    match ty {
        SemanticType::Scalar { name } if name == "bool" => "bool".to_owned(),
        SemanticType::Scalar { name } => name.to_owned(),
        SemanticType::String => "String".to_owned(),
        _ => "()".to_owned(),
    }
}

fn render_enum(output: &mut String, enum_model: &EnumModel) {
    output.push_str("        #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    output.push_str(&format!("        pub enum {} {{\n", enum_model.name));
    for variant in enum_model.variants.keys() {
        output.push_str(&format!(
            "            {},\n",
            enum_variant_ident(&enum_model.name, variant)
        ));
    }
    output.push_str("        }\n\n");
}

fn render_record(
    output: &mut String,
    record: &RecordModel,
    records: &BTreeMap<String, &RecordModel>,
    enums: &BTreeMap<String, &EnumModel>,
) {
    output.push_str("        #[derive(Debug, Clone, PartialEq)]\n");
    output.push_str(&format!("        pub struct {} {{\n", record.name));
    for field in &record.fields {
        output.push_str(&format!(
            "            pub {}: {},\n",
            rust_ident(&field.name),
            rust_type(&field.ty, records, enums),
        ));
    }
    output.push_str("        }\n\n");
}

fn render_output_record(
    output: &mut String,
    function: &FunctionModel,
    records: &BTreeMap<String, &RecordModel>,
    enums: &BTreeMap<String, &EnumModel>,
) {
    output.push_str("        #[derive(Debug, Clone, PartialEq)]\n");
    output.push_str(&format!("        pub struct {}Value {{\n", function.name));
    for field in &function.outputs {
        output.push_str(&format!(
            "            pub {}: {},\n",
            rust_ident(&field.name),
            rust_type(&field.ty, records, enums),
        ));
    }
    output.push_str("        }\n\n");
}

fn render_function(
    output: &mut String,
    function: &FunctionModel,
    _records: &BTreeMap<String, &RecordModel>,
    _enums: &BTreeMap<String, &EnumModel>,
    plan: &FunctionPlan,
) {
    // Every registry import must remain callable even when its ergonomic
    // semantic adapter is specialized elsewhere. This is an exact ABI
    // forwarding entry, not a fake Result or an unreachable stub. Safe typed
    // wrappers take precedence above; callers using this last-resort entry
    // must acknowledge the raw Core ABI with `unsafe`.
    let signature =
        handwritten_signature_override(&plan.module, &function.name).unwrap_or(&plan.signature);
    let (parameter_types, result_type) = signature
        .split_once("->")
        .map(|(params, result)| {
            (
                params
                    .split(',')
                    .filter(|param| !param.is_empty())
                    .map(rust_signature_type)
                    .collect::<Vec<_>>(),
                rust_signature_type(result),
            )
        })
        .unwrap_or_else(|| (Vec::new(), "i32"));
    let params = parameter_types
        .iter()
        .enumerate()
        .map(|(index, ty)| format!("p{index}: {ty}"))
        .collect::<Vec<_>>()
        .join(", ");
    let args = parameter_types
        .iter()
        .enumerate()
        .map(|(index, _)| format!("p{index}"))
        .collect::<Vec<_>>()
        .join(", ");
    let raw_module = format!("__core_owned_{}", rust_ident(&function.name));
    output.push_str(&format!(
        "        #[cfg(target_arch = \"wasm32\")]\n        mod {raw_module} {{\n            #[link(wasm_import_module = \"{module}\")]\n            extern \"C\" {{\n                #[link_name = \"{import}\"]\n                pub fn call({params}) -> {result};\n            }}\n        }}\n\n        #[doc = \"Exact Core ABI forwarding entry for {module}.{import}.\"]\n        #[inline]\n        pub unsafe fn {name}({params}) -> {result} {{\n            unsafe {{ {raw_module}::call({args}) }}\n        }}\n\n",
        raw_module = raw_module,
        module = plan.import_module,
        import = plan.import_name,
        name = rust_ident(&function.name),
        params = params,
        result = result_type,
        args = args,
    ));
}

fn rust_signature_type(signature: &str) -> &'static str {
    match signature {
        "i32" => "i32",
        "i64" => "i64",
        "f32" => "f32",
        "f64" => "f64",
        other => panic!("unexpected Core ABI result type {other}"),
    }
}

/// The reviewed handwritten registry predates the semantic Core planner and
/// intentionally uses a few compact pointer/count ABIs. Keep those exact
/// signatures here for the ABI forwarding entries; generated transports use
/// the planner signature directly.
fn handwritten_signature_override(module: &str, function: &str) -> Option<&'static str> {
    match (module, function) {
        ("units_info", "GetUnitNanoPieces") => Some("i32,i32,i32->i64"),
        ("units_info", "GetUnitIsTransporting") => Some("i32,i32,i32,i32->i64"),
        ("units_query", "GetAllUnits") => Some("i32,i32->i64"),
        ("units_query", "GetTeamUnits") => Some("i32,i32,i32->i64"),
        ("units_query", "GetTeamUnitsByDefs") => Some("i32,i32,i32,i32,i32->i64"),
        ("units_query", "GetUnitArrayCentroid") => Some("i32,i32,i32->i32"),
        ("units_query", "GetUnitMapCentroid") => Some("i32,i32,i32->i32"),
        ("units_query", "GetUnitsInRectangle") => Some("f32,f32,f32,f32,i32,i32,i32->i64"),
        ("units_query", "GetUnitsInBox") => Some("f32,f32,f32,f32,f32,f32,i32,i32,i32->i64"),
        ("units_query", "GetUnitsInSphere") => Some("f32,f32,f32,f32,i32,i32,i32->i64"),
        ("units_query", "GetUnitsInCylinder") => Some("f32,f32,f32,i32,i32,i32->i64"),
        ("unit_defs", "GetUnitDefName") => Some("i32,i32,i32->i64"),
        ("unit_defs", "GetUnitDefHumanName") => Some("i32,i32,i32->i64"),
        ("units_commands", "GetUnitCommands") => Some("i32,i32,i32,i32->i64"),
        ("units_commands", "GiveOrder") => Some("i32,i32,i32,i32,i32->i64"),
        ("units_commands", "GiveOrderToUnitMap") => Some("i32,i32,i32,i32,i32,i32,i32->i64"),
        ("cob_script", "CallCOBScript") => Some("i32,i32,i32,i32,i32,i32,i32,i32,i32,i32->i64"),
        ("unit_control", "GiveOrderToUnit") => Some("i32,i32,i32,i32,i32,i32->i64"),
        ("terrain_control", "SetHeightMapFunc") => Some("i32,i32->i64"),
        ("terrain_control", "SetOriginalHeightMapFunc") => Some("i32,i32->i64"),
        ("terrain_control", "SetSmoothMeshFunc") => Some("i32,i32->i64"),
        ("system_control", "CallAsTeam") => Some("i32,i32,i32->i64"),
        ("math_extra", "Normalize") => Some("f32,f32,f32,i32->i32"),
        ("gfx", "BeginEnd") => Some("i32,i32,i32->i32"),
        ("gfx", "ActiveFBO") => Some("i32,i32,i32,i32,i32->i32"),
        ("gfx", "ActiveShader") => Some("i32,i32,i32->i32"),
        ("gfx", "CreateList") => Some("i32,i32->i64"),
        ("gfx", "DrawFuncAtUnit") => Some("i32,i32,i32,i32->i32"),
        ("gfx", "PushPopMatrix") => Some("i32,i32->i32"),
        ("gfx", "RenderToTexture") => Some("i32,i32,i32,i32->i32"),
        ("gfx", "RunQuery") => Some("i32,i32,i32->i32"),
        ("gfx", "UnsafeState") => Some("i32,i32,i32,i32->i32"),
        ("gfx", "CreateTexture") => Some("i32,i32,i32,i32,i32,i32->i64"),
        ("gfx", "CreateTextureAtlas") => Some("i32,i32,i32,i32,i32->i64"),
        ("profiling", "DiffTimers") => Some("i64,i64,i32,i32->i64"),
        ("messages", "Echo") => Some("i32,i32,i32,i32->i64"),
        ("messages", "Log") => Some("i32,i32,i32,i32,i32->i64"),
        ("messages", "SendMessage") => Some("i32,i32->i64"),
        ("messages", "SendMessageToPlayer") => Some("i32,i32,i32->i64"),
        ("messages", "SendMessageToTeam") => Some("i32,i32,i32->i64"),
        ("messages", "SendMessageToAllyTeam") => Some("i32,i32,i32->i64"),
        ("messages", "SendMessageToSpectators") => Some("i32,i32->i64"),
        ("messages", "SendPublicChat") => Some("i32,i32->i64"),
        ("messages", "SendAllyChat") => Some("i32,i32->i64"),
        ("messages", "SendSpectatorChat") => Some("i32,i32->i64"),
        ("messages", "SendPrivateChat") => Some("i32,i32,i32->i64"),
        ("messages", "SendCommands") => Some("i32,i32,i32,i32->i64"),
        ("messages", "SendLuaMenuMsg") => Some("i32,i32->i64"),
        ("messages", "SendSkirmishAIMessage") => Some("i32,i32,i32->i64"),
        ("messages", "SendLuaUIMsg") => Some("i32,i32,i32,i32->i64"),
        ("messages", "SendLuaGaiaMsg") => Some("i32,i32->i64"),
        ("messages", "SendLuaRulesMsg") => Some("i32,i32->i64"),
        ("messages", "SendToUnsynced") => Some("i32,i32->i64"),
        ("terrain", "IsPosInMap") => Some("f32,f32->i64"),
        ("terrain", "GetWaterPlaneLevel") => Some("->i64"),
        ("terrain", "GetGroundExtremes") => Some("i32->i32"),
        ("terrain", "GetHeightMapSize") => Some("i32->i32"),
        _ => None,
    }
}

fn render_normalize_forward(output: &mut String) {
    output.push_str(
        r#"        #[cfg(target_arch = "wasm32")]
        mod __core_math_extra_normalize {
            #[link(wasm_import_module = "spring:math-extra")]
            extern "C" {
                #[link_name = "normalize"]
                pub fn call(x: f32, y: f32, z: f32, output: i32) -> i32;
            }
        }

        #[inline]
        pub fn normalize(vec: Float3) -> Result<NormalizeValue> {
            #[cfg(target_arch = "wasm32")]
            {
                let mut output = [0.0f32; 4];
                let pointer = output.as_mut_ptr() as usize;
                if pointer > u32::MAX as usize {
                    return Err(crate::ApiError::new(crate::ErrorCode::InvalidArgument as i32));
                }
                let status = unsafe {
                    __core_math_extra_normalize::call(
                        vec.x,
                        vec.y,
                        vec.z,
                        pointer as u32 as i32,
                    )
                };
                if status != 0 {
                    return Err(crate::ApiError::new(status));
                }
                return Ok(NormalizeValue {
                    length: output[3],
                    vec: Float3 {
                        x: output[0],
                        y: output[1],
                        z: output[2],
                    },
                });
            }
            #[cfg(not(target_arch = "wasm32"))]
            {
                let _ = vec;
                Err(unreachable!())
            }
        }

"#,
    );
}

fn render_fixed_forward(
    output: &mut String,
    function: &FunctionModel,
    records: &BTreeMap<String, &RecordModel>,
    enums: &BTreeMap<String, &EnumModel>,
    module_ident: &str,
) {
    let params = function
        .inputs
        .iter()
        .map(|field| {
            format!(
                "{}: {}",
                rust_ident(&field.name),
                rust_param_type(&field.ty, records, enums)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let args = function
        .inputs
        .iter()
        .map(|field| {
            convert_to_core(
                &field.ty,
                &rust_ident(&field.name),
                records,
                enums,
                module_ident,
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let core_path = format!(
        "crate::generated::{module_ident}::{}",
        rust_ident(&function.name)
    );
    let body = match function.outputs.as_slice() {
        [] => format!("{core_path}({args})?;\n            Ok(())"),
        [field] => format!(
            "let value = {core_path}({args})?;\n            Ok({})",
            convert_from_core(&field.ty, "value", records, enums),
        ),
        fields => {
            let values = fields
                .iter()
                .enumerate()
                .map(|(index, field)| {
                    let value = format!("value.{index}");
                    format!(
                        "{}: {}",
                        rust_ident(&field.name),
                        convert_from_core(&field.ty, &value, records, enums)
                    )
                })
                .collect::<Vec<_>>()
                .join(",\n                ");
            format!(
                "let value = {core_path}({args})?;\n            Ok({}Value {{\n                {values}\n            }})",
                function.name
            )
        }
    };
    let return_type = match function.outputs.as_slice() {
        [] => "()".to_owned(),
        [field] => rust_type(&field.ty, records, enums),
        _ => format!("{}Value", function.name),
    };
    output.push_str(&format!(
        "        #[inline]\n        pub fn {}({params}) -> Result<{return_type}> {{\n            {body}\n        }}\n\n",
        rust_ident(&function.name),
    ));
}

fn convert_to_core(
    ty: &SemanticType,
    expression: &str,
    records: &BTreeMap<String, &RecordModel>,
    enums: &BTreeMap<String, &EnumModel>,
    module_ident: &str,
) -> String {
    match ty {
        SemanticType::Enum { name } => {
            let enum_model = enums[name];
            let arms = enum_model
                .variants
                .iter()
                .map(|(variant, value)| format!("{}::{variant_ident} => {value}i32", name, variant_ident = enum_variant_ident(name, variant)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("match {expression} {{ {arms} }}")
        }
        SemanticType::Record { name } => {
            let record = records[name];
            let fields = record
                .fields
                .iter()
                .map(|field| {
                    let field_name = rust_ident(&field.name);
                    format!("{field_name}: {}", convert_to_core(&field.ty, &format!("{expression}.{field_name}"), records, enums, module_ident))
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("crate::generated::{module_ident}::{name} {{ {fields} }}")
        }
        SemanticType::FixedArray { .. } => format!(
            "{expression}.clone().try_into().map_err(|_| crate::ApiError::new(crate::ErrorCode::InvalidArgument as i32))?"
        ),
        _ => expression.to_owned(),
    }
}

fn convert_from_core(
    ty: &SemanticType,
    expression: &str,
    records: &BTreeMap<String, &RecordModel>,
    enums: &BTreeMap<String, &EnumModel>,
) -> String {
    match ty {
        SemanticType::Enum { name } => {
            let enum_model = enums[name];
            let arms = enum_model
                .variants
                .iter()
                .map(|(variant, value)| {
                    format!(
                        "{value} => Ok({name}::{variant_ident})",
                        name = name,
                        variant_ident = enum_variant_ident(name, variant)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("match {expression} {{ {arms}, _ => Err(crate::ApiError::new(crate::ErrorCode::Internal as i32)) }}?")
        }
        SemanticType::Record { name } => {
            let record = records[name];
            let fields = record
                .fields
                .iter()
                .map(|field| {
                    let field_name = rust_ident(&field.name);
                    format!(
                        "{field_name}: {}",
                        convert_from_core(
                            &field.ty,
                            &format!("{expression}.{field_name}"),
                            records,
                            enums
                        )
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("{name} {{ {fields} }}")
        }
        SemanticType::FixedArray { element, .. } => format!(
            "{expression}.into_iter().map(|value| Ok({})).collect::<crate::Result<Vec<_>>>()?",
            convert_from_core(element, "value", records, enums)
        ),
        _ => expression.to_owned(),
    }
}

fn rust_type(
    ty: &SemanticType,
    records: &BTreeMap<String, &RecordModel>,
    enums: &BTreeMap<String, &EnumModel>,
) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "char" => "u8".to_owned(),
            "void" => "()".to_owned(),
            other => other.to_owned(),
        },
        SemanticType::Enum { name } => {
            if enums.contains_key(name) {
                name.to_owned()
            } else {
                "i32".to_owned()
            }
        }
        SemanticType::Record { name } => {
            if records.contains_key(name) {
                name.to_owned()
            } else {
                "u32".to_owned()
            }
        }
        SemanticType::String => "String".to_owned(),
        SemanticType::Bytes => "Vec<u8>".to_owned(),
        SemanticType::List { element } => {
            format!("Vec<{}>", rust_type(element, records, enums))
        }
        // The semantic Core façade follows the WIT surface.  Native fixed
        // arrays are lowered to `list<T>` there, while the raw transport
        // keeps the fixed width for validation and packing.
        SemanticType::FixedArray { element, .. } => {
            format!("Vec<{}>", rust_type(element, records, enums))
        }
        SemanticType::Option { inner } => {
            format!("Option<{}>", rust_type(inner, records, enums))
        }
        SemanticType::Handle { .. } => "u64".to_owned(),
        SemanticType::Callback { .. }
        | SemanticType::Pointer { .. }
        | SemanticType::Unknown { .. } => "u32".to_owned(),
        SemanticType::Result { ok, .. } => ok
            .as_deref()
            .map(|inner| rust_type(inner, records, enums))
            .unwrap_or_else(|| "()".to_owned()),
    }
}

fn needs_borrow(ty: &SemanticType, records: &BTreeMap<String, &RecordModel>) -> bool {
    match ty {
        SemanticType::String
        | SemanticType::Bytes
        | SemanticType::List { .. }
        | SemanticType::FixedArray { .. } => true,
        SemanticType::Option { inner } => matches!(inner.as_ref(), SemanticType::String),
        SemanticType::Record { name } => records.get(name).is_some_and(|record| {
            record
                .fields
                .iter()
                .any(|field| needs_borrow(&field.ty, records))
        }),
        _ => false,
    }
}

fn rust_param_type(
    ty: &SemanticType,
    records: &BTreeMap<String, &RecordModel>,
    enums: &BTreeMap<String, &EnumModel>,
) -> String {
    match ty {
        SemanticType::String => "&str".to_owned(),
        SemanticType::Option { inner } if matches!(inner.as_ref(), SemanticType::String) => {
            "Option<&str>".to_owned()
        }
        other if needs_borrow(other, records) => {
            format!("&{}", rust_type(other, records, enums))
        }
        other => rust_type(other, records, enums),
    }
}

fn enum_variant_ident(_enum_name: &str, variant: &str) -> String {
    let value = variant.to_lowercase();
    value
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_uppercase().collect::<String>() + chars.as_str())
                .unwrap_or_default()
        })
        .collect()
}

fn rust_ident(value: &str) -> String {
    let value = value.to_snake_case();
    if matches!(
        value.as_str(),
        "as" | "async"
            | "await"
            | "box"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "do"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "macro"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "override"
            | "priv"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "typeof"
            | "unsafe"
            | "unsized"
            | "use"
            | "where"
            | "while"
            | "yield"
    ) {
        format!("{value}_")
    } else {
        value
    }
}
