//! Guest wrappers for nested dynamic-input Core callouts.
//!
//! Nested semantic values are passed as canonical schema blobs. This keeps raw
//! wasm32 pointers inside generated code while parity/tests can encode exactly
//! the semantic record they want to exercise.

use heck::ToSnakeCase;
use std::collections::BTreeMap;

use crate::model::{ApiModel, RecordModel, SemanticType};
use crate::render_core_wasm::{self, CoreType, ResultStrategy};
use crate::render_core_wasm_dynamic_input_host;

pub fn render(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();
    let mut modules = String::new();
    let mut total = 0usize;

    for module in &model.modules {
        let functions = module
            .functions
            .iter()
            .filter_map(|function| {
                let plan = plans.get(&(module.name.clone(), function.name.clone()))?;
                render_core_wasm_dynamic_input_host::eligible(
                    plan,
                    &function.inputs,
                    &function.outputs,
                    &records,
                )
                .then_some((function, plan))
            })
            .collect::<Vec<_>>();
        if functions.is_empty() {
            continue;
        }
        total += functions.len();
        let module_ident = rust_ident(&module.name.to_snake_case());
        modules.push_str(&format!("    pub mod {module_ident} {{\n"));
        modules.push_str("        #[cfg(target_arch = \"wasm32\")]\n        mod raw {\n");
        for (_, plan) in &functions {
            modules.push_str(&render_raw(plan));
        }
        modules.push_str("        }\n\n");
        for (function, plan) in functions {
            modules.push_str(&render_wrapper(function, plan, &records));
            modules.push('\n');
        }
        modules.push_str("    }\n\n");
    }

    format!(
        "// @generated by spring-api-codegen; do not edit.\n\
         pub mod dynamic_input {{\n\
             #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
             pub struct VariableResultError {{\n\
                 pub error: crate::ApiError,\n\
                 pub required: usize,\n\
             }}\n\n\
         {modules}\
             #[doc(hidden)]\n\
             pub const __GENERATED_DYNAMIC_INPUT_CALLOUT_COUNT: usize = {total};\n\
         }}\n",
        modules = modules,
        total = total,
    )
}

fn render_raw(plan: &render_core_wasm::FunctionPlan) -> String {
    let ident = rust_ident(&plan.function.to_snake_case());
    let params = plan
        .direct_params
        .iter()
        .enumerate()
        .map(|(index, ty)| format!("p{index}: {}", rust_core_type(*ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let result = plan
        .direct_results
        .first()
        .map(|ty| format!(" -> {}", rust_core_type(*ty)))
        .unwrap_or_default();
    format!(
        "            #[link(wasm_import_module = \"{module}\")]\n\
                     unsafe extern \"C\" {{\n\
                         #[link_name = \"{name}\"]\n\
                         pub safe fn {ident}({params}){result};\n\
                     }}\n",
        module = plan.import_module,
        name = plan.import_name,
        ident = ident,
        params = params,
        result = result,
    )
}

fn render_wrapper(
    function: &crate::model::FunctionModel,
    plan: &render_core_wasm::FunctionPlan,
    records: &BTreeMap<String, RecordModel>,
) -> String {
    let ident = rust_ident(&function.name.to_snake_case());
    let direct_count = function
        .inputs
        .iter()
        .filter(|field| direct_type(&field.ty))
        .count();
    let blobs = function
        .inputs
        .iter()
        .filter(|field| !direct_type(&field.ty))
        .collect::<Vec<_>>();

    let mut params = (0..direct_count)
        .map(|index| format!("p{index}: {}", rust_core_type(plan.direct_params[index])))
        .collect::<Vec<_>>();
    params.extend(
        blobs
            .iter()
            .enumerate()
            .map(|(index, _)| format!("blob{index}: &[u8]")),
    );

    let descriptor_words = blobs.len() * 2;
    let descriptor_fill = blobs
        .iter()
        .enumerate()
        .map(|(index, _)| {
            format!(
                "            let (blob{index}_ptr, blob{index}_len) =\n\
                 match crate::wasm_slice_parts(blob{index}) {{\n\
                     Ok(value) => value,\n\
                     Err(_) => return {bounds_return},\n\
                 }};\n\
                 descriptor[{word}] = blob{index}_ptr as u32;\n\
                 descriptor[{len_word}] = blob{index}_len as u32;\n",
                bounds_return = bounds_return(plan),
                word = index * 2,
                len_word = index * 2 + 1,
            )
        })
        .collect::<String>();

    let direct_args = (0..direct_count)
        .map(|index| format!("p{index}"))
        .collect::<Vec<_>>();
    let non_wasm_ignored = (0..direct_count)
        .map(|index| format!("p{index}"))
        .chain((0..blobs.len()).map(|index| format!("blob{index}")))
        .collect::<Vec<_>>()
        .join(", ");

    match plan.result_strategy {
        ResultStrategy::Status | ResultStrategy::Packed32 => {
            let ret_ty = scalar_return_type(function, plan);
            let result_expr = scalar_result_expr(function, plan, &ident, &direct_args);
            let arity_lint = too_many_arguments_attribute(params.len(), 20);
            format!(
                "        #[inline]\n\
                 {arity_lint}pub fn {ident}({params}) -> {ret_ty} {{\n\
                     #[cfg(target_arch = \"wasm32\")]\n\
                     {{\n\
                         let mut descriptor = [0u32; {descriptor_words}];\n\
             {descriptor_fill}\
                         let descriptor_ptr = match crate::wasm_output_ptr(&mut descriptor) {{\n\
                             Ok(value) => value,\n\
                             Err(_) => return {bounds_return},\n\
                         }};\n\
                         {result_expr}\n\
                     }}\n\
                     #[cfg(not(target_arch = \"wasm32\"))]\n\
                     {{\n\
                         let _ = ({non_wasm_ignored});\n\
                         {unsupported_return}\n\
                     }}\n\
                 }}\n",
                ident = ident,
                params = params.join(", "),
                ret_ty = ret_ty,
                descriptor_words = descriptor_words,
                descriptor_fill = descriptor_fill,
                bounds_return = bounds_return(plan),
                result_expr = result_expr,
                non_wasm_ignored = non_wasm_ignored,
                unsupported_return = unsupported_return(plan),
            )
        }
        ResultStrategy::FixedOutputBuffer { bytes, .. } => {
            params.push("output: &mut [u8]".to_owned());
            let arity_lint = too_many_arguments_attribute(params.len(), 20);
            let mut call_args = direct_args;
            call_args.push("descriptor_ptr".to_owned());
            call_args.push("output_ptr".to_owned());
            format!(
                "        #[inline]\n\
                 {arity_lint}pub fn {ident}({params}) -> crate::Result<()> {{\n\
                     #[cfg(target_arch = \"wasm32\")]\n\
                     {{\n\
                         if output.len() != {bytes}usize {{ return Err(crate::ApiError::new(crate::ErrorCode::InvalidArgument as i32)); }}\n\
                         let mut descriptor = [0u32; {descriptor_words}];\n\
             {descriptor_fill}\
                         let descriptor_ptr = crate::wasm_output_ptr(&mut descriptor)?;\n\
                         let (output_ptr, _) = crate::wasm_mut_slice_parts(output)?;\n\
                         let status = raw::{ident}({call_args});\n\
                         if status == 0 {{ Ok(()) }} else {{ Err(crate::ApiError::new(status)) }}\n\
                     }}\n\
                     #[cfg(not(target_arch = \"wasm32\"))]\n\
                     {{\n\
                         let _ = ({non_wasm_ignored}, output);\n\
                         Err(unreachable!())\n\
                     }}\n\
                 }}\n",
                ident = ident,
                params = params.join(", "),
                bytes = bytes,
                descriptor_words = descriptor_words,
                descriptor_fill = descriptor_fill,
                call_args = call_args.join(", "),
                non_wasm_ignored = non_wasm_ignored,
            )
        }
        ResultStrategy::VariableOutputBuffer => {
            let field = &function.outputs[0];
            let element_bytes = match &field.ty {
                SemanticType::List { element } => {
                    fixed_wire_layout(element, records)
                        .expect("eligible variable result layout")
                        .0
                }
                SemanticType::String => 1,
                _ => unreachable!(),
            };
            params.push("output: &mut [u8]".to_owned());
            let arity_lint = too_many_arguments_attribute(params.len(), 20);
            let mut call_args = direct_args;
            call_args.push("descriptor_ptr".to_owned());
            call_args.push("output_descriptor_ptr".to_owned());
            format!(
                "        #[inline]\n\
                 {arity_lint}pub fn {ident}({params}) -> core::result::Result<usize, super::VariableResultError> {{\n\
                     #[cfg(target_arch = \"wasm32\")]\n\
                     {{\n\
                         if !output.len().is_multiple_of({element_bytes}usize) || output.len() / {element_bytes}usize > u32::MAX as usize {{\n\
                             return Err(super::VariableResultError {{ error: crate::ApiError::new(crate::ErrorCode::InvalidArgument as i32), required: 0 }});\n\
                         }}\n\
                         let mut descriptor = [0u32; {descriptor_words}];\n\
             {descriptor_fill}\
                         let descriptor_ptr = crate::wasm_output_ptr(&mut descriptor)\n\
                             .map_err(|error| super::VariableResultError {{ error, required: 0 }})?;\n\
                         let (output_ptr, output_bytes) = crate::wasm_mut_slice_parts(output)\n\
                             .map_err(|error| super::VariableResultError {{ error, required: 0 }})?;\n\
                         let output_capacity = output_bytes as usize / {element_bytes}usize;\n\
                         let mut output_descriptor = [output_ptr as u32, output_capacity as u32, 0u32];\n\
                         let output_descriptor_ptr = crate::wasm_output_ptr(&mut output_descriptor)\n\
                             .map_err(|error| super::VariableResultError {{ error, required: 0 }})?;\n\
                         let status = raw::{ident}({call_args});\n\
                         let required = output_descriptor[2] as usize;\n\
                         if status == 0 {{ Ok(required) }} else {{ Err(super::VariableResultError {{ error: crate::ApiError::new(status), required }}) }}\n\
                     }}\n\
                     #[cfg(not(target_arch = \"wasm32\"))]\n\
                     {{\n\
                         let _ = ({non_wasm_ignored}, output);\n\
                         Err(super::VariableResultError {{ error: unreachable!(), required: 0 }})\n\
                     }}\n\
                 }}\n",
                ident = ident,
                params = params.join(", "),
                element_bytes = element_bytes,
                descriptor_words = descriptor_words,
                descriptor_fill = descriptor_fill,
                call_args = call_args.join(", "),
                non_wasm_ignored = non_wasm_ignored,
            )
        }
        ResultStrategy::Unsupported => unreachable!(),
    }
}

fn scalar_return_type(
    function: &crate::model::FunctionModel,
    plan: &render_core_wasm::FunctionPlan,
) -> &'static str {
    match plan.result_strategy {
        ResultStrategy::Status => "crate::Result<()>",
        ResultStrategy::Packed32 => match &function.outputs[0].ty {
            SemanticType::Scalar { name } if name == "bool" => "crate::Result<bool>",
            SemanticType::Scalar { name } if name == "f32" => "crate::Result<f32>",
            _ => "crate::Result<i32>",
        },
        _ => unreachable!(),
    }
}

fn too_many_arguments_attribute(count: usize, indent: usize) -> String {
    let _ = (count, indent);
    String::new()
}

fn scalar_result_expr(
    function: &crate::model::FunctionModel,
    plan: &render_core_wasm::FunctionPlan,
    ident: &str,
    direct_args: &[String],
) -> String {
    let mut args = direct_args.to_vec();
    args.push("descriptor_ptr".to_owned());
    let call = format!("raw::{ident}({})", args.join(", "));
    match plan.result_strategy {
        ResultStrategy::Status => format!(
            "let status = {call}; if status == 0 {{ Ok(()) }} else {{ Err(crate::ApiError::new(status)) }}"
        ),
        ResultStrategy::Packed32 => match &function.outputs[0].ty {
            SemanticType::Scalar { name } if name == "bool" => {
                format!("crate::unpack_bool({call})")
            }
            SemanticType::Scalar { name } if name == "f32" => {
                format!("crate::decode_packed_f32({call})")
            }
            _ => format!("crate::unpack_i32({call})"),
        },
        _ => unreachable!(),
    }
}

fn bounds_return(plan: &render_core_wasm::FunctionPlan) -> String {
    match plan.result_strategy {
        ResultStrategy::VariableOutputBuffer => "Err(super::VariableResultError { error: crate::ApiError::new(crate::ErrorCode::OutOfBounds as i32), required: 0 })".to_owned(),
        _ => "Err(crate::ApiError::new(crate::ErrorCode::OutOfBounds as i32))".to_owned(),
    }
}

fn unsupported_return(plan: &render_core_wasm::FunctionPlan) -> String {
    match plan.result_strategy {
        ResultStrategy::VariableOutputBuffer => {
            "Err(super::VariableResultError { error: unreachable!(), required: 0 })".to_owned()
        }
        _ => "Err(unreachable!())".to_owned(),
    }
}

fn direct_type(ty: &SemanticType) -> bool {
    matches!(
        ty,
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. }
    )
}

fn fixed_wire_layout(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i64" | "u64" | "isize" | "usize" | "f64" => Some((8, 8)),
            _ => Some((4, 4)),
        },
        SemanticType::Enum { .. } => Some((4, 4)),
        SemanticType::Handle { .. } => Some((8, 8)),
        SemanticType::FixedArray { element, length } => {
            let (bytes, alignment) = fixed_wire_layout(element, records)?;
            Some((bytes.checked_mul(u32::try_from(*length).ok()?)?, alignment))
        }
        SemanticType::Record { name } => {
            let mut bytes = 0u32;
            let mut alignment = 1u32;
            for field in &records.get(name)?.fields {
                let (field_bytes, field_alignment) = fixed_wire_layout(&field.ty, records)?;
                bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
                alignment = alignment.max(field_alignment);
            }
            Some((align_up(bytes, alignment), alignment))
        }
        _ => None,
    }
}

fn align_up(value: u32, alignment: u32) -> u32 {
    (value + alignment - 1) & !(alignment - 1)
}

fn rust_core_type(ty: CoreType) -> &'static str {
    match ty {
        CoreType::I32 => "i32",
        CoreType::I64 => "i64",
        CoreType::F32 => "f32",
        CoreType::F64 => "f64",
    }
}

fn rust_ident(value: &str) -> String {
    match value {
        "type" | "match" | "move" | "ref" | "self" | "Self" | "super" | "crate" | "where"
        | "loop" | "in" | "mod" | "fn" | "struct" | "enum" | "use" | "pub" | "impl" | "trait"
        | "const" | "static" | "async" | "await" | "dyn" | "abstract" | "become" | "box" | "do"
        | "final" | "macro" | "override" | "priv" | "typeof" | "unsized" | "virtual" | "yield"
        | "try" => {
            format!("r#{value}")
        }
        _ => value.to_owned(),
    }
}

fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records
                .entry(record.name.clone())
                .or_insert_with(|| record.clone());
        }
    }
    records
}
