//! Generated callin interfaces and dispatch metadata.

use heck::ToKebabCase;

fn wit_identifier(name: &str) -> String {
    let name = name.to_kebab_case();
    if matches!(
        name.as_str(),
        "use"
            | "type"
            | "func"
            | "u8"
            | "u16"
            | "u32"
            | "u64"
            | "s8"
            | "s16"
            | "s32"
            | "s64"
            | "f32"
            | "f64"
            | "char"
            | "own"
            | "borrow"
            | "resource"
            | "record"
            | "flags"
            | "variant"
            | "enum"
            | "bool"
            | "string"
            | "option"
            | "result"
            | "future"
            | "stream"
            | "error-context"
            | "list"
            | "map"
            | "_"
            | "as"
            | "from"
            | "static"
            | "interface"
            | "tuple"
            | "import"
            | "export"
            | "world"
            | "package"
            | "constructor"
            | "include"
            | "with"
            | "async"
    ) {
        format!("%{name}")
    } else {
        name
    }
}
use std::collections::BTreeSet;

use crate::model::{ApiModel, CallinModel, Environment, RecordModel, SemanticType};
use crate::render_wit::wit_type;

/// Render the environment-specific guest export interface for engine callins.
/// Query/result records are copied into each interface so a world never
/// imports a callin whose visibility belongs to a different execution role.
pub fn render_wit(model: &ApiModel, environment: Environment) -> String {
    let interface_name = format!("callins-{}", environment.as_str().to_kebab_case());
    let callins = model
        .callins
        .iter()
        .filter(|callin| callin.environments.contains(&environment))
        .collect::<Vec<_>>();
    let records = records_for(model, &callins);

    let mut output = String::from(
        "package recoil:spring-api@1.0.0;\n\n/* @generated by spring-api-codegen; do not edit. */\n\n",
    );
    output.push_str(&format!("interface {interface_name} {{\n"));
    output.push_str("  record spring-error { code: s32 }\n\n");

    for record in records {
        output.push_str(&format!("  record {} {{\n", wit_identifier(&record.name)));
        for field in &record.fields {
            output.push_str(&format!(
                "    {}: {},\n",
                wit_identifier(&field.name),
                wit_type(&field.ty)
            ));
        }
        output.push_str("  }\n\n");
    }

    for callin in callins {
        output.push_str(&render_callin(model, callin));
        for alias in &callin.aliases {
            output.push_str(&render_callin_name(model, callin, alias));
        }
    }
    output.push_str("}\n");
    output
}

/// Render a compact Rust dispatch seam. Typed WIT bindings can wrap this
/// seam, while the engine-facing transport remains independent of a specific
/// serialization library.
pub fn render_rust(model: &ApiModel) -> String {
    let mut output = String::from("// @generated by spring-api-codegen; do not edit.\n\n");
    output.push_str("use crate::ApiError;\n\n");
    output.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    output.push_str("pub struct CallinDescriptor { pub name: &'static str, pub canonical: &'static str, pub aggregation: &'static str }\n\n");
    output.push_str("pub const CALLINS: &[CallinDescriptor] = &[\n");
    for callin in &model.callins {
        output.push_str(&format!(
            "    CallinDescriptor {{ name: {:?}, canonical: {:?}, aggregation: {:?} }},\n",
            callin.name, callin.name, callin.aggregation
        ));
        for alias in &callin.aliases {
            output.push_str(&format!(
                "    CallinDescriptor {{ name: {:?}, canonical: {:?}, aggregation: {:?} }},\n",
                alias, callin.name, callin.aggregation
            ));
        }
    }
    output.push_str("];\n\n");
    output.push_str("pub trait CallinHandler {\n    fn dispatch_callin(&mut self, name: &str, query: &[u8]) -> Result<Vec<u8>, ApiError>;\n}\n\n");
    output.push_str("pub fn dispatch<H: CallinHandler>(handler: &mut H, name: &str, query: &[u8]) -> Result<Vec<u8>, ApiError> {\n");
    output.push_str("    let canonical = CALLINS.iter().find(|callin| callin.name == name).map(|callin| callin.canonical).ok_or_else(|| ApiError::with_detail(10, crate::ErrorCategory::Unavailable, \"unknown callin\"))?;\n");
    output.push_str("    handler.dispatch_callin(canonical, query)\n}\n");
    output
}

fn render_callin(model: &ApiModel, callin: &CallinModel) -> String {
    render_callin_name(model, callin, &callin.name)
}

fn render_callin_name(model: &ApiModel, callin: &CallinModel, name: &str) -> String {
    let query = record_or_unit(model, &callin.query);
    let result = record_or_unit(model, &callin.result);
    let parameters = if query == "()" {
        String::new()
    } else {
        format!("query: {query}")
    };
    format!(
        "  /// aggregation: {}\n  {}: func({}) -> result<{}, spring-error>;\n\n",
        callin.aggregation,
        wit_identifier(name),
        parameters,
        if result == "()" { "_" } else { result.as_str() }
    )
}

fn record_or_unit(model: &ApiModel, name: &str) -> String {
    match find_record(model, name) {
        Some(record) if record.fields.is_empty() => "()".to_string(),
        _ => wit_identifier(name),
    }
}

fn records_for<'a>(model: &'a ApiModel, callins: &[&CallinModel]) -> Vec<&'a RecordModel> {
    let mut names = callins
        .iter()
        .flat_map(|callin| [&callin.query, &callin.result])
        .cloned()
        .collect::<BTreeSet<_>>();
    let mut cursor = 0;
    let mut ordered_names = names.iter().cloned().collect::<Vec<_>>();
    while cursor < ordered_names.len() {
        let name = &ordered_names[cursor];
        if let Some(record) = find_record(model, name) {
            for field in &record.fields {
                collect_type_records(&field.ty, &mut names);
            }
        }
        ordered_names = names.iter().cloned().collect();
        cursor += 1;
    }
    let mut records = Vec::new();
    for name in names {
        if let Some(record) = find_record(model, &name).filter(|record| !record.fields.is_empty()) {
            records.push(record);
        }
    }
    records.sort_by(|left, right| left.name.cmp(&right.name));
    records
}

fn find_record<'a>(model: &'a ApiModel, name: &str) -> Option<&'a RecordModel> {
    model
        .modules
        .iter()
        .flat_map(|module| module.records.iter())
        .find(|record| record.name == name)
}

fn collect_type_records(ty: &SemanticType, names: &mut BTreeSet<String>) {
    match ty {
        SemanticType::Record { name } => {
            names.insert(name.clone());
        }
        SemanticType::List { element }
        | SemanticType::FixedArray { element, .. }
        | SemanticType::Option { inner: element }
        | SemanticType::Pointer {
            pointee: element, ..
        } => collect_type_records(element, names),
        SemanticType::Result { ok, error } => {
            if let Some(ok) = ok {
                collect_type_records(ok, names);
            }
            if let Some(error) = error {
                collect_type_records(error, names);
            }
        }
        SemanticType::Scalar { .. }
        | SemanticType::Enum { .. }
        | SemanticType::String
        | SemanticType::Bytes
        | SemanticType::Handle { .. }
        | SemanticType::Callback { .. }
        | SemanticType::Unknown { .. } => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{ApiModel, ApiModule, FunctionModel, LoweringStatus};

    #[test]
    fn renders_environment_specific_callins_and_aliases() {
        let model = ApiModel {
            model_version: 1,
            native_api_version: None,
            modules: vec![ApiModule {
                name: "callins".to_string(),
                interface_version: "1.0".to_string(),
                functions: vec![FunctionModel {
                    name: "unused".to_string(),
                    query: "unused-query".to_string(),
                    result: "unused-result".to_string(),
                    inputs: Vec::new(),
                    outputs: Vec::new(),
                    environments: BTreeSet::new(),
                    mutating: false,
                    visibility_sensitive: false,
                    status: LoweringStatus::Automatic,
                    notes: Vec::new(),
                }],
                records: Vec::new(),
                enums: Vec::new(),
            }],
            callins: vec![CallinModel {
                name: "GameFrame".to_string(),
                query: "GameFrameQuery".to_string(),
                result: "GameFrameResult".to_string(),
                environments: BTreeSet::from([Environment::RulesSynced]),
                aggregation: "ignore".to_string(),
                aliases: vec!["Frame".to_string()],
                flags: Vec::new(),
            }],
        };
        let output = render_wit(&model, Environment::RulesSynced);
        assert!(output.contains("game-frame: func"));
        assert!(output.contains("frame: func"));
    }
}
