//! Generate Core-Wasm host callbacks for automatic/annotated functions whose
//! inputs contain strings, bytes or lists. Variable inputs are described by one
//! guest-memory descriptor; all guest data is validated and copied before the
//! NativeInterface call.

use heck::{ToLowerCamelCase, ToSnakeCase};
use std::collections::BTreeMap;

use crate::model::{ApiModel, FieldModel, RecordModel, SemanticType};
use crate::render_core_wasm::{self, CoreType, FunctionPlan, InputStrategy, ResultStrategy};

pub fn render_header() -> String {
    r#"/* @generated by spring-api-codegen; do not edit. */
#pragma once

#include <string>

#include "WasmInterface/WasmCoreBindings.h"

namespace recoil::wasm::core::generated {

bool RegisterGeneratedVariableImports(wasmtime_linker_t* linker, HostState* state,
    std::string& error);

} // namespace recoil::wasm::core::generated
"#
    .to_owned()
}

pub fn render_cpp(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();

    let mut callbacks = String::new();
    let mut registrations = String::new();
    let mut generated_count = 0usize;

    for module in &model.modules {
        for function in &module.functions {
            let Some(plan) = plans.get(&(module.name.clone(), function.name.clone())) else {
                continue;
            };
            if !eligible(plan, &function.inputs, &function.outputs, &records) {
                continue;
            }
            generated_count += 1;
            callbacks.push_str(&render_callback(&module.name, function, plan, &records));
            callbacks.push('\n');
            registrations.push_str(&render_registration(
                plan,
                &callback_name(&module.name, &function.name),
            ));
        }
    }

    format!(
        r#"/* @generated by spring-api-codegen; do not edit. */

#include "wasm/generated/WasmCoreGeneratedVariableBindings.h"

#include <array>
#include <bit>
#include <cstdint>
#include <limits>
#include <span>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

#include "NativeInterface/NativeInterface.h"
#include "WasmInterface/WasmCoreAbi.h"
#include "WasmInterface/WasmCoreGeneratedSupport.h"
#include "WasmInterface/WasmCoreWire.h"

namespace recoil::wasm::core::generated {{
namespace {{

template<typename T>
bool AssignCoreCount(std::uint32_t value, T& output)
{{
    using Native = std::remove_cv_t<std::remove_reference_t<T>>;
    if constexpr (std::numeric_limits<Native>::is_signed) {{
        if (static_cast<std::uint64_t>(value) >
            static_cast<std::uint64_t>(std::numeric_limits<Native>::max()))
            return false;
    }}
    output = static_cast<Native>(value);
    return true;
}}

bool DefineGeneratedVariable(wasmtime_linker_t* linker, const char* moduleName,
    const char* functionName, wasm_functype_t* type,
    wasmtime_func_unchecked_callback_t callback, HostState* state, std::string& error)
{{
    wasmtime_error_t* defineError = wasmtime_linker_define_func_unchecked(
        linker,
        moduleName, std::char_traits<char>::length(moduleName),
        functionName, std::char_traits<char>::length(functionName),
        type, callback, state, nullptr);
    wasm_functype_delete(type);
    if (defineError == nullptr)
        return true;
    error = ErrorMessage(defineError);
    return false;
}}

{callbacks}
}} // namespace

bool RegisterGeneratedVariableImports(wasmtime_linker_t* linker, HostState* state,
    std::string& error)
{{
    if (linker == nullptr || state == nullptr || state->native == nullptr) {{
        error = "cannot register generated variable Core imports without linker/host/native API";
        return false;
    }}
{registrations}
    return true;
}}

static_assert({generated_count} >= 0, "generated variable Core callback count");

}} // namespace recoil::wasm::core::generated
"#,
        callbacks = callbacks,
        registrations = registrations,
        generated_count = generated_count,
    )
}

pub(crate) fn eligible(
    plan: &FunctionPlan,
    inputs: &[FieldModel],
    outputs: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    if matches!(plan.source_status.as_str(), "manual" | "unsupported")
        || !matches!(plan.input_strategy, InputStrategy::VariableInputBuffer)
    {
        return false;
    }
    if descriptor_layout(inputs, records).is_none() {
        return false;
    }
    for field in inputs {
        if direct_type(&field.ty) || fixed_wire_type(&field.ty, records) {
            continue;
        }
        if !variable_field_supported(field, records) {
            return false;
        }
    }
    match plan.result_strategy {
        ResultStrategy::Status => true,
        ResultStrategy::Packed32 => {
            outputs.len() == 1
                && matches!(
                    outputs[0].ty,
                    SemanticType::Scalar { .. } | SemanticType::Enum { .. }
                )
        }
        ResultStrategy::FixedOutputBuffer { .. } => outputs
            .iter()
            .all(|field| fixed_wire_type(&field.ty, records)),
        ResultStrategy::VariableOutputBuffer | ResultStrategy::Unsupported => false,
    }
}

fn direct_type(ty: &SemanticType) -> bool {
    matches!(
        ty,
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. }
    )
}

fn variable_field_supported(
    field: &FieldModel,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    match &field.ty {
        SemanticType::String => true,
        SemanticType::Bytes => count_field(field).is_some(),
        SemanticType::List { element } => {
            count_field(field).is_some() && list_element_supported(element, records)
        }
        _ => false,
    }
}

fn list_element_supported(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    match ty {
        SemanticType::String => true,
        SemanticType::Scalar { name } if name == "bool" => false,
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. } => true,
        SemanticType::Record { .. } | SemanticType::FixedArray { .. } => {
            fixed_wire_type(ty, records)
        }
        _ => false,
    }
}

fn fixed_wire_type(ty: &SemanticType, records: &BTreeMap<String, RecordModel>) -> bool {
    match ty {
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. } => true,
        SemanticType::FixedArray { element, length } => {
            *length <= 64 && fixed_wire_type(element, records)
        }
        SemanticType::Record { name } => records
            .get(name)
            .is_some_and(|record| {
                record
                    .fields
                    .iter()
                    .all(|field| fixed_wire_type(&field.ty, records))
            }),
        _ => false,
    }
}

fn fixed_wire_layout(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i64" | "u64" | "isize" | "usize" | "f64" => Some((8, 8)),
            _ => Some((4, 4)),
        },
        SemanticType::Enum { .. } => Some((4, 4)),
        SemanticType::Handle { .. } => Some((8, 8)),
        SemanticType::FixedArray { element, length } => {
            let (bytes, alignment) = fixed_wire_layout(element, records)?;
            Some((bytes.checked_mul(u32::try_from(*length).ok()?)?, alignment))
        }
        SemanticType::Record { name } => {
            let record = records.get(name)?;
            layout_fields(&record.fields, records)
        }
        _ => None,
    }
}

fn descriptor_field_layout(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    match ty {
        SemanticType::String | SemanticType::Bytes | SemanticType::List { .. } => Some((8, 4)),
        _ => fixed_wire_layout(ty, records),
    }
}

fn descriptor_layout(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    let mut bytes = 0u32;
    let mut alignment = 1u32;
    let mut any = false;
    for field in fields.iter().filter(|field| !direct_type(&field.ty)) {
        let (field_bytes, field_alignment) = descriptor_field_layout(&field.ty, records)?;
        bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
        alignment = alignment.max(field_alignment);
        any = true;
    }
    any.then(|| (align_up(bytes, alignment), alignment))
}

fn layout_fields(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    let mut bytes = 0u32;
    let mut alignment = 1u32;
    for field in fields {
        let (field_bytes, field_alignment) = fixed_wire_layout(&field.ty, records)?;
        bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
        alignment = alignment.max(field_alignment);
    }
    Some((align_up(bytes, alignment), alignment))
}

fn align_up(value: u32, alignment: u32) -> u32 {
    debug_assert!(alignment.is_power_of_two());
    (value + alignment - 1) & !(alignment - 1)
}

fn render_callback(
    module_name: &str,
    function: &crate::model::FunctionModel,
    plan: &FunctionPlan,
    records: &BTreeMap<String, RecordModel>,
) -> String {
    let callback = callback_name(module_name, &function.name);
    let api_member = native_member(module_name);
    let slot_count = plan.direct_params.len().max(plan.direct_results.len());
    let work = 1 + plan.direct_params.len() as u64;
    let direct_input_count = function
        .inputs
        .iter()
        .filter(|field| direct_type(&field.ty))
        .count();
    let (descriptor_bytes, descriptor_alignment) =
        descriptor_layout(&function.inputs, records).expect("eligible descriptor layout");
    let descriptor_index = direct_input_count;
    let mut body = String::new();

    body.push_str(&format!(
        "wasm_trap_t* {callback}(void* environment, wasmtime_caller_t* caller,\n    wasmtime_val_raw_t* slots, std::size_t slotCount)\n{{\n    auto* state = static_cast<HostState*>(environment);\n    if (state == nullptr || state->native == nullptr || state->native->{api_member} == nullptr ||\n        state->native->{api_member}->{function_name} == nullptr)\n        return Trap(\"{function_name} generated Core binding is unavailable\");\n    if (slots == nullptr || slotCount != {slot_count})\n        return Trap(\"{function_name} generated Core ABI signature mismatch\");\n\n    std::string budgetError;\n    ImportGuard guard(state, {work}u, budgetError);\n    if (!guard.Ok())\n        return Trap(budgetError);\n\n    std::string memoryError;\n    if (!EnsureMemory(state, caller, memoryError))\n        return Trap(memoryError);\n    const std::uint32_t descriptor = static_cast<std::uint32_t>(slots[{descriptor_index}].i32);\n    std::span<const std::uint8_t> descriptorWire;\n    if (!state->memory.View(descriptor, {descriptor_bytes}u, descriptorWire)) {{\n{descriptor_error}    }}\n    WireReader reader(descriptorWire);\n",
        callback = callback,
        api_member = api_member,
        function_name = function.name,
        slot_count = slot_count,
        work = work,
        descriptor_index = descriptor_index,
        descriptor_bytes = descriptor_bytes,
        descriptor_error = render_error_return(plan, "Status::OutOfBounds", 2),
    ));

    if let ResultStrategy::FixedOutputBuffer { bytes, .. } = plan.result_strategy {
        let output_index = plan.direct_params.len() - 1;
        body.push_str(&format!(
            "    const std::uint32_t output = static_cast<std::uint32_t>(slots[{output_index}].i32);\n    if (!state->memory.Contains(output, {bytes}u)) {{\n{error_return}    }}\n",
            output_index = output_index,
            bytes = bytes,
            error_return = render_error_return(plan, "Status::OutOfBounds", 2),
        ));
    }

    body.push_str(&format!("\n    {} query{{}};\n", function.query));
    let mut direct_slot = 0usize;
    for field in &function.inputs {
        if direct_type(&field.ty) {
            body.push_str(&format!(
                "    query.{field} = {expr};\n",
                field = field.name,
                expr = query_expr(&field.ty, direct_slot, &format!("query.{}", field.name)),
            ));
            direct_slot += 1;
        } else if matches!(field.ty, SemanticType::String | SemanticType::Bytes | SemanticType::List { .. }) {
            body.push_str(&render_variable_field(field, records, plan));
        } else {
            body.push_str(&render_wire_read(
                &field.ty,
                &format!("query.{}", field.name),
                records,
                "reader",
                1,
            ));
        }
    }
    body.push_str(&format!(
        "    if (!reader.Finish({descriptor_alignment}u)) {{\n{descriptor_error}    }}\n",
        descriptor_alignment = descriptor_alignment,
        descriptor_error = render_error_return(plan, "Status::InvalidArgument", 2),
    ));

    body.push_str(&format!(
        "    {} result{{}};\n    state->native->{api_member}->{function_name}(&query, &result);\n    const std::int32_t errorCode = NativeErrorCode(result.error);\n",
        function.result,
        api_member = api_member,
        function_name = function.name,
    ));

    match plan.result_strategy {
        ResultStrategy::Status => {
            body.push_str("    slots[0].i32 = errorCode;\n    return nullptr;\n");
        }
        ResultStrategy::Packed32 => {
            let field = &function.outputs[0];
            let value = packed32_expr(&field.ty, &format!("result.{}", field.name));
            body.push_str(&format!(
                "    slots[0].i64 = static_cast<std::int64_t>(PackU32({value}, errorCode));\n    return nullptr;\n",
                value = value,
            ));
        }
        ResultStrategy::FixedOutputBuffer { bytes, alignment } => {
            body.push_str(
                "    if (errorCode != 0) {\n        slots[0].i32 = errorCode;\n        return nullptr;\n    }\n",
            );
            body.push_str(&format!(
                "    std::array<std::uint8_t, {bytes}> wire{{}};\n    WireWriter writer(wire);\n",
                bytes = bytes,
            ));
            for field in &function.outputs {
                body.push_str(&render_wire_write(
                    &field.ty,
                    &format!("result.{}", field.name),
                    records,
                    1,
                ));
            }
            body.push_str(&format!(
                "    if (!writer.Finish({alignment}u))\n        return Trap(\"generated Core wire layout mismatch for {function_name}\");\n    if (!state->memory.Write(output, wire.data(), wire.size()))\n        return Trap(\"generated Core output range changed unexpectedly\");\n    slots[0].i32 = 0;\n    return nullptr;\n",
                alignment = alignment,
                function_name = function.name,
            ));
        }
        ResultStrategy::VariableOutputBuffer | ResultStrategy::Unsupported => unreachable!(),
    }
    body.push_str("}\n");
    body
}

fn render_variable_field(
    field: &FieldModel,
    records: &BTreeMap<String, RecordModel>,
    plan: &FunctionPlan,
) -> String {
    let stem = sanitize(&field.name);
    let mut output = format!(
        "    std::uint32_t {stem}Pointer = 0;\n    std::uint32_t {stem}Count = 0;\n    if (!reader.U32({stem}Pointer) || !reader.U32({stem}Count)) {{\n{error_return}    }}\n",
        stem = stem,
        error_return = render_error_return(plan, "Status::InvalidArgument", 2),
    );

    match &field.ty {
        SemanticType::String => {
            output.push_str(&format!(
                "    std::span<const std::uint8_t> {stem}Bytes;\n    if (!state->memory.View({stem}Pointer, {stem}Count, {stem}Bytes)) {{\n{range_error}    }}\n    std::string {stem}Storage(reinterpret_cast<const char*>({stem}Bytes.data()), {stem}Bytes.size());\n    query.{field_name} = {stem}Storage.c_str();\n",
                stem = stem,
                field_name = field.name,
                range_error = render_error_return(plan, "Status::OutOfBounds", 2),
            ));
        }
        SemanticType::Bytes => {
            let count = count_field(field).expect("eligible bytes input has count metadata");
            output.push_str(&format!(
                "    std::span<const std::uint8_t> {stem}Bytes;\n    if (!state->memory.View({stem}Pointer, {stem}Count, {stem}Bytes)) {{\n{range_error}    }}\n    std::vector<std::uint8_t> {stem}Storage({stem}Bytes.begin(), {stem}Bytes.end());\n    query.{field_name} = reinterpret_cast<std::remove_reference_t<decltype(query.{field_name})>>({stem}Storage.data());\n    if (!AssignCoreCount({stem}Count, query.{count})) {{\n{count_error}    }}\n",
                stem = stem,
                field_name = field.name,
                count = count,
                range_error = render_error_return(plan, "Status::OutOfBounds", 2),
                count_error = render_error_return(plan, "Status::InvalidArgument", 2),
            ));
        }
        SemanticType::List { element } if matches!(element.as_ref(), SemanticType::String) => {
            let count = count_field(field).expect("eligible string list has count metadata");
            output.push_str(&format!(
                "    const std::uint64_t {stem}DescriptorBytes64 = static_cast<std::uint64_t>({stem}Count) * 8u;\n    if ({stem}DescriptorBytes64 > std::numeric_limits<std::size_t>::max()) {{\n{count_error}    }}\n    std::span<const std::uint8_t> {stem}Wire;\n    if (!state->memory.View({stem}Pointer, static_cast<std::size_t>({stem}DescriptorBytes64), {stem}Wire)) {{\n{range_error}    }}\n    WireReader {stem}Reader({stem}Wire);\n    std::vector<std::string> {stem}Strings;\n    std::vector<const char*> {stem}Pointers;\n    {stem}Strings.reserve({stem}Count);\n    for (std::uint32_t coreIndex = 0; coreIndex < {stem}Count; ++coreIndex) {{\n        std::uint32_t itemPointer = 0;\n        std::uint32_t itemLength = 0;\n        if (!{stem}Reader.U32(itemPointer) || !{stem}Reader.U32(itemLength)) {{\n{item_error}        }}\n        std::span<const std::uint8_t> itemBytes;\n        if (!state->memory.View(itemPointer, itemLength, itemBytes)) {{\n{item_range_error}        }}\n        {stem}Strings.emplace_back(reinterpret_cast<const char*>(itemBytes.data()), itemBytes.size());\n    }}\n    if (!{stem}Reader.Finish(4)) {{\n{count_error}    }}\n    {stem}Pointers.reserve({stem}Strings.size());\n    for (const auto& item : {stem}Strings) {stem}Pointers.push_back(item.c_str());\n    query.{field_name} = {stem}Pointers.data();\n    if (!AssignCoreCount({stem}Count, query.{count})) {{\n{count_error}    }}\n",
                stem = stem,
                field_name = field.name,
                count = count,
                count_error = render_error_return(plan, "Status::InvalidArgument", 2),
                range_error = render_error_return(plan, "Status::OutOfBounds", 2),
                item_error = render_error_return(plan, "Status::InvalidArgument", 3),
                item_range_error = render_error_return(plan, "Status::OutOfBounds", 3),
            ));
        }
        SemanticType::List { element } => {
            let count = count_field(field).expect("eligible list has count metadata");
            let (element_bytes, element_alignment) = fixed_wire_layout(element, records)
                .expect("eligible list element has fixed wire layout");
            let cpp = native_cpp_type(element);
            output.push_str(&format!(
                "    const std::uint64_t {stem}Bytes64 = static_cast<std::uint64_t>({stem}Count) * {element_bytes}u;\n    if ({stem}Bytes64 > std::numeric_limits<std::size_t>::max()) {{\n{count_error}    }}\n    std::span<const std::uint8_t> {stem}Wire;\n    if (!state->memory.View({stem}Pointer, static_cast<std::size_t>({stem}Bytes64), {stem}Wire)) {{\n{range_error}    }}\n    WireReader {stem}Reader({stem}Wire);\n    std::vector<{cpp}> {stem}Storage;\n    {stem}Storage.reserve({stem}Count);\n    for (std::uint32_t coreIndex = 0; coreIndex < {stem}Count; ++coreIndex) {{\n        {cpp} item{{}};\n{item_read}        {stem}Storage.push_back(item);\n    }}\n    if (!{stem}Reader.Finish({element_alignment}u)) {{\n{count_error}    }}\n    query.{field_name} = {stem}Storage.data();\n    if (!AssignCoreCount({stem}Count, query.{count})) {{\n{count_error}    }}\n",
                stem = stem,
                element_bytes = element_bytes,
                element_alignment = element_alignment,
                cpp = cpp,
                field_name = field.name,
                count = count,
                item_read = render_wire_read(element, "item", records, &format!("{stem}Reader"), 2),
                count_error = render_error_return(plan, "Status::InvalidArgument", 2),
                range_error = render_error_return(plan, "Status::OutOfBounds", 2),
            ));
        }
        _ => unreachable!("non-variable field reached variable input renderer"),
    }
    output
}

fn render_error_return(plan: &FunctionPlan, status: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    match plan.result_strategy {
        ResultStrategy::Packed32 => format!(
            "{pad}slots[0].i64 = static_cast<std::int64_t>(PackU32(0, static_cast<std::int32_t>({status})));\n{pad}return nullptr;\n"
        ),
        _ => format!(
            "{pad}slots[0].i32 = static_cast<std::int32_t>({status});\n{pad}return nullptr;\n"
        ),
    }
}

fn native_cast(destination: &str, value: &str) -> String {
    format!(
        "static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>({value})"
    )
}

fn query_expr(ty: &SemanticType, slot: usize, destination: &str) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!("slots[{slot}].i32 != 0"),
            "f32" => format!("slots[{slot}].f32"),
            "f64" => format!("slots[{slot}].f64"),
            "i64" | "u64" | "isize" | "usize" => native_cast(destination, &format!("slots[{slot}].i64")),
            _ => native_cast(destination, &format!("slots[{slot}].i32")),
        },
        SemanticType::Enum { .. } => native_cast(destination, &format!("slots[{slot}].i32")),
        SemanticType::Handle { .. } => native_cast(destination, &format!("slots[{slot}].i64")),
        _ => unreachable!(),
    }
}

fn packed32_expr(ty: &SemanticType, value: &str) -> String {
    match ty {
        SemanticType::Scalar { name } if name == "f32" => {
            format!("std::bit_cast<std::uint32_t>({value})")
        }
        SemanticType::Scalar { name } if name == "bool" => {
            format!("static_cast<std::uint32_t>({value} ? 1u : 0u)")
        }
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } => {
            format!("static_cast<std::uint32_t>({value})")
        }
        _ => unreachable!(),
    }
}

fn render_wire_read(
    ty: &SemanticType,
    destination: &str,
    records: &BTreeMap<String, RecordModel>,
    reader: &str,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!(
                "{pad}if (!{reader}.Bool({destination})) return Trap(\"generated Core wire underflow\");\n"
            ),
            "f32" => format!(
                "{pad}if (!{reader}.F32({destination})) return Trap(\"generated Core wire underflow\");\n"
            ),
            "f64" => format!(
                "{pad}if (!{reader}.F64({destination})) return Trap(\"generated Core wire underflow\");\n"
            ),
            "i64" | "isize" => format!(
                "{pad}{{ std::int64_t coreRaw = 0; if (!{reader}.I64(coreRaw)) return Trap(\"generated Core wire underflow\"); {destination} = {cast}; }}\n",
                cast = native_cast(destination, "coreRaw"),
            ),
            "u64" | "usize" => format!(
                "{pad}{{ std::uint64_t coreRaw = 0; if (!{reader}.U64(coreRaw)) return Trap(\"generated Core wire underflow\"); {destination} = {cast}; }}\n",
                cast = native_cast(destination, "coreRaw"),
            ),
            "i8" | "i16" | "i32" => format!(
                "{pad}{{ std::int32_t coreRaw = 0; if (!{reader}.I32(coreRaw)) return Trap(\"generated Core wire underflow\"); {destination} = {cast}; }}\n",
                cast = native_cast(destination, "coreRaw"),
            ),
            _ => format!(
                "{pad}{{ std::uint32_t coreRaw = 0; if (!{reader}.U32(coreRaw)) return Trap(\"generated Core wire underflow\"); {destination} = {cast}; }}\n",
                cast = native_cast(destination, "coreRaw"),
            ),
        },
        SemanticType::Enum { .. } => format!(
            "{pad}{{ std::int32_t coreRaw = 0; if (!{reader}.I32(coreRaw)) return Trap(\"generated Core wire underflow\"); {destination} = {cast}; }}\n",
            cast = native_cast(destination, "coreRaw"),
        ),
        SemanticType::Handle { .. } => format!(
            "{pad}{{ std::uint64_t coreRaw = 0; if (!{reader}.U64(coreRaw)) return Trap(\"generated Core wire underflow\"); {destination} = {cast}; }}\n",
            cast = native_cast(destination, "coreRaw"),
        ),
        SemanticType::Record { name } => records[name]
            .fields
            .iter()
            .map(|field| {
                render_wire_read(
                    &field.ty,
                    &format!("{destination}.{}", field.name),
                    records,
                    reader,
                    indent,
                )
            })
            .collect::<String>(),
        SemanticType::FixedArray { element, length } => {
            let index = format!("coreReadIndex{indent}");
            let nested = render_wire_read(
                element,
                &format!("{destination}[{index}]"),
                records,
                reader,
                indent + 1,
            );
            format!(
                "{pad}for (std::size_t {index} = 0; {index} < {length}u; ++{index}) {{\n{nested}{pad}}}\n"
            )
        }
        _ => unreachable!(),
    }
}

fn render_wire_write(
    ty: &SemanticType,
    value: &str,
    records: &BTreeMap<String, RecordModel>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    match ty {
        SemanticType::Scalar { name } => {
            let method = match name.as_str() {
                "bool" => "Bool",
                "f32" => "F32",
                "f64" => "F64",
                "i64" | "isize" => "I64",
                "u64" | "usize" => "U64",
                "i8" | "i16" | "i32" => "I32",
                _ => "U32",
            };
            format!(
                "{pad}if (!writer.{method}({value})) return Trap(\"generated Core wire overflow\");\n"
            )
        }
        SemanticType::Enum { .. } => format!(
            "{pad}if (!writer.I32(static_cast<std::int32_t>({value}))) return Trap(\"generated Core wire overflow\");\n"
        ),
        SemanticType::Handle { .. } => format!(
            "{pad}if (!writer.U64(static_cast<std::uint64_t>({value}))) return Trap(\"generated Core wire overflow\");\n"
        ),
        SemanticType::Record { name } => records[name]
            .fields
            .iter()
            .map(|field| {
                render_wire_write(
                    &field.ty,
                    &format!("{value}.{}", field.name),
                    records,
                    indent,
                )
            })
            .collect::<String>(),
        SemanticType::FixedArray { element, length } => {
            let index = format!("coreWriteIndex{indent}");
            let nested = render_wire_write(
                element,
                &format!("{value}[{index}]"),
                records,
                indent + 1,
            );
            format!(
                "{pad}for (std::size_t {index} = 0; {index} < {length}u; ++{index}) {{\n{nested}{pad}}}\n"
            )
        }
        _ => unreachable!(),
    }
}

fn native_cpp_type(ty: &SemanticType) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i8" => "std::int8_t".to_owned(),
            "i16" => "std::int16_t".to_owned(),
            "i32" | "isize" => "std::int32_t".to_owned(),
            "i64" => "std::int64_t".to_owned(),
            "u8" | "char" => "std::uint8_t".to_owned(),
            "u16" => "std::uint16_t".to_owned(),
            "u32" => "std::uint32_t".to_owned(),
            "u64" | "usize" => "std::uint64_t".to_owned(),
            "f32" => "float".to_owned(),
            "f64" => "double".to_owned(),
            _ => "std::int32_t".to_owned(),
        },
        SemanticType::Enum { name } | SemanticType::Record { name } => name.clone(),
        SemanticType::Handle { family } => family.clone(),
        SemanticType::FixedArray { .. } => unreachable!("fixed arrays are not vector element C++ types"),
        _ => unreachable!("unsupported variable list element C++ type"),
    }
}

fn count_field(field: &FieldModel) -> Option<String> {
    field.metadata.iter().find_map(|metadata| {
        metadata
            .strip_prefix("count-field:")
            .map(ToString::to_string)
    })
}

fn render_registration(plan: &FunctionPlan, callback: &str) -> String {
    let params = kind_array("params", &plan.direct_params);
    let results = kind_array("results", &plan.direct_results);
    format!(
        "    {{\n{params}{results}        if (!DefineGeneratedVariable(linker, \"{module}\", \"{name}\",\n                MakeFuncType(params, {param_count}, results, {result_count}), {callback}, state, error))\n            return false;\n    }}\n",
        params = params,
        results = results,
        module = plan.import_module,
        name = plan.import_name,
        param_count = plan.direct_params.len(),
        result_count = plan.direct_results.len(),
        callback = callback,
    )
}

fn kind_array(name: &str, kinds: &[CoreType]) -> String {
    if kinds.is_empty() {
        return format!("        const wasm_valkind_t* {name} = nullptr;\n");
    }
    format!(
        "        const wasm_valkind_t {name}[] = {{{}}};\n",
        kinds
            .iter()
            .map(|kind| match kind {
                CoreType::I32 => "WASM_I32",
                CoreType::I64 => "WASM_I64",
                CoreType::F32 => "WASM_F32",
                CoreType::F64 => "WASM_F64",
            })
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn native_member(module: &str) -> String {
    match module {
        "camera" => "cameraApi".to_owned(),
        "sound" => "soundApi".to_owned(),
        other => other.to_lower_camel_case(),
    }
}

fn callback_name(module: &str, function: &str) -> String {
    format!(
        "CoreVariable_{}_{}",
        module.to_snake_case(),
        function.to_snake_case()
    )
}

fn sanitize(value: &str) -> String {
    value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() {
                character
            } else {
                '_'
            }
        })
        .collect()
}

fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records.entry(record.name.clone()).or_insert_with(|| record.clone());
        }
    }
    records
}
