//! Generated guest wire support for shared-scratch Core callins.

pub(super) fn render(macros: &str, count: usize) -> String {
    unsafe_export_attributes(format!(
        r#"// @generated by spring-api-codegen; do not edit.
// Shared-scratch Core callins. Invoke `export_callin_scratch!(BYTES)` exactly
// once in a guest that exports any generated variable-size callin.

#[doc(hidden)]
pub mod __core_callin_scratch_wire {{
    pub struct Reader<'a> {{
        bytes: &'a [u8],
        cursor: usize,
    }}

    pub struct FramedList<'a> {{
        reader: Reader<'a>,
        remaining: u32,
    }}

    impl<'a> Reader<'a> {{
        #[inline]
        pub fn new(bytes: &'a [u8]) -> Self {{ Self {{ bytes, cursor: 0 }} }}

        #[inline]
        fn align(&mut self, alignment: usize) -> Option<()> {{
            if alignment == 0 || !alignment.is_power_of_two() {{ return None; }}
            let aligned = self.cursor.checked_add(alignment - 1)? & !(alignment - 1);
            if aligned > self.bytes.len() {{ return None; }}
            self.cursor = aligned;
            Some(())
        }}

        #[inline]
        fn take(&mut self, count: usize, alignment: usize) -> Option<&'a [u8]> {{
            self.align(alignment)?;
            let end = self.cursor.checked_add(count)?;
            let value = self.bytes.get(self.cursor..end)?;
            self.cursor = end;
            Some(value)
        }}

        #[inline]
        pub fn u8(&mut self) -> Option<u8> {{ Some(*self.take(1, 1)?.first()?) }}
        #[inline]
        pub fn u32(&mut self) -> Option<u32> {{
            let b = self.take(4, 4)?;
            Some(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        }}
        #[inline]
        pub fn i32(&mut self) -> Option<i32> {{ Some(self.u32()? as i32) }}
        #[inline]
        pub fn u64(&mut self) -> Option<u64> {{
            let b = self.take(8, 8)?;
            Some(u64::from_le_bytes([b[0],b[1],b[2],b[3],b[4],b[5],b[6],b[7]]))
        }}
        #[inline]
        pub fn i64(&mut self) -> Option<i64> {{ Some(self.u64()? as i64) }}
        #[inline]
        pub fn f32(&mut self) -> Option<f32> {{ Some(f32::from_bits(self.u32()?)) }}
        #[inline]
        pub fn f64(&mut self) -> Option<f64> {{ Some(f64::from_bits(self.u64()?)) }}
        #[inline]
        pub fn boolean(&mut self) -> Option<bool> {{
            match self.u32()? {{ 0 => Some(false), 1 => Some(true), _ => None }}
        }}
        #[inline]
        pub fn bytes(&mut self) -> Option<&'a [u8]> {{
            let len = self.u32()? as usize;
            self.take(len, 1)
        }}
        #[inline]
        pub fn slice<T>(&mut self) -> Option<&'a [T]> {{
            let len = self.u32()? as usize;
            let bytes = len.checked_mul(core::mem::size_of::<T>())?;
            let raw = self.take(bytes, core::mem::align_of::<T>())?;
            if raw.as_ptr().align_offset(core::mem::align_of::<T>()) != 0 {{ return None; }}
            // SAFETY: the generator calls this only for integer/float primitive
            // representations, all bit patterns of which are valid. The host
            // writes canonical little-endian bytes and WebAssembly is little-endian.
            Some(unsafe {{ core::slice::from_raw_parts(raw.as_ptr().cast::<T>(), len) }})
        }}
        #[inline]
        pub fn framed_list(&mut self) -> Option<FramedList<'a>> {{
            let count = self.u32()?;
            let total_bytes = self.u32()? as usize;
            self.align(8)?;
            // The trusted host supplies the total span explicitly, so advancing
            // the outer reader is O(1). Individual length-framed records remain
            // bounds-checked lazily as the handler consumes the iterator.
            let frames = self.take(total_bytes, 1)?;
            Some(FramedList {{ reader: Reader::new(frames), remaining: count }})
        }}
        #[inline]
        pub fn finish(&self) -> bool {{ self.cursor == self.bytes.len() }}
    }}

    impl<'a> FramedList<'a> {{
        #[inline]
        pub fn remaining(&self) -> u32 {{ self.remaining }}
        #[inline]
        pub fn next_frame(&mut self) -> Option<&'a [u8]> {{
            if self.remaining == 0 {{ return None; }}
            let frame_len = self.reader.u32()? as usize;
            self.reader.align(8)?;
            let frame = self.reader.take(frame_len, 1)?;
            self.remaining -= 1;
            Some(frame)
        }}
    }}
}}

#[macro_export]
macro_rules! export_callin_scratch {{
    ($bytes:expr) => {{
        #[repr(align(8))]
        struct __SpringCoreCallinScratch([u8; $bytes]);
        static mut __SPRING_CORE_CALLIN_SCRATCH: __SpringCoreCallinScratch =
            __SpringCoreCallinScratch([0; $bytes]);

        #[doc(hidden)]
        pub fn __spring_core_callin_scratch_view(used: i32) -> Option<&'static [u8]> {{
            if used < 0 || used as usize > $bytes {{ return None; }}
            let pointer = unsafe {{ core::ptr::addr_of!(__SPRING_CORE_CALLIN_SCRATCH.0).cast::<u8>() }};
            // SAFETY: the host writes this guest-owned region only while entering
            // one callin, and the host rejects nested scratch callins.
            Some(unsafe {{ core::slice::from_raw_parts(pointer, used as usize) }})
        }}

        #[cfg(target_arch = "wasm32")]
        #[export_name = "spring:callin/scratch-info"]
        pub extern "C" fn __spring_core_callin_scratch_info() -> i64 {{
            let pointer = unsafe {{ core::ptr::addr_of!(__SPRING_CORE_CALLIN_SCRATCH.0).cast::<u8>() as usize }};
            debug_assert!(pointer <= u32::MAX as usize && $bytes <= u32::MAX as usize);
            ((($bytes as u64) << 32) | pointer as u32 as u64) as i64
        }}
    }};
}}

{macros}
#[doc(hidden)]
pub const __GENERATED_SCRATCH_CALLIN_COUNT: usize = {count};
"#,
        macros = macros,
        count = count,
    ))
}

fn unsafe_export_attributes(source: String) -> String {
    let mut output = String::with_capacity(source.len());
    for line in source.split_inclusive('\n') {
        let Some(start) = line.find("#[export_name = ") else {
            output.push_str(line);
            continue;
        };
        let mut line = line.to_owned();
        let attribute = "#[export_name = ";
        line.replace_range(start..start + attribute.len(), "#[unsafe(export_name = ");
        if let Some(close) = line.rfind(']') {
            line.insert(close, ')');
        }
        output.push_str(&line);
    }
    output
}
