//! Allocation-free Core-Wasm lowering for synchronous variable-input callouts.
//!
//! The NativeInterface query contract makes ordinary input pointers call-scoped.
//! This renderer therefore borrows validated guest memory directly for strings,
//! bytes and scalar/enum lists. Complex element records and list<string> remain
//! outside this renderer because their native layout requires adaptation.

use heck::{ToLowerCamelCase, ToSnakeCase};
use std::collections::{BTreeMap, BTreeSet};

use crate::model::{ApiModel, FieldModel, FunctionModel, RecordModel, SemanticType};
use crate::render_core_wasm::{self, CoreType, FunctionPlan, InputStrategy, ResultStrategy};

pub fn render_header() -> String {
    r#"/* @generated by spring-api-codegen; do not edit. */
#pragma once

#include <string>

#include "WasmInterface/WasmCoreBindings.h"

namespace recoil::wasm::core::generated {

bool RegisterGeneratedBorrowedImports(wasmtime_linker_t* linker, HostState* state,
    std::string& error);

} // namespace recoil::wasm::core::generated
"#
    .to_owned()
}

pub fn render_cpp(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = plan_index(model);
    let mut callbacks = String::new();
    let mut registrations = String::new();
    let mut count = 0usize;

    for module in &model.modules {
        for function in &module.functions {
            let Some(plan) = plans.get(&(module.name.clone(), function.name.clone())) else {
                continue;
            };
            if !eligible(plan, &function.inputs, &function.outputs, &records) {
                continue;
            }
            count += 1;
            callbacks.push_str(&render_callback(&module.name, function, plan, &records));
            callbacks.push('\n');
            registrations.push_str(&render_registration(
                plan,
                &callback_name(&module.name, &function.name),
            ));
        }
    }

    format!(
        r#"/* @generated by spring-api-codegen; do not edit. */

#include "wasm/generated/WasmCoreGeneratedBorrowedBindings.h"

#include <array>
#include <bit>
#include <cstdint>
#include <limits>
#include <span>
#include <string_view>
#include <type_traits>

#include "NativeInterface/NativeInterface.h"
#include "WasmInterface/WasmCoreAbi.h"
#include "WasmInterface/WasmCoreGeneratedSupport.h"
#include "WasmInterface/WasmCoreWire.h"

namespace recoil::wasm::core::generated {{
namespace {{

template<typename T>
bool AssignCoreBorrowedCount(std::uint32_t value, T& output)
{{
    using Native = std::remove_cv_t<std::remove_reference_t<T>>;
    if (static_cast<std::uint64_t>(value) >
        static_cast<std::uint64_t>(std::numeric_limits<Native>::max()))
        return false;
    output = static_cast<Native>(value);
    return true;
}}

bool DefineGeneratedBorrowed(wasmtime_linker_t* linker, const char* moduleName,
    const char* functionName, wasm_functype_t* type,
    wasmtime_func_unchecked_callback_t callback, HostState* state, std::string& error)
{{
    wasmtime_error_t* defineError = wasmtime_linker_define_func_unchecked(
        linker,
        moduleName, std::char_traits<char>::length(moduleName),
        functionName, std::char_traits<char>::length(functionName),
        type, callback, state, nullptr);
    wasm_functype_delete(type);
    if (defineError == nullptr)
        return true;
    error = ErrorMessage(defineError);
    return false;
}}

{callbacks}
}} // namespace

bool RegisterGeneratedBorrowedImports(wasmtime_linker_t* linker, HostState* state,
    std::string& error)
{{
    if (linker == nullptr || state == nullptr || state->native == nullptr) {{
        error = "cannot register borrowed Core imports without linker/host/native API";
        return false;
    }}
{registrations}
    return true;
}}

static_assert({count}u >= 0u, "generated borrowed Core callback count");

}} // namespace recoil::wasm::core::generated
"#,
        callbacks = callbacks,
        registrations = registrations,
        count = count,
    )
}

/// Production eligibility for the allocation-free borrowed variable-input class.
/// This intentionally rejects callbacks/opaque/manual APIs, list<string>, bool
/// lists, pointer-sized lists and record lists.
pub fn eligible(
    plan: &FunctionPlan,
    inputs: &[FieldModel],
    outputs: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    // A reviewed handwritten transport already owns this import.
    if crate::render_core_wasm_registry::handwritten_reviewed(&plan.module, &plan.function) {
        return false;
    }
    if matches!(plan.source_status.as_str(), "manual" | "unsupported")
        || !matches!(plan.input_strategy, InputStrategy::VariableInputBuffer)
    {
        return false;
    }
    if descriptor_layout(inputs, records).is_none()
        || !inputs
            .iter()
            .all(|field| borrowed_input_supported(field, records))
    {
        return false;
    }
    match plan.result_strategy {
        ResultStrategy::Status => true,
        ResultStrategy::Packed32 => {
            outputs.len() == 1
                && matches!(
                    outputs[0].ty,
                    SemanticType::Scalar { .. } | SemanticType::Enum { .. }
                )
        }
        ResultStrategy::FixedOutputBuffer { .. } => {
            outputs.iter().all(|field| fixed_wire_field(field, records))
        }
        ResultStrategy::VariableOutputBuffer | ResultStrategy::Unsupported => false,
    }
}

pub fn render_rust(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = plan_index(model);
    let mut modules = String::new();
    let mut total = 0usize;

    for module in &model.modules {
        let functions = module
            .functions
            .iter()
            .filter_map(|function| {
                let plan = plans.get(&(module.name.clone(), function.name.clone()))?;
                eligible(plan, &function.inputs, &function.outputs, &records)
                    .then_some((function, plan))
            })
            .collect::<Vec<_>>();
        if functions.is_empty() {
            continue;
        }
        total += functions.len();
        let module_ident = rust_ident(&module.name.to_snake_case());
        modules.push_str(&format!("    pub mod {module_ident} {{\n"));
        modules.push_str("        use crate::{ApiError, ErrorCode, Result};\n\n");
        modules.push_str("        #[cfg(target_arch = \"wasm32\")]\n        mod raw {\n");
        for (function, plan) in &functions {
            modules.push_str(&render_rust_raw(function, plan, 12));
        }
        modules.push_str("        }\n\n");
        for (function, plan) in &functions {
            modules.push_str(&render_rust_wrapper(function, plan, &records, 8));
            modules.push('\n');
        }
        modules.push_str("    }\n\n");
    }

    format!(
        "// @generated by spring-api-codegen; do not edit.\n\
         // Allocation-free borrowed variable-input Core wrappers live below a\n\
         // dedicated namespace so concatenating generated SDK fragments cannot\n\
         // create duplicate per-API module declarations.\n\n\
         pub mod borrowed {{\n{wire_helpers}\n{modules}\
         #[doc(hidden)]\n    pub const __GENERATED_BORROWED_CALLOUT_COUNT: usize = {total};\n\
         }}\n",
        wire_helpers = indent_block(RUST_DESCRIPTOR_HELPERS, 4),
        modules = modules,
        total = total,
    )
}

const RUST_DESCRIPTOR_HELPERS: &str = r#"#[doc(hidden)]
mod __core_borrowed_wire {
    #[inline]
    fn align(bytes: &mut [u8], cursor: &mut usize, alignment: usize) -> bool {
        if alignment == 0 || !alignment.is_power_of_two() {
            return false;
        }
        let Some(sum) = cursor.checked_add(alignment - 1) else { return false; };
        let aligned = sum & !(alignment - 1);
        if aligned > bytes.len() {
            return false;
        }
        bytes[*cursor..aligned].fill(0);
        *cursor = aligned;
        true
    }

    #[inline]
    pub fn put_u32(bytes: &mut [u8], cursor: &mut usize, value: u32) -> bool {
        if !align(bytes, cursor, 4) {
            return false;
        }
        let Some(end) = cursor.checked_add(4) else { return false; };
        let Some(target) = bytes.get_mut(*cursor..end) else { return false; };
        target.copy_from_slice(&value.to_le_bytes());
        *cursor = end;
        true
    }

    #[inline]
    pub fn put_pair(bytes: &mut [u8], cursor: &mut usize, ptr: u32, len: u32) -> bool {
        put_u32(bytes, cursor, ptr) && put_u32(bytes, cursor, len)
    }

    /// `option<string>`: the presence flag is followed by the pointer/length
    /// pair either way, so the descriptor keeps a fixed stride.
    #[inline]
    pub fn put_optional_pair(
        bytes: &mut [u8],
        cursor: &mut usize,
        value: Option<(u32, u32)>,
    ) -> bool {
        let (ptr, len) = value.unwrap_or((0, 0));
        put_u32(bytes, cursor, u32::from(value.is_some())) && put_pair(bytes, cursor, ptr, len)
    }

    #[inline]
    pub fn put_fixed(bytes: &mut [u8], cursor: &mut usize, value: &[u8], alignment: usize) -> bool {
        if !align(bytes, cursor, alignment) {
            return false;
        }
        let Some(end) = cursor.checked_add(value.len()) else { return false; };
        let Some(target) = bytes.get_mut(*cursor..end) else { return false; };
        target.copy_from_slice(value);
        *cursor = end;
        true
    }

    #[inline]
    pub fn finish(bytes: &mut [u8], cursor: &mut usize, alignment: usize) -> bool {
        align(bytes, cursor, alignment) && *cursor == bytes.len()
    }
}
"#;

fn indent_block(value: &str, spaces: usize) -> String {
    let pad = " ".repeat(spaces);
    value.lines().map(|line| format!("{pad}{line}\n")).collect()
}

fn borrowed_input_supported(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> bool {
    if direct_type(&field.ty) || fixed_wire_field(field, records) {
        return true;
    }
    match &field.ty {
        SemanticType::String => true,
        SemanticType::Bytes => count_field(field).is_some(),
        SemanticType::List { element } => {
            count_field(field).is_some() && borrowed_list_element(element)
        }
        // An absent optional string is a null native pointer, so only the
        // pointer-shaped payloads can carry one.
        SemanticType::Option { inner } => {
            presence_field(field).is_some() && matches!(inner.as_ref(), SemanticType::String)
        }
        _ => false,
    }
}

/// True for `option<string>`: a presence flag followed by the same borrowed
/// pointer/length pair a plain string uses.
fn optional_borrowed_string(field: &FieldModel) -> bool {
    matches!(&field.ty, SemanticType::Option { inner } if matches!(inner.as_ref(), SemanticType::String))
}

fn borrowed_list_element(ty: &SemanticType) -> bool {
    match ty {
        SemanticType::Scalar { name } => !matches!(name.as_str(), "bool" | "isize" | "usize"),
        SemanticType::Enum { .. } => true,
        _ => false,
    }
}

fn direct_type(ty: &SemanticType) -> bool {
    matches!(
        ty,
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. }
    )
}

fn presence_field(field: &FieldModel) -> Option<String> {
    field.metadata.iter().find_map(|metadata| {
        metadata
            .strip_prefix("presence-field:")
            .map(ToString::to_string)
    })
}

/// Field-aware fixed-wire test. `option<T>` is fixed-size on the descriptor --
/// a u32 presence flag plus an always-reserved payload -- but only the field
/// carries the presence metadata.
fn fixed_wire_field(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> bool {
    match &field.ty {
        SemanticType::Option { inner } => {
            presence_field(field).is_some() && fixed_wire_type(inner, records)
        }
        other => fixed_wire_type(other, records),
    }
}

fn fixed_wire_type(ty: &SemanticType, records: &BTreeMap<String, RecordModel>) -> bool {
    match ty {
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } | SemanticType::Handle { .. } => {
            true
        }
        SemanticType::FixedArray { element, length } => {
            *length <= 64 && fixed_wire_type(element, records)
        }
        SemanticType::Record { name } => records.get(name).is_some_and(|record| {
            record
                .fields
                .iter()
                .all(|field| fixed_wire_field(field, records))
        }),
        _ => false,
    }
}

fn fixed_wire_layout(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i64" | "u64" | "isize" | "usize" | "f64" => Some((8, 8)),
            _ => Some((4, 4)),
        },
        SemanticType::Enum { .. } => Some((4, 4)),
        SemanticType::Handle { .. } => Some((8, 8)),
        SemanticType::FixedArray { element, length } => {
            let (bytes, alignment) = fixed_wire_layout(element, records)?;
            Some((bytes.checked_mul(u32::try_from(*length).ok()?)?, alignment))
        }
        SemanticType::Record { name } => layout_fields(&records.get(name)?.fields, records),
        // Presence flag, payload at its own alignment, pair padded so a record
        // of options keeps a constant stride.
        SemanticType::Option { inner } => {
            let (payload_bytes, payload_alignment) = fixed_wire_layout(inner, records)?;
            let alignment = payload_alignment.max(4);
            let payload_offset = align_up(4, payload_alignment);
            Some((
                align_up(payload_offset.checked_add(payload_bytes)?, alignment),
                alignment,
            ))
        }
        _ => None,
    }
}

fn descriptor_field_layout(
    field: &FieldModel,
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    if matches!(
        field.ty,
        SemanticType::String | SemanticType::Bytes | SemanticType::List { .. }
    ) {
        Some((8, 4))
    } else if optional_borrowed_string(field) {
        // Presence flag plus the always-reserved pointer/length pair.
        Some((12, 4))
    } else {
        fixed_wire_layout(&field.ty, records)
    }
}

fn descriptor_layout(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    let mut bytes = 0u32;
    let mut alignment = 1u32;
    let mut any = false;
    for field in fields.iter().filter(|field| !direct_type(&field.ty)) {
        let (field_bytes, field_alignment) = descriptor_field_layout(field, records)?;
        bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
        alignment = alignment.max(field_alignment);
        any = true;
    }
    any.then(|| (align_up(bytes, alignment), alignment))
}

fn layout_fields(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<(u32, u32)> {
    let mut bytes = 0u32;
    let mut alignment = 1u32;
    for field in fields {
        let (field_bytes, field_alignment) = fixed_wire_layout(&field.ty, records)?;
        bytes = align_up(bytes, field_alignment).checked_add(field_bytes)?;
        alignment = alignment.max(field_alignment);
    }
    Some((align_up(bytes, alignment), alignment))
}

fn align_up(value: u32, alignment: u32) -> u32 {
    (value + alignment - 1) & !(alignment - 1)
}

fn render_callback(
    module_name: &str,
    function: &FunctionModel,
    plan: &FunctionPlan,
    records: &BTreeMap<String, RecordModel>,
) -> String {
    let callback = callback_name(module_name, &function.name);
    let api_member = native_member(module_name);
    let api_guard = native_guard(module_name);
    let slot_count = plan.direct_params.len().max(plan.direct_results.len());
    let direct_input_count = function
        .inputs
        .iter()
        .filter(|field| direct_type(&field.ty))
        .count();
    let descriptor_index = direct_input_count;
    let (descriptor_bytes, descriptor_alignment) =
        descriptor_layout(&function.inputs, records).expect("eligible borrowed descriptor layout");
    let mut body = format!(
        "wasm_trap_t* {callback}(void* environment, wasmtime_caller_t* caller,\n    wasmtime_val_raw_t* slots, std::size_t slotCount)\n{{\n    auto* state = static_cast<HostState*>(environment);\n    if (state == nullptr || state->native == nullptr || {api_guard} ||\n        state->native->{api_member}->{function_name} == nullptr)\n        return Trap(\"{function_name} borrowed Core binding is unavailable\");\n    if (slots == nullptr || slotCount != {slot_count}u)\n        return Trap(\"{function_name} borrowed Core ABI signature mismatch\");\n\n    std::string budgetError;\n    ImportGuard guard(state, {work}u, budgetError);\n    if (!guard.Ok()) return Trap(budgetError);\n\n    std::string memoryError;\n    if (!EnsureMemory(state, caller, memoryError)) return Trap(memoryError);\n    const std::uint32_t descriptor = static_cast<std::uint32_t>(slots[{descriptor_index}].i32);\n    std::span<const std::uint8_t> descriptorWire;\n    if (!state->memory.View(descriptor, {descriptor_bytes}u, descriptorWire)) {{\n{descriptor_error}    }}\n    WireReader reader(descriptorWire);\n",
        callback = callback,
        api_guard = api_guard,
        api_member = api_member,
        function_name = function.name,
        slot_count = slot_count,
        work = 1 + plan.direct_params.len(),
        descriptor_index = descriptor_index,
        descriptor_bytes = descriptor_bytes,
        descriptor_error = error_return(plan, "Status::OutOfBounds", 2),
    );

    if let ResultStrategy::FixedOutputBuffer { bytes, .. } = plan.result_strategy {
        let output_index = plan.direct_params.len() - 1;
        body.push_str(&format!(
            "    const std::uint32_t output = static_cast<std::uint32_t>(slots[{output_index}].i32);\n    if (!state->memory.Contains(output, {bytes}u)) {{\n{output_error}    }}\n",
            output_index = output_index,
            bytes = bytes,
            output_error = error_return(plan, "Status::OutOfBounds", 2),
        ));
    }

    body.push_str(&format!("\n    {} query{{}};\n", function.query));
    let mut direct_slot = 0usize;
    for field in &function.inputs {
        if direct_type(&field.ty) {
            body.push_str(&format!(
                "    query.{field} = {expr};\n",
                field = field.name,
                expr = query_expr(&field.ty, direct_slot, &format!("query.{}", field.name)),
            ));
            direct_slot += 1;
        } else if matches!(
            field.ty,
            SemanticType::String | SemanticType::Bytes | SemanticType::List { .. }
        ) {
            body.push_str(&render_borrowed_field(field, plan));
        } else if optional_borrowed_string(field) {
            body.push_str(&render_borrowed_optional_string(field, plan));
        } else {
            body.push_str(&render_wire_read_field(
                field,
                &format!("query.{}", field.name),
                "query",
                records,
                1,
            ));
        }
    }
    body.push_str(&format!(
        "    if (!reader.Finish({descriptor_alignment}u)) {{\n{descriptor_error}    }}\n",
        descriptor_alignment = descriptor_alignment,
        descriptor_error = error_return(plan, "Status::InvalidArgument", 2),
    ));

    body.push_str(&format!(
        "    {} result{{}};\n    state->native->{api_member}->{function_name}(&query, &result);\n    const std::int32_t errorCode = NativeErrorCode(result.error);\n",
        function.result,
        api_member = api_member,
        function_name = function.name,
    ));
    match plan.result_strategy {
        ResultStrategy::Status => {
            body.push_str("    slots[0].i32 = errorCode;\n    return nullptr;\n");
        }
        ResultStrategy::Packed32 => {
            let field = &function.outputs[0];
            body.push_str(&format!(
                "    slots[0].i64 = static_cast<std::int64_t>(PackU32({value}, errorCode));\n    return nullptr;\n",
                value = packed32_expr(&field.ty, &format!("result.{}", field.name)),
            ));
        }
        ResultStrategy::FixedOutputBuffer { bytes, alignment } => {
            body.push_str(
                "    if (errorCode != 0) { slots[0].i32 = errorCode; return nullptr; }\n",
            );
            body.push_str(&format!(
                "    std::array<std::uint8_t, {bytes}> wire{{}};\n    WireWriter writer(wire);\n"
            ));
            for field in &function.outputs {
                body.push_str(&render_wire_write_field(
                    field,
                    &format!("result.{}", field.name),
                    "result",
                    records,
                    1,
                ));
            }
            body.push_str(&format!(
                "    if (!writer.Finish({alignment}u)) return Trap(\"borrowed Core output layout mismatch\");\n    if (!state->memory.Write(output, wire.data(), wire.size())) return Trap(\"borrowed Core output range changed unexpectedly\");\n    slots[0].i32 = 0;\n    return nullptr;\n"
            ));
        }
        _ => unreachable!(),
    }
    body.push_str("}\n");
    body
}

/// `option<string>`: presence flag, then the same borrowed pointer/length pair a
/// plain string uses. The pair is read either way so the descriptor keeps a
/// fixed stride; an absent option leaves the native pointer null.
fn render_borrowed_optional_string(field: &FieldModel, plan: &FunctionPlan) -> String {
    let stem = sanitize(&field.name);
    let presence = presence_field(field).expect("eligible option has presence metadata");
    format!(
        "    bool {stem}Present = false;\n    std::uint32_t {stem}Pointer = 0;\n    std::uint32_t {stem}Count = 0;\n    if (!reader.Bool({stem}Present) || !reader.U32({stem}Pointer) || !reader.U32({stem}Count)) {{\n{invalid}    }}\n    query.{presence} = {stem}Present;\n    if (!{stem}Present) {{\n        query.{field_name} = nullptr;\n    }} else {{\n        if ({stem}Count == std::numeric_limits<std::uint32_t>::max()) {{\n{invalid_inner}        }}\n        std::span<const std::uint8_t> {stem}Bytes;\n        if (!state->memory.View({stem}Pointer, static_cast<std::size_t>({stem}Count) + 1u, {stem}Bytes)) {{\n{range}        }}\n        if ({stem}Bytes[{stem}Count] != 0) {{\n{invalid_inner}        }}\n        query.{field_name} = reinterpret_cast<const char*>({stem}Bytes.data());\n    }}\n",
        stem = stem,
        presence = presence,
        field_name = field.name,
        invalid = error_return(plan, "Status::InvalidArgument", 2),
        invalid_inner = error_return(plan, "Status::InvalidArgument", 3),
        range = error_return(plan, "Status::OutOfBounds", 3),
    )
}

fn render_borrowed_field(field: &FieldModel, plan: &FunctionPlan) -> String {
    let stem = sanitize(&field.name);
    let mut output = format!(
        "    std::uint32_t {stem}Pointer = 0;\n    std::uint32_t {stem}Count = 0;\n    if (!reader.U32({stem}Pointer) || !reader.U32({stem}Count)) {{\n{invalid}    }}\n",
        invalid = error_return(plan, "Status::InvalidArgument", 2),
    );
    match &field.ty {
        SemanticType::String => {
            output.push_str(&format!(
                "    if ({stem}Count == std::numeric_limits<std::uint32_t>::max()) {{\n{invalid}    }}\n    std::span<const std::uint8_t> {stem}Bytes;\n    if (!state->memory.View({stem}Pointer, static_cast<std::size_t>({stem}Count) + 1u, {stem}Bytes)) {{\n{range}    }}\n    if ({stem}Bytes[{stem}Count] != 0) {{\n{invalid}    }}\n    query.{field_name} = reinterpret_cast<const char*>({stem}Bytes.data());\n",
                field_name = field.name,
                invalid = error_return(plan, "Status::InvalidArgument", 2),
                range = error_return(plan, "Status::OutOfBounds", 2),
            ));
        }
        SemanticType::Bytes => {
            let count = count_field(field).expect("eligible borrowed bytes count");
            output.push_str(&format!(
                "    if ({stem}Count == 0) {{\n        query.{field_name} = nullptr;\n    }} else {{\n        std::span<const std::uint8_t> {stem}Bytes;\n        if (!state->memory.View({stem}Pointer, {stem}Count, {stem}Bytes)) {{\n{range}        }}\n        query.{field_name} = reinterpret_cast<std::remove_reference_t<decltype(query.{field_name})>>({stem}Bytes.data());\n    }}\n    if (!AssignCoreBorrowedCount({stem}Count, query.{count})) {{\n{invalid}    }}\n",
                field_name = field.name,
                range = error_return(plan, "Status::OutOfBounds", 3),
                invalid = error_return(plan, "Status::InvalidArgument", 2),
            ));
        }
        SemanticType::List { element } => {
            let count = count_field(field).expect("eligible borrowed list count");
            let cpp = native_cpp_type(element);
            let bytes = native_element_bytes(element);
            let align = bytes.min(8);
            output.push_str(&format!(
                "    if ({stem}Count == 0) {{\n        query.{field_name} = nullptr;\n    }} else {{\n        if constexpr (std::endian::native != std::endian::little) {{\n{unavailable}        }}\n        const std::uint64_t {stem}Bytes64 = static_cast<std::uint64_t>({stem}Count) * {bytes}u;\n        if ({stem}Bytes64 > std::numeric_limits<std::size_t>::max() || ({stem}Pointer % {align}u) != 0u) {{\n{invalid_inner}        }}\n        std::span<const std::uint8_t> {stem}Bytes;\n        if (!state->memory.View({stem}Pointer, static_cast<std::size_t>({stem}Bytes64), {stem}Bytes)) {{\n{range}        }}\n        static_assert(sizeof({cpp}) == {bytes}u, \"borrowed Core/native element width mismatch\");\n        query.{field_name} = reinterpret_cast<std::remove_reference_t<decltype(query.{field_name})>>({stem}Bytes.data());\n    }}\n    if (!AssignCoreBorrowedCount({stem}Count, query.{count})) {{\n{invalid}    }}\n",
                field_name = field.name,
                unavailable = error_return(plan, "Status::NotAvailable", 3),
                invalid_inner = error_return(plan, "Status::InvalidArgument", 3),
                invalid = error_return(plan, "Status::InvalidArgument", 2),
                range = error_return(plan, "Status::OutOfBounds", 3),
            ));
        }
        _ => unreachable!(),
    }
    output
}

fn query_expr(ty: &SemanticType, slot: usize, destination: &str) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!("slots[{slot}].i32 != 0"),
            "f32" => format!("slots[{slot}].f32"),
            "f64" => format!("slots[{slot}].f64"),
            "i64" | "u64" | "isize" | "usize" => {
                native_cast(destination, &format!("slots[{slot}].i64"))
            }
            _ => native_cast(destination, &format!("slots[{slot}].i32")),
        },
        SemanticType::Enum { .. } => native_cast(destination, &format!("slots[{slot}].i32")),
        SemanticType::Handle { .. } => native_cast(destination, &format!("slots[{slot}].i64")),
        _ => unreachable!(),
    }
}

fn native_cast(destination: &str, value: &str) -> String {
    format!(
        "static_cast<std::remove_cv_t<std::remove_reference_t<decltype({destination})>>>({value})"
    )
}

fn packed32_expr(ty: &SemanticType, value: &str) -> String {
    match ty {
        SemanticType::Scalar { name } if name == "f32" => {
            format!("std::bit_cast<std::uint32_t>({value})")
        }
        SemanticType::Scalar { name } if name == "bool" => {
            format!("static_cast<std::uint32_t>({value} ? 1u : 0u)")
        }
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } => {
            format!("static_cast<std::uint32_t>({value})")
        }
        _ => unreachable!(),
    }
}

/// Field-aware descriptor read; only a field carries option presence metadata.
fn render_wire_read_field(
    field: &FieldModel,
    destination: &str,
    owner: &str,
    records: &BTreeMap<String, RecordModel>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    match &field.ty {
        SemanticType::Option { inner } => {
            let presence = presence_field(field).expect("eligible option has presence metadata");
            let mut output = format!(
                "{pad}{{\n{pad}    bool corePresent = false;\n{pad}    if (!reader.Bool(corePresent)) return Trap(\"borrowed Core option presence underflow\");\n{pad}    {owner}.{presence} = corePresent;\n{pad}}}\n"
            );
            output.push_str(&render_wire_read(inner, destination, records, indent));
            output
        }
        other => render_wire_read(other, destination, records, indent),
    }
}

fn render_wire_read(
    ty: &SemanticType,
    destination: &str,
    records: &BTreeMap<String, RecordModel>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!(
                "{pad}if (!reader.Bool({destination})) return Trap(\"borrowed Core wire underflow\");\n"
            ),
            "f32" => format!(
                "{pad}if (!reader.F32({destination})) return Trap(\"borrowed Core wire underflow\");\n"
            ),
            "f64" => format!(
                "{pad}if (!reader.F64({destination})) return Trap(\"borrowed Core wire underflow\");\n"
            ),
            "i64" | "isize" => format!(
                "{pad}{{ std::int64_t coreRaw = 0; if (!reader.I64(coreRaw)) return Trap(\"borrowed Core wire underflow\"); {destination} = {cast}; }}\n",
                cast = native_cast(destination, "coreRaw"),
            ),
            "u64" | "usize" => format!(
                "{pad}{{ std::uint64_t coreRaw = 0; if (!reader.U64(coreRaw)) return Trap(\"borrowed Core wire underflow\"); {destination} = {cast}; }}\n",
                cast = native_cast(destination, "coreRaw"),
            ),
            "i8" | "i16" | "i32" => format!(
                "{pad}{{ std::int32_t coreRaw = 0; if (!reader.I32(coreRaw)) return Trap(\"borrowed Core wire underflow\"); {destination} = {cast}; }}\n",
                cast = native_cast(destination, "coreRaw"),
            ),
            _ => format!(
                "{pad}{{ std::uint32_t coreRaw = 0; if (!reader.U32(coreRaw)) return Trap(\"borrowed Core wire underflow\"); {destination} = {cast}; }}\n",
                cast = native_cast(destination, "coreRaw"),
            ),
        },
        SemanticType::Enum { .. } => format!(
            "{pad}{{ std::int32_t coreRaw = 0; if (!reader.I32(coreRaw)) return Trap(\"borrowed Core wire underflow\"); {destination} = {cast}; }}\n",
            cast = native_cast(destination, "coreRaw"),
        ),
        SemanticType::Handle { .. } => format!(
            "{pad}{{ std::uint64_t coreRaw = 0; if (!reader.U64(coreRaw)) return Trap(\"borrowed Core wire underflow\"); {destination} = {cast}; }}\n",
            cast = native_cast(destination, "coreRaw"),
        ),
        SemanticType::Record { name } => {
            let record = &records[name];
            let mut output = record
                .fields
                .iter()
                .map(|field| render_wire_read_field(
                    field,
                    &format!("{destination}.{}", field.name),
                    destination,
                    records,
                    indent,
                ))
                .collect::<String>();
            let (_, alignment) = fixed_wire_layout(ty, records)
                .expect("eligible borrowed record must have a wire layout");
            output.push_str(&format!(
                "{pad}if (!reader.Align({alignment}u)) return Trap(\"borrowed Core record alignment overflow\");\n"
            ));
            output
        }
        SemanticType::FixedArray { element, length } => {
            let index = format!("borrowedReadIndex{indent}");
            let nested = render_wire_read(element, &format!("{destination}[{index}]"), records, indent + 1);
            format!("{pad}for (std::size_t {index}=0; {index}<{length}u; ++{index}) {{\n{nested}{pad}}}\n")
        }
        _ => unreachable!(),
    }
}

fn render_wire_write_field(
    field: &FieldModel,
    value: &str,
    owner: &str,
    records: &BTreeMap<String, RecordModel>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    match &field.ty {
        SemanticType::Option { inner } => {
            let presence = presence_field(field).expect("eligible option has presence metadata");
            // The payload slot is always reserved so the record keeps a fixed
            // stride; an absent option writes a zeroed value of the same shape.
            let native = format!("std::remove_cv_t<std::remove_reference_t<decltype({value})>>");
            let mut output = format!(
                "{pad}if (!writer.Bool({owner}.{presence})) return Trap(\"borrowed Core option overflow\");\n{pad}if ({owner}.{presence}) {{\n"
            );
            output.push_str(&render_wire_write(inner, value, records, indent + 1));
            output.push_str(&format!(
                "{pad}}} else {{\n{pad}    {native} coreAbsent{{}};\n"
            ));
            output.push_str(&render_wire_write(inner, "coreAbsent", records, indent + 1));
            output.push_str(&format!("{pad}}}\n"));
            output
        }
        other => render_wire_write(other, value, records, indent),
    }
}

fn render_wire_write(
    ty: &SemanticType,
    value: &str,
    records: &BTreeMap<String, RecordModel>,
    indent: usize,
) -> String {
    let pad = "    ".repeat(indent);
    match ty {
        SemanticType::Scalar { name } => {
            let method = match name.as_str() {
                "bool" => "Bool", "f32" => "F32", "f64" => "F64",
                "i64" | "isize" => "I64", "u64" | "usize" => "U64",
                "i8" | "i16" | "i32" => "I32", _ => "U32",
            };
            format!("{pad}if (!writer.{method}({value})) return Trap(\"borrowed Core wire overflow\");\n")
        }
        SemanticType::Enum { .. } => format!("{pad}if (!writer.I32(static_cast<std::int32_t>({value}))) return Trap(\"borrowed Core wire overflow\");\n"),
        SemanticType::Handle { .. } => format!("{pad}if (!writer.U64(static_cast<std::uint64_t>({value}))) return Trap(\"borrowed Core wire overflow\");\n"),
        SemanticType::Record { name } => {
            let record = &records[name];
            let mut output = record
                .fields
                .iter()
                .map(|field| render_wire_write_field(
                    field,
                    &format!("{value}.{}", field.name),
                    value,
                    records,
                    indent,
                ))
                .collect::<String>();
            let (_, alignment) = fixed_wire_layout(ty, records)
                .expect("eligible borrowed record must have a wire layout");
            output.push_str(&format!(
                "{pad}if (!writer.Align({alignment}u)) return Trap(\"borrowed Core record alignment overflow\");\n"
            ));
            output
        }
        SemanticType::FixedArray { element, length } => {
            let index = format!("borrowedWriteIndex{indent}");
            let nested = render_wire_write(element, &format!("{value}[{index}]"), records, indent + 1);
            format!("{pad}for (std::size_t {index}=0; {index}<{length}u; ++{index}) {{\n{nested}{pad}}}\n")
        }
        _ => unreachable!(),
    }
}

fn render_registration(plan: &FunctionPlan, callback: &str) -> String {
    let params = kind_array("params", &plan.direct_params);
    let results = kind_array("results", &plan.direct_results);
    format!(
        "    {{\n{params}{results}        if (!DefineGeneratedBorrowed(linker, \"{module}\", \"{name}\",\n                MakeFuncType(params, {pc}, results, {rc}), {callback}, state, error))\n            return false;\n    }}\n",
        params = params,
        results = results,
        module = plan.import_module,
        name = plan.import_name,
        pc = plan.direct_params.len(),
        rc = plan.direct_results.len(),
        callback = callback,
    )
}

fn render_rust_raw(function: &FunctionModel, plan: &FunctionPlan, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let params = plan
        .direct_params
        .iter()
        .enumerate()
        .map(|(index, kind)| format!("arg{index}: {}", rust_core_type(*kind)))
        .collect::<Vec<_>>()
        .join(", ");
    let result = plan
        .direct_results
        .first()
        .map(|kind| format!(" -> {}", rust_core_type(*kind)))
        .unwrap_or_default();
    format!(
        "{pad}#[link(wasm_import_module = \"{module}\")]\n{pad}extern \"C\" {{\n{pad}    #[link_name = \"{name}\"]\n{pad}    pub fn {rust_name}({params}){result};\n{pad}}}\n",
        module = plan.import_module,
        name = plan.import_name,
        rust_name = rust_ident(&function.name.to_snake_case()),
    )
}

fn render_rust_wrapper(
    function: &FunctionModel,
    plan: &FunctionPlan,
    records: &BTreeMap<String, RecordModel>,
    indent: usize,
) -> String {
    let pad = " ".repeat(indent);
    let implicit_counts = implicit_count_fields(&function.inputs);
    let params = function
        .inputs
        .iter()
        .filter(|field| !implicit_counts.contains(&field.name))
        .map(|field| {
            format!(
                "{}: {}",
                rust_ident(&field.name.to_snake_case()),
                rust_input_type(field, records)
            )
        })
        .collect::<Vec<_>>();
    let return_type = rust_result_type(&function.outputs, plan, records);
    let (descriptor_bytes, descriptor_alignment) =
        descriptor_layout(&function.inputs, records).expect("eligible borrowed Rust descriptor");
    let mut descriptor = format!(
        "{pad}    let mut descriptor = [0u8; {descriptor_bytes}];\n{pad}    let mut cursor = 0usize;\n"
    );
    for field in function
        .inputs
        .iter()
        .filter(|field| !direct_type(&field.ty))
    {
        let name = rust_ident(&field.name.to_snake_case());
        if matches!(
            field.ty,
            SemanticType::String | SemanticType::Bytes | SemanticType::List { .. }
        ) {
            let (ptr, len) = rust_borrowed_parts(&field.ty, &name);
            descriptor.push_str(&format!(
                "{pad}    let core_ptr = {ptr};\n{pad}    let core_len = {len};\n{pad}    debug_assert!(core_ptr <= u32::MAX as usize && core_len <= u32::MAX as usize);\n{pad}    if !super::__core_borrowed_wire::put_pair(&mut descriptor, &mut cursor, core_ptr as u32, core_len as u32) {{ return Err(ApiError::new(ErrorCode::Internal as i32)); }}\n"
            ));
        } else if optional_borrowed_string(field) {
            descriptor.push_str(&format!(
                "{pad}    let core_optional = {name}.map(|core_value| {{\n{pad}        let core_bytes = core_value.to_bytes();\n{pad}        (core_value.as_ptr() as usize as u32, core_bytes.len() as u32)\n{pad}    }});\n{pad}    if !super::__core_borrowed_wire::put_optional_pair(&mut descriptor, &mut cursor, core_optional) {{ return Err(ApiError::new(ErrorCode::Internal as i32)); }}\n"
            ));
            continue;
        } else {
            let (bytes, alignment) = fixed_wire_layout(&field.ty, records)
                .expect("eligible borrowed fixed descriptor field");
            descriptor.push_str(&format!(
                "{pad}    debug_assert_eq!({name}.len(), {bytes}usize);\n{pad}    if !super::__core_borrowed_wire::put_fixed(&mut descriptor, &mut cursor, {name}, {alignment}usize) {{ return Err(ApiError::new(ErrorCode::Internal as i32)); }}\n"
            ));
        }
    }
    descriptor.push_str(&format!(
        "{pad}    if !super::__core_borrowed_wire::finish(&mut descriptor, &mut cursor, {descriptor_alignment}usize) {{ return Err(ApiError::new(ErrorCode::Internal as i32)); }}\n"
    ));
    let descriptor_ptr = "descriptor.as_ptr() as usize";
    let mut raw_args = Vec::new();
    for field in function
        .inputs
        .iter()
        .filter(|field| direct_type(&field.ty))
    {
        if let Some(owner) = count_owner(&function.inputs, &field.name) {
            let owner_name = rust_ident(&owner.name.to_snake_case());
            raw_args.push(format!(
                "{} as {}",
                rust_borrowed_len(&owner.ty, &owner_name),
                rust_core_type(plan.direct_params[raw_args.len()])
            ));
        } else {
            // The Core signature is the authority on the wire type. Guest-facing
            // parameters keep their semantic Rust type (u32 counts, bool flags,
            // handles), so each one is converted to the declared Core type here
            // rather than relying on them happening to match.
            raw_args.push(format!(
                "({}) as {}",
                rust_direct_arg(&field.ty, &rust_ident(&field.name.to_snake_case())),
                rust_core_type(plan.direct_params[raw_args.len()])
            ));
        }
    }
    raw_args.push(format!("({descriptor_ptr}) as u32 as i32"));
    if matches!(
        plan.result_strategy,
        ResultStrategy::FixedOutputBuffer { .. }
    ) {
        raw_args.push("output.as_mut_ptr() as usize as u32 as i32".to_owned());
    }
    let raw_call = format!(
        "raw::{}({})",
        rust_ident(&function.name.to_snake_case()),
        raw_args.join(", ")
    );

    let wasm_body = match plan.result_strategy {
        ResultStrategy::Status => format!(
            "{descriptor}{pad}    let status = unsafe {{ {raw_call} }};\n{pad}    if status == 0 {{ Ok(()) }} else {{ Err(ApiError::new(status)) }}"
        ),
        ResultStrategy::Packed32 => format!(
            "{descriptor}{pad}    let packed = unsafe {{ {raw_call} }} as u64;\n{pad}    let status = (packed >> 32) as u32 as i32;\n{pad}    if status != 0 {{ return Err(ApiError::new(status)); }}\n{pad}    {}",
            rust_unpack_packed(&function.outputs[0].ty, "packed")
        ),
        ResultStrategy::FixedOutputBuffer { bytes, .. } => format!(
            "{pad}    let mut output = [0u8; {bytes}];\n{descriptor}{pad}    let status = unsafe {{ {raw_call} }};\n{pad}    if status != 0 {{ return Err(ApiError::new(status)); }}\n{pad}    Ok(output)"
        ),
        _ => unreachable!(),
    };

    let non_wasm_uses = params
        .iter()
        .map(|parameter| parameter.split(':').next().unwrap().trim())
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{pad}#[inline]\n{pad}pub fn {name}({params}) -> {return_type} {{\n{pad}    #[cfg(target_arch = \"wasm32\")]\n{pad}    {{\n{wasm_body}\n{pad}    }}\n{pad}    #[cfg(not(target_arch = \"wasm32\"))]\n{pad}    {{\n{pad}        let _ = ({non_wasm_uses});\n{pad}        Err(ApiError::new(ErrorCode::UnsupportedHostTarget as i32))\n{pad}    }}\n{pad}}}\n",
        name = rust_ident(&function.name.to_snake_case()),
        params = params.join(", "),
        return_type = return_type,
        wasm_body = wasm_body,
    )
}

fn rust_input_type(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> String {
    if optional_borrowed_string(field) {
        return "Option<&core::ffi::CStr>".to_owned();
    }
    match &field.ty {
        SemanticType::String => "&core::ffi::CStr".to_owned(),
        SemanticType::Bytes => "&[u8]".to_owned(),
        SemanticType::List { element } => format!("&[{}]", rust_list_element_type(element)),
        SemanticType::Scalar { name } => rust_scalar_type(name).to_owned(),
        SemanticType::Enum { .. } => "i32".to_owned(),
        SemanticType::Handle { .. } => "u64".to_owned(),
        other => {
            let (bytes, _) =
                fixed_wire_layout(other, records).expect("eligible borrowed fixed Rust input");
            format!("&[u8; {bytes}]")
        }
    }
}

fn rust_result_type(
    outputs: &[FieldModel],
    plan: &FunctionPlan,
    _records: &BTreeMap<String, RecordModel>,
) -> String {
    match plan.result_strategy {
        ResultStrategy::Status => "Result<()>".to_owned(),
        ResultStrategy::Packed32 => match &outputs[0].ty {
            SemanticType::Scalar { name } => format!("Result<{}>", rust_scalar_type(name)),
            SemanticType::Enum { .. } => "Result<i32>".to_owned(),
            _ => unreachable!(),
        },
        ResultStrategy::FixedOutputBuffer { bytes, .. } => format!("Result<[u8; {bytes}]>"),
        _ => unreachable!(),
    }
}

fn rust_borrowed_parts(ty: &SemanticType, name: &str) -> (String, String) {
    match ty {
        SemanticType::String => (
            format!("{name}.as_ptr() as usize"),
            format!("{name}.to_bytes().len()"),
        ),
        SemanticType::Bytes | SemanticType::List { .. } => (
            format!("if {name}.is_empty() {{ 0usize }} else {{ {name}.as_ptr() as usize }}"),
            format!("{name}.len()"),
        ),
        _ => unreachable!(),
    }
}

fn rust_borrowed_len(ty: &SemanticType, name: &str) -> String {
    match ty {
        SemanticType::String => format!("{name}.to_bytes().len()"),
        SemanticType::Bytes | SemanticType::List { .. } => format!("{name}.len()"),
        _ => "0".to_owned(),
    }
}

fn rust_direct_arg(ty: &SemanticType, name: &str) -> String {
    match ty {
        SemanticType::Scalar { name: scalar } if scalar == "bool" => {
            format!("if {name} {{ 1 }} else {{ 0 }}")
        }
        SemanticType::Enum { .. } => name.to_owned(),
        SemanticType::Handle { .. } => format!("{name} as i64"),
        _ => name.to_owned(),
    }
}

fn rust_unpack_packed(ty: &SemanticType, packed: &str) -> String {
    match ty {
        SemanticType::Scalar { name } if name == "bool" => format!("Ok(({packed} as u32) != 0)"),
        SemanticType::Scalar { name } if name == "f32" => {
            format!("Ok(f32::from_bits({packed} as u32))")
        }
        SemanticType::Scalar { name } => {
            format!("Ok(({packed} as u32) as {})", rust_scalar_type(name))
        }
        SemanticType::Enum { .. } => format!("Ok(({packed} as u32) as i32)"),
        _ => unreachable!(),
    }
}

fn rust_list_element_type(ty: &SemanticType) -> String {
    match ty {
        SemanticType::Scalar { name } => rust_scalar_type(name).to_owned(),
        SemanticType::Enum { .. } => "i32".to_owned(),
        _ => unreachable!(),
    }
}

fn rust_scalar_type(name: &str) -> &'static str {
    match name {
        "bool" => "bool",
        "i8" => "i8",
        "i16" => "i16",
        "i32" => "i32",
        "i64" => "i64",
        "u8" | "char" => "u8",
        "u16" => "u16",
        "u32" => "u32",
        "u64" => "u64",
        "isize" => "isize",
        "usize" => "usize",
        "f32" => "f32",
        "f64" => "f64",
        _ => "i32",
    }
}

fn rust_core_type(kind: CoreType) -> &'static str {
    match kind {
        CoreType::I32 => "i32",
        CoreType::I64 => "i64",
        CoreType::F32 => "f32",
        CoreType::F64 => "f64",
    }
}

fn native_cpp_type(ty: &SemanticType) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i8" => "std::int8_t",
            "i16" => "std::int16_t",
            "i32" => "std::int32_t",
            "i64" => "std::int64_t",
            "u8" | "char" => "std::uint8_t",
            "u16" => "std::uint16_t",
            "u32" => "std::uint32_t",
            "u64" => "std::uint64_t",
            "f32" => "float",
            "f64" => "double",
            other => panic!("unsupported borrowed scalar {other}"),
        }
        .to_owned(),
        SemanticType::Enum { name } => name.clone(),
        _ => unreachable!(),
    }
}

fn native_element_bytes(ty: &SemanticType) -> u32 {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "i8" | "u8" | "char" => 1,
            "i16" | "u16" => 2,
            "i32" | "u32" | "f32" => 4,
            "i64" | "u64" | "f64" => 8,
            _ => unreachable!(),
        },
        SemanticType::Enum { .. } => 4,
        _ => unreachable!(),
    }
}

fn implicit_count_fields(inputs: &[FieldModel]) -> BTreeSet<String> {
    inputs.iter().filter_map(count_field).collect()
}

fn count_owner<'a>(inputs: &'a [FieldModel], count_name: &str) -> Option<&'a FieldModel> {
    inputs
        .iter()
        .find(|field| count_field(field).as_deref() == Some(count_name))
}

fn count_field(field: &FieldModel) -> Option<String> {
    field.metadata.iter().find_map(|metadata| {
        metadata
            .strip_prefix("count-field:")
            .map(ToString::to_string)
    })
}

fn error_return(plan: &FunctionPlan, status: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    if matches!(plan.result_strategy, ResultStrategy::Packed32) {
        format!("{pad}slots[0].i64 = static_cast<std::int64_t>(PackU32(0, static_cast<std::int32_t>({status})));\n{pad}return nullptr;\n")
    } else {
        format!("{pad}slots[0].i32 = static_cast<std::int32_t>({status});\n{pad}return nullptr;\n")
    }
}

fn kind_array(name: &str, kinds: &[CoreType]) -> String {
    if kinds.is_empty() {
        return format!("        const wasm_valkind_t* {name} = nullptr;\n");
    }
    format!(
        "        const wasm_valkind_t {name}[] = {{{}}};\n",
        kinds
            .iter()
            .map(|kind| match kind {
                CoreType::I32 => "WASM_I32",
                CoreType::I64 => "WASM_I64",
                CoreType::F32 => "WASM_F32",
                CoreType::F64 => "WASM_F64",
            })
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn native_member(module: &str) -> String {
    spring_native_codegen::render_host::core_native_member(module)
        .unwrap_or_else(|| panic!("no NativeInterface member mapped for module {module}"))
}

fn native_guard(module: &str) -> String {
    spring_native_codegen::render_host::core_native_guard(module)
        .unwrap_or_else(|| panic!("no NativeInterface member mapped for module {module}"))
}

fn callback_name(module: &str, function: &str) -> String {
    format!(
        "CoreBorrowed_{}_{}",
        module.to_snake_case(),
        function.to_snake_case()
    )
}

fn sanitize(value: &str) -> String {
    value
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

fn rust_ident(value: &str) -> String {
    match value {
        "move" | "type" | "match" | "loop" | "ref" | "self" | "crate" | "super" | "where" => {
            format!("r#{value}")
        }
        _ => value.to_owned(),
    }
}

fn plan_index(model: &ApiModel) -> BTreeMap<(String, String), FunctionPlan> {
    render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect()
}

fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records
                .entry(record.name.clone())
                .or_insert_with(|| record.clone());
        }
    }
    records
}
