//! Safe guest façade for reviewed variable-input/variable-output callouts.
//!
//! The transport uses descriptors internally because Wasm imports can only
//! receive scalar values.  This module deliberately keeps that representation
//! below the generated SDK boundary: callers work with Rust slices, strings,
//! and owned results.

pub fn render() -> String {
    r#"// @generated by spring-api-codegen; do not edit.

#[cfg(feature = "alloc")]
pub mod variable_io {
    pub mod unit_script {
        use core::convert::TryFrom;
        use alloc::vec;

        #[cfg(target_arch = "wasm32")]
        mod raw {
            #[link(wasm_import_module = "spring:unit-script")]
            unsafe extern "C" {
                #[link_name = "call-unit-script"]
                pub safe fn call(unit_id: i32, ret_capacity: i32, input: i32, output: i32) -> i32;
            }
        }

        /// Invoke a numeric Lua unit-script function.
        ///
        /// The engine keeps the original Lua `CallAsUnit` semantics.  This
        /// Rust façade intentionally exposes the portable numeric subset used
        /// by unit scripts, while retaining the Lua API for arbitrary values.
        #[inline]
        pub fn call_unit_script(
            unit_id: i32,
            function_name: &str,
            args: &[f32],
            ret_capacity: usize,
        ) -> crate::Result<crate::generated::owned::unit_script::CallUnitScriptValue> {
            let ret_capacity = i32::try_from(ret_capacity)
                .map_err(|_| crate::ApiError::new(crate::ErrorCode::InvalidArgument as i32))?;
            let (function_name_pointer, function_name_length) =
                crate::wasm_slice_parts(function_name.as_bytes())?;
            let (args_pointer, args_length) = crate::wasm_slice_parts(args)?;
            let mut input = [
                function_name_pointer as u32,
                function_name_length as u32,
                args_pointer as u32,
                args_length as u32,
            ];
            let input_pointer = crate::wasm_output_ptr(&mut input)?;
            let mut ret_values = vec![0.0f32; ret_capacity as usize];

            loop {
                let (ret_pointer, capacity) = crate::wasm_mut_slice_parts(&mut ret_values)?;
                let mut output = [
                    ret_pointer as u32,
                    capacity as u32,
                    0u32,
                    0u32,
                    0u32,
                ];
                let output_pointer = crate::wasm_output_ptr(&mut output)?;
                let status = raw::call(
                    unit_id,
                    capacity,
                    input_pointer,
                    output_pointer,
                );
                let required = output[2] as usize;
                if status == crate::ErrorCode::BufferOverflow as i32 {
                    ret_values.resize(required, 0.0);
                    continue;
                }
                if status != 0 {
                    return Err(crate::ApiError::new(status));
                }
                ret_values.truncate(required);
                return Ok(crate::generated::owned::unit_script::CallUnitScriptValue {
                    function_found: output[3] != 0,
                    success: output[4] != 0,
                    ret_values,
                });
            }
        }
    }
}
"#
    .to_owned()
}

#[cfg(test)]
mod tests {
    use super::render;

    #[test]
    fn unit_script_wrapper_exposes_a_typed_safe_boundary() {
        let output = render();
        assert!(output.contains("pub fn call_unit_script("));
        assert!(output.contains("function_name: &str"));
        assert!(output.contains("args: &[f32]"));
        assert!(output.contains("ret_capacity: usize"));
        assert!(output.contains("ret_values.resize(required, 0.0)"));
        assert!(!output.contains("pub unsafe fn call_unit_script"));
    }
}
