//! Generate Core-Wasm host callbacks for calls that have both variable-size
//! input and caller-owned variable-size output. Input and output descriptors
//! are separate wasm32 pointers so guest wrappers can prepare/retry outputs
//! without rebuilding input payloads.
//!
//! The input-side lowering here is the shared one: the dynamic-output renderer
//! reuses `input_descriptor_layout`, `input_field_supported`,
//! `render_input_variable` and `render_wire_read` so a variable input is read
//! exactly the same way whichever result transport pairs with it.
//!
//! Variable input follows the same synchronous lifetime rule as the dedicated
//! borrowed renderer: bytes and native-width numeric/enum lists borrow validated
//! guest memory for the duration of the NativeInterface call. Shapes whose wire
//! representation is not the native representation are adapted explicitly.

use heck::ToSnakeCase;
use std::collections::BTreeMap;

use crate::model::{ApiModel, FieldModel, RecordModel, SemanticType};
use crate::render_core_wasm::{self, CoreType, FunctionPlan, InputStrategy, ResultStrategy};
use crate::render_core_wasm_wire::{
    align_up, borrowed_element_bytes, borrowed_list_element, count_field, direct_type,
    fixed_wire_field, fixed_wire_layout, fixed_wire_type, input_descriptor_layout,
    input_field_supported, layout_fields, native_cast, native_cpp_type, optional_string,
    presence_field, render_input_variable, render_wire_read_field, render_wire_write,
    render_wire_write_field, sanitize, variable_type, OutputLayout,
};

pub fn render_header() -> String {
    r#"/* @generated by spring-api-codegen; do not edit. */
#pragma once

#include <string>

#include "WasmInterface/WasmCoreBindings.h"

namespace recoil::wasm::core::generated {

bool RegisterGeneratedVariableIoImports(wasmtime_linker_t* linker, HostState* state,
    std::string& error);

} // namespace recoil::wasm::core::generated
"#
    .to_owned()
}

pub fn render_cpp(model: &ApiModel) -> String {
    let records = record_index(model);
    let plans = render_core_wasm::plan(model)
        .functions
        .into_iter()
        .map(|plan| ((plan.module.clone(), plan.function.clone()), plan))
        .collect::<BTreeMap<_, _>>();
    let mut callbacks = String::new();
    let mut registrations = String::new();
    let mut generated_count = 0usize;

    for module in &model.modules {
        for function in &module.functions {
            let Some(plan) = plans.get(&(module.name.clone(), function.name.clone())) else {
                continue;
            };
            if !eligible(plan, &function.inputs, &function.outputs, &records) {
                continue;
            }
            generated_count += 1;
            callbacks.push_str(&render_callback(&module.name, function, plan, &records));
            callbacks.push('\n');
            registrations.push_str(&render_registration(
                plan,
                &callback_name(&module.name, &function.name),
            ));
        }
    }

    format!(
        r#"/* @generated by spring-api-codegen; do not edit. */

#include "wasm/generated/WasmCoreGeneratedVariableIoBindings.h"

#include <array>
#include <bit>
#include <cstdint>
#include <limits>
#include <span>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

#include "NativeInterface/NativeInterface.h"
#include "WasmInterface/WasmCoreAbi.h"
#include "WasmInterface/WasmCoreGeneratedSupport.h"
#include "WasmInterface/WasmCoreWire.h"

namespace recoil::wasm::core::generated {{
namespace {{

template<typename T>
bool AssignCoreCount(std::uint32_t value, T& output)
{{
    using Native = std::remove_cv_t<std::remove_reference_t<T>>;
    static_assert(std::is_integral_v<Native>);
    if (static_cast<std::uint64_t>(value) >
        static_cast<std::uint64_t>(std::numeric_limits<Native>::max()))
        return false;
    output = static_cast<Native>(value);
    return true;
}}

bool WriteCoreU32(std::span<std::uint8_t> bytes, std::size_t offset, std::uint32_t value)
{{
    if (offset > bytes.size() || bytes.size() - offset < 4)
        return false;
    bytes[offset + 0] = static_cast<std::uint8_t>(value);
    bytes[offset + 1] = static_cast<std::uint8_t>(value >> 8);
    bytes[offset + 2] = static_cast<std::uint8_t>(value >> 16);
    bytes[offset + 3] = static_cast<std::uint8_t>(value >> 24);
    return true;
}}

bool DefineGeneratedVariableIo(wasmtime_linker_t* linker, const char* moduleName,
    const char* functionName, wasm_functype_t* type,
    wasmtime_func_unchecked_callback_t callback, HostState* state, std::string& error)
{{
    wasmtime_error_t* defineError = wasmtime_linker_define_func_unchecked(
        linker,
        moduleName, std::char_traits<char>::length(moduleName),
        functionName, std::char_traits<char>::length(functionName),
        type, callback, state, nullptr);
    wasm_functype_delete(type);
    if (defineError == nullptr)
        return true;
    error = ErrorMessage(defineError);
    return false;
}}

{callbacks}
}} // namespace

bool RegisterGeneratedVariableIoImports(wasmtime_linker_t* linker, HostState* state,
    std::string& error)
{{
    if (linker == nullptr || state == nullptr || state->native == nullptr) {{
        error = "cannot register generated variable-I/O Core imports without linker/host/native API";
        return false;
    }}
{registrations}
    return true;
}}

static_assert({generated_count} >= 0, "generated variable-I/O Core callback count");

}} // namespace recoil::wasm::core::generated
"#,
        callbacks = callbacks,
        registrations = registrations,
        generated_count = generated_count,
    )
}

pub(crate) fn eligible(
    plan: &FunctionPlan,
    inputs: &[FieldModel],
    outputs: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    // A reviewed handwritten transport already owns this import.
    if crate::render_core_wasm_registry::handwritten_reviewed(&plan.module, &plan.function) {
        return false;
    }
    if matches!(plan.source_status.as_str(), "manual" | "unsupported")
        || !matches!(plan.input_strategy, InputStrategy::VariableInputBuffer)
        || !matches!(plan.result_strategy, ResultStrategy::VariableOutputBuffer)
    {
        return false;
    }
    input_descriptor_layout(inputs, records).is_some()
        && inputs
            .iter()
            .all(|field| input_field_supported(field, records))
        && output_descriptor_layout(outputs, records).is_some()
        && outputs
            .iter()
            .all(|field| output_field_supported(field, records))
        && outputs.iter().any(|field| variable_type(&field.ty))
}

fn output_field_supported(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> bool {
    match &field.ty {
        SemanticType::String => true,
        SemanticType::Bytes => count_field(field).is_some(),
        SemanticType::List { element } => {
            count_field(field).is_some() && output_list_element_supported(element, records)
        }
        _ => fixed_wire_field(field, records),
    }
}

fn output_list_element_supported(
    ty: &SemanticType,
    records: &BTreeMap<String, RecordModel>,
) -> bool {
    match ty {
        SemanticType::Scalar { name } if !matches!(name.as_str(), "bool" | "isize" | "usize") => {
            true
        }
        SemanticType::Enum { .. } => true,
        SemanticType::Record { .. } => fixed_wire_type(ty, records),
        _ => false,
    }
}

fn output_descriptor_layout(
    fields: &[FieldModel],
    records: &BTreeMap<String, RecordModel>,
) -> Option<OutputLayout> {
    let variable_count = fields
        .iter()
        .filter(|field| variable_type(&field.ty))
        .count();
    let header_bytes = u32::try_from(variable_count).ok()?.checked_mul(12)?;
    let fixed = fields
        .iter()
        .filter(|field| !variable_type(&field.ty))
        .cloned()
        .collect::<Vec<_>>();
    let (fixed_bytes, fixed_alignment) = if fixed.is_empty() {
        (0, 1)
    } else {
        layout_fields(&fixed, records)?
    };
    let fixed_offset = align_up(header_bytes, fixed_alignment);
    Some(OutputLayout {
        descriptor_bytes: fixed_offset.checked_add(fixed_bytes)?,
        fixed_offset,
        fixed_bytes,
        fixed_alignment,
    })
}

fn render_callback(
    module_name: &str,
    function: &crate::model::FunctionModel,
    plan: &FunctionPlan,
    records: &BTreeMap<String, RecordModel>,
) -> String {
    let callback = callback_name(module_name, &function.name);
    let api_member = native_member(module_name);
    let api_guard = native_guard(module_name);
    let slot_count = plan.direct_params.len().max(plan.direct_results.len());
    let direct_input_count = function
        .inputs
        .iter()
        .filter(|field| direct_type(&field.ty))
        .count();
    let input_descriptor_index = direct_input_count;
    let output_descriptor_index = plan.direct_params.len() - 1;
    let (input_bytes, input_alignment) =
        input_descriptor_layout(&function.inputs, records).expect("eligible input descriptor");
    let output_layout =
        output_descriptor_layout(&function.outputs, records).expect("eligible output descriptor");
    let mut body = format!(
        "wasm_trap_t* {callback}(void* environment, wasmtime_caller_t* caller,\n    wasmtime_val_raw_t* slots, std::size_t slotCount)\n{{\n    auto* state = static_cast<HostState*>(environment);\n    if (state == nullptr || state->native == nullptr || {api_guard} ||\n        state->native->{api_member}->{function_name} == nullptr)\n        return Trap(\"{function_name} generated Core binding is unavailable\");\n    if (slots == nullptr || slotCount != {slot_count})\n        return Trap(\"{function_name} generated Core ABI signature mismatch\");\n\n    std::string budgetError;\n    ImportGuard guard(state, {work}u, budgetError);\n    if (!guard.Ok())\n        return Trap(budgetError);\n\n    std::string memoryError;\n    if (!EnsureMemory(state, caller, memoryError))\n        return Trap(memoryError);\n    const std::uint32_t inputDescriptor = static_cast<std::uint32_t>(slots[{input_index}].i32);\n    const std::uint32_t outputDescriptor = static_cast<std::uint32_t>(slots[{output_index}].i32);\n    std::span<const std::uint8_t> inputWire;\n    std::span<std::uint8_t> outputWire;\n    if (!state->memory.View(inputDescriptor, {input_bytes}u, inputWire) ||\n        !state->memory.MutableView(outputDescriptor, {output_bytes}u, outputWire)) {{\n        slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds);\n        return nullptr;\n    }}\n    WireReader reader(inputWire);\n",
        callback = callback,
        api_member = api_member,
        api_guard = api_guard,
        function_name = function.name,
        slot_count = slot_count,
        work = 1 + plan.direct_params.len(),
        input_index = input_descriptor_index,
        output_index = output_descriptor_index,
        input_bytes = input_bytes,
        output_bytes = output_layout.descriptor_bytes,
    );

    let mut variable_output_index = 0usize;
    for field in &function.outputs {
        if !variable_type(&field.ty) {
            continue;
        }
        let stem = sanitize(&field.name);
        let offset = variable_output_index * 12;
        body.push_str(&format!(
            "    WireReader {stem}Control(std::span<const std::uint8_t>(outputWire.data() + {offset}u, 12));\n    std::uint32_t {stem}Pointer = 0;\n    std::uint32_t {stem}Capacity = 0;\n    std::uint32_t {stem}IgnoredLength = 0;\n    if (!{stem}Control.U32({stem}Pointer) || !{stem}Control.U32({stem}Capacity) ||\n        !{stem}Control.U32({stem}IgnoredLength) || !{stem}Control.Finish(4)) {{\n        slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument);\n        return nullptr;\n    }}\n",
            stem = stem,
            offset = offset,
        ));
        body.push_str(&render_capacity_validation(field, records, &stem));
        variable_output_index += 1;
    }

    body.push_str(&format!("\n    {} query{{}};\n", function.query));
    let mut direct_slot = 0usize;
    for field in &function.inputs {
        if direct_type(&field.ty) {
            body.push_str(&format!(
                "    query.{field} = {expr};\n",
                field = field.name,
                expr = query_expr(&field.ty, direct_slot, &format!("query.{}", field.name)),
            ));
            direct_slot += 1;
        } else if variable_type(&field.ty) {
            body.push_str(&render_input_variable(field, records));
        } else if optional_string(field) {
            body.push_str(&render_input_optional_string(field));
        } else {
            body.push_str(&render_wire_read_field(
                field,
                &format!("query.{}", field.name),
                "query",
                records,
                "reader",
                1,
            ));
        }
    }
    body.push_str(&format!(
        "    if (!reader.Finish({input_alignment}u)) {{\n        slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument);\n        return nullptr;\n    }}\n",
    ));

    body.push_str(&format!(
        "    {} result{{}};\n    state->native->{api_member}->{function_name}(&query, &result);\n    const std::int32_t errorCode = NativeErrorCode(result.error);\n    if (errorCode != 0) {{ slots[0].i32 = errorCode; return nullptr; }}\n    bool outputTooSmall = false;\n",
        function.result,
        api_member = api_member,
        function_name = function.name,
    ));

    variable_output_index = 0;
    for field in &function.outputs {
        if !variable_type(&field.ty) {
            continue;
        }
        let stem = sanitize(&field.name);
        let length_offset = variable_output_index * 12 + 8;
        body.push_str(&render_required_length(field, &stem));
        body.push_str(&format!(
            "    if (!WriteCoreU32(outputWire, {length_offset}u, {stem}Required))\n        return Trap(\"generated Core output descriptor changed unexpectedly\");\n    outputTooSmall = outputTooSmall || {stem}Capacity < {stem}Required;\n",
            length_offset = length_offset,
            stem = stem,
        ));
        variable_output_index += 1;
    }
    body.push_str("    if (outputTooSmall) { slots[0].i32 = static_cast<std::int32_t>(Status::BufferOverflow); return nullptr; }\n");

    for field in &function.outputs {
        if variable_type(&field.ty) {
            body.push_str(&render_output_copy(field, records));
        }
    }

    if output_layout.fixed_bytes != 0 {
        body.push_str(&format!(
            "    std::span<std::uint8_t> fixedWire = outputWire.subspan({fixed_offset}u, {fixed_bytes}u);\n    WireWriter writer(fixedWire);\n",
            fixed_offset = output_layout.fixed_offset,
            fixed_bytes = output_layout.fixed_bytes,
        ));
        for field in function
            .outputs
            .iter()
            .filter(|field| !variable_type(&field.ty))
        {
            body.push_str(&render_wire_write_field(
                field,
                &format!("result.{}", field.name),
                "result",
                records,
                "writer",
                1,
            ));
        }
        body.push_str(&format!(
            "    if (!writer.Finish({alignment}u)) return Trap(\"generated Core fixed output layout mismatch\");\n",
            alignment = output_layout.fixed_alignment,
        ));
    }
    body.push_str("    slots[0].i32 = 0;\n    return nullptr;\n}\n");
    body
}

/// `option<string>`: presence flag, then the pointer/length pair the plain
/// string input uses. The pair is read either way so the descriptor keeps a
/// fixed stride; an absent option leaves the native pointer null.
pub(crate) fn render_input_optional_string(field: &FieldModel) -> String {
    let stem = sanitize(&field.name);
    let presence = presence_field(field).expect("eligible option has presence metadata");
    format!(
        "    bool {stem}InputPresent = false;\n    std::uint32_t {stem}InputPointer = 0;\n    std::uint32_t {stem}InputCount = 0;\n    if (!reader.Bool({stem}InputPresent) || !reader.U32({stem}InputPointer) || !reader.U32({stem}InputCount)) {{\n        slots[0].i32 = static_cast<std::int32_t>(Status::InvalidArgument);\n        return nullptr;\n    }}\n    query.{presence} = {stem}InputPresent;\n    std::string {stem}InputStorage;\n    if (!{stem}InputPresent) {{\n        query.{field_name} = nullptr;\n    }} else {{\n        std::span<const std::uint8_t> {stem}InputBytes;\n        if (!state->memory.View({stem}InputPointer, {stem}InputCount, {stem}InputBytes)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n        {stem}InputStorage.assign(reinterpret_cast<const char*>({stem}InputBytes.data()), {stem}InputBytes.size());\n        query.{field_name} = {stem}InputStorage.c_str();\n    }}\n",
        stem = stem,
        presence = presence,
        field_name = field.name,
    )
}

fn render_capacity_validation(
    field: &FieldModel,
    records: &BTreeMap<String, RecordModel>,
    stem: &str,
) -> String {
    match &field.ty {
        SemanticType::String | SemanticType::Bytes => format!(
            "    if (!state->memory.Contains({stem}Pointer, {stem}Capacity)) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n"
        ),
        SemanticType::List { element } => {
            let (bytes, _) = fixed_wire_layout(element, records).expect("eligible output list element");
            format!(
                "    const std::uint64_t {stem}CapacityBytes = static_cast<std::uint64_t>({stem}Capacity) * {bytes}u;\n    if ({stem}CapacityBytes > std::numeric_limits<std::size_t>::max() || !state->memory.Contains({stem}Pointer, static_cast<std::size_t>({stem}CapacityBytes))) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OutOfBounds); return nullptr; }}\n"
            )
        }
        _ => String::new(),
    }
}

fn render_required_length(field: &FieldModel, stem: &str) -> String {
    match &field.ty {
        SemanticType::String => format!(
            "    const std::size_t {stem}RequiredSize = result.{field_name} == nullptr ? 0u : std::char_traits<char>::length(result.{field_name});\n    if ({stem}RequiredSize > std::numeric_limits<std::uint32_t>::max()) {{ slots[0].i32 = static_cast<std::int32_t>(Status::BufferOverflow); return nullptr; }}\n    const std::uint32_t {stem}Required = static_cast<std::uint32_t>({stem}RequiredSize);\n",
            field_name = field.name,
        ),
        SemanticType::Bytes | SemanticType::List { .. } => {
            let count = count_field(field).expect("eligible variable output count");
            format!(
                "    if (static_cast<std::uint64_t>(result.{count}) > std::numeric_limits<std::uint32_t>::max()) {{ slots[0].i32 = static_cast<std::int32_t>(Status::BufferOverflow); return nullptr; }}\n    const std::uint32_t {stem}Required = static_cast<std::uint32_t>(result.{count});\n    if ({stem}Required != 0 && result.{field_name} == nullptr) {{ slots[0].i32 = static_cast<std::int32_t>(Status::OperationFailed); return nullptr; }}\n",
                field_name = field.name,
            )
        }
        _ => unreachable!(),
    }
}

fn render_output_copy(field: &FieldModel, records: &BTreeMap<String, RecordModel>) -> String {
    let stem = sanitize(&field.name);
    match &field.ty {
        SemanticType::String | SemanticType::Bytes => format!(
            "    if ({stem}Required != 0 && !state->memory.Write({stem}Pointer, result.{field_name}, {stem}Required)) return Trap(\"generated Core variable output range changed unexpectedly\");\n",
            field_name = field.name,
        ),
        SemanticType::List { element } if borrowed_list_element(element) => {
            let element_bytes = borrowed_element_bytes(element);
            let element_alignment = element_bytes.min(8);
            let cpp = native_cpp_type(element);
            let item_write = render_wire_write(
                element,
                &format!("result.{}[coreIndex]", field.name),
                records,
                &format!("{stem}Writer"),
                3,
            );
            format!(
                "    if ({stem}Required != 0) {{\n        const std::size_t {stem}Bytes = static_cast<std::size_t>({stem}Required) * {element_bytes}u;\n        if constexpr (std::endian::native == std::endian::little) {{\n            static_assert(sizeof({cpp}) == {element_bytes}u, \"generated Core output/native element width mismatch\");\n            if (!state->memory.Write({stem}Pointer, result.{field_name}, {stem}Bytes)) return Trap(\"generated Core variable output range changed unexpectedly\");\n        }} else {{\n            std::span<std::uint8_t> {stem}Wire;\n            if (!state->memory.MutableView({stem}Pointer, {stem}Bytes, {stem}Wire)) return Trap(\"generated Core variable output range changed unexpectedly\");\n            WireWriter {stem}Writer({stem}Wire);\n            for (std::uint32_t coreIndex = 0; coreIndex < {stem}Required; ++coreIndex) {{\n{item_write}            }}\n            if (!{stem}Writer.Finish({element_alignment}u)) return Trap(\"generated Core list output layout mismatch\");\n        }}\n    }}\n",
                field_name = field.name,
            )
        }
        SemanticType::List { element } => {
            let (element_bytes, element_alignment) = fixed_wire_layout(element, records).expect("eligible output list element");
            let item_write = render_wire_write(element, &format!("result.{}[coreIndex]", field.name), records, &format!("{stem}Writer"), 2);
            format!(
                "    if ({stem}Required != 0) {{\n        const std::size_t {stem}Bytes = static_cast<std::size_t>({stem}Required) * {element_bytes}u;\n        std::span<std::uint8_t> {stem}Wire;\n        if (!state->memory.MutableView({stem}Pointer, {stem}Bytes, {stem}Wire)) return Trap(\"generated Core variable output range changed unexpectedly\");\n        WireWriter {stem}Writer({stem}Wire);\n        for (std::uint32_t coreIndex = 0; coreIndex < {stem}Required; ++coreIndex) {{\n{item_write}        }}\n        if (!{stem}Writer.Finish({element_alignment}u)) return Trap(\"generated Core list output layout mismatch\");\n    }}\n"
            )
        }
        _ => unreachable!(),
    }
}

fn query_expr(ty: &SemanticType, slot: usize, destination: &str) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!("slots[{slot}].i32 != 0"),
            "f32" => format!("slots[{slot}].f32"),
            "f64" => format!("slots[{slot}].f64"),
            "i64" | "u64" | "isize" | "usize" => {
                native_cast(destination, &format!("slots[{slot}].i64"))
            }
            _ => native_cast(destination, &format!("slots[{slot}].i32")),
        },
        SemanticType::Enum { .. } => native_cast(destination, &format!("slots[{slot}].i32")),
        SemanticType::Handle { .. } => native_cast(destination, &format!("slots[{slot}].i64")),
        _ => unreachable!(),
    }
}

/// Field-aware wire read. Only a field carries option presence metadata, so
/// option decoding lives here and everything else delegates to the type-driven
/// reader below.
fn render_registration(plan: &FunctionPlan, callback: &str) -> String {
    let params = kind_array("params", &plan.direct_params);
    let results = kind_array("results", &plan.direct_results);
    format!("    {{\n{params}{results}        if (!DefineGeneratedVariableIo(linker, \"{module}\", \"{name}\",\n                MakeFuncType(params, {pc}, results, {rc}), {callback}, state, error))\n            return false;\n    }}\n",
        params=params, results=results, module=plan.import_module, name=plan.import_name, pc=plan.direct_params.len(), rc=plan.direct_results.len(), callback=callback)
}

fn kind_array(name: &str, kinds: &[CoreType]) -> String {
    if kinds.is_empty() {
        return format!("        const wasm_valkind_t* {name} = nullptr;\n");
    }
    format!(
        "        const wasm_valkind_t {name}[] = {{{}}};\n",
        kinds
            .iter()
            .map(|kind| match kind {
                CoreType::I32 => "WASM_I32",
                CoreType::I64 => "WASM_I64",
                CoreType::F32 => "WASM_F32",
                CoreType::F64 => "WASM_F64",
            })
            .collect::<Vec<_>>()
            .join(", ")
    )
}

fn native_member(module: &str) -> String {
    spring_native_codegen::render_host::core_native_member(module)
        .unwrap_or_else(|| panic!("no NativeInterface member mapped for module {module}"))
}

fn native_guard(module: &str) -> String {
    spring_native_codegen::render_host::core_native_guard(module)
        .unwrap_or_else(|| panic!("no NativeInterface member mapped for module {module}"))
}
fn callback_name(module: &str, function: &str) -> String {
    format!(
        "CoreVariableIo_{}_{}",
        module.to_snake_case(),
        function.to_snake_case()
    )
}
fn record_index(model: &ApiModel) -> BTreeMap<String, RecordModel> {
    let mut records = BTreeMap::new();
    for module in &model.modules {
        for record in &module.records {
            records
                .entry(record.name.clone())
                .or_insert_with(|| record.clone());
        }
    }
    records
}
