//! Rust guest generation for direct/fixed Core-Wasm callins.

use heck::{ToKebabCase, ToSnakeCase};

use crate::model::{ApiModel, SemanticType};

use super::exec_model::{
    executable_callin, expanded_callins, record_index, ExecutableCallin, ResultAbi,
};

pub(super) fn render_rust(model: &ApiModel) -> String {
    let records = record_index(model);
    let executable = expanded_callins(model)
        .into_iter()
        .filter_map(|entry| executable_callin(entry, &records))
        .collect::<Vec<_>>();

    let mut output = String::from(
        "// @generated by spring-api-codegen; do not edit.\n\
         // Allocation-free Core callin export macros for direct/fixed queries.\n\
         // Fixed <=64-bit results are packed into one i64; first-non-empty\n\
         // strings use a guest-owned caller-specified static output buffer.\n\n",
    );
    for callin in &executable {
        output.push_str(&render_rust_macro(callin));
        output.push('\n');
    }
    output.push_str(&format!(
        "#[doc(hidden)]\npub const __GENERATED_CALLIN_COUNT: usize = {};\n\
         #[doc(hidden)]\npub const __GENERATED_NUMERIC_CALLIN_COUNT: usize = __GENERATED_CALLIN_COUNT;\n",
        executable.len()
    ));
    output
}

fn render_rust_macro(callin: &ExecutableCallin<'_>) -> String {
    if matches!(callin.result, ResultAbi::String { .. }) {
        return render_rust_string_macro(callin);
    }

    let macro_name = format!("export_{}", callin.entry.name.to_snake_case());
    let function_name = format!(
        "__spring_wasm_core_callin_{}",
        callin.entry.name.to_snake_case()
    );
    let export_name = format!("spring:callin/{}", callin.entry.name.to_kebab_case());
    let raw_params = callin
        .query_leaves
        .iter()
        .map(|leaf| format!("{}: {}", leaf.rust_name, rust_raw_type(&leaf.ty)))
        .collect::<Vec<_>>();
    let handler_args = callin
        .query_leaves
        .iter()
        .map(|leaf| rust_handler_arg(&leaf.ty, &leaf.rust_name))
        .collect::<Vec<_>>();
    let handler_call = format!("$handler({})", handler_args.join(", "));

    let (raw_return, body) = match &callin.result {
        ResultAbi::Empty => (String::new(), format!("{handler_call};")),
        ResultAbi::Direct { field } => (
            format!(" -> {}", rust_raw_type(&field.ty)),
            rust_return_expr(&field.ty, &handler_call),
        ),
        ResultAbi::PackedFixed { leaves } => {
            let result_binding = format!("let value = {handler_call};");
            let packed = leaves
                .iter()
                .enumerate()
                .map(|(index, leaf)| {
                    let value = if leaves.len() == 1 {
                        "value".to_owned()
                    } else {
                        format!("value.{index}")
                    };
                    let encoded = rust_pack32_expr(&leaf.ty, &value);
                    if index == 0 {
                        format!("({encoded} as u64)")
                    } else {
                        format!("(({encoded} as u64) << {}u32)", index * 32)
                    }
                })
                .collect::<Vec<_>>()
                .join(" | ");
            (
                " -> i64".to_owned(),
                format!("{result_binding}\n            ({packed}) as i64"),
            )
        }
        ResultAbi::String { .. } => unreachable!(),
    };

    let params = if raw_params.is_empty() {
        String::new()
    } else {
        format!(
            "\n            {}\n        ",
            raw_params.join(",\n            ")
        )
    };
    let result_doc = match &callin.result {
        ResultAbi::PackedFixed { leaves } if leaves.len() == 2 => {
            " The handler returns a tuple matching result-field declaration order."
        }
        ResultAbi::PackedFixed { .. } => " The handler returns the single flattened result leaf.",
        _ => "",
    };

    format!(
        "/// Export `{native_name}` through the allocation-free numeric Core ABI.{result_doc}\n#[macro_export]\nmacro_rules! {macro_name} {{\n    ($handler:path) => {{\n        #[cfg(target_arch = \"wasm32\")]\n        #[export_name = \"{export_name}\"]\n        pub extern \"C\" fn {function_name}({params}){raw_return} {{\n            {body}\n        }}\n    }};\n}}\n",
        native_name = callin.entry.name,
        result_doc = result_doc,
        macro_name = macro_name,
        export_name = export_name,
        function_name = function_name,
        params = params,
        raw_return = raw_return,
        body = body,
    )
}

fn render_rust_string_macro(callin: &ExecutableCallin<'_>) -> String {
    let macro_name = format!("export_{}", callin.entry.name.to_snake_case());
    let function_name = format!(
        "__spring_wasm_core_callin_{}",
        callin.entry.name.to_snake_case()
    );
    let buffer_type = format!(
        "__SpringCoreStringResultBuffer_{}",
        callin.entry.name.to_snake_case()
    );
    let buffer_name = format!(
        "__SPRING_CORE_STRING_RESULT_BUFFER_{}",
        callin.entry.name.to_snake_case().to_ascii_uppercase()
    );
    let export_name = format!("spring:callin/{}", callin.entry.name.to_kebab_case());
    let raw_params = callin
        .query_leaves
        .iter()
        .map(|leaf| format!("{}: {}", leaf.rust_name, rust_raw_type(&leaf.ty)))
        .collect::<Vec<_>>();
    let mut handler_args = callin
        .query_leaves
        .iter()
        .map(|leaf| rust_handler_arg(&leaf.ty, &leaf.rust_name))
        .collect::<Vec<_>>();
    handler_args.push("output".to_owned());
    let handler_call = format!("$handler({})", handler_args.join(", "));
    let params = if raw_params.is_empty() {
        String::new()
    } else {
        format!(
            "\n            {}\n        ",
            raw_params.join(",\n            ")
        )
    };

    format!(
        "/// Export `{native_name}` with a guest-owned string result buffer.\n/// The handler receives the flattened query arguments followed by `&mut [u8]`\n/// and returns the number of UTF-8 bytes written. The host copies those bytes\n/// immediately after the single guest call; no guest pointer is retained.\n#[macro_export]\nmacro_rules! {macro_name} {{\n    ($handler:path, $bytes:expr) => {{\n        #[repr(align(8))]\n        struct {buffer_type}([u8; $bytes]);\n        static mut {buffer_name}: {buffer_type} = {buffer_type}([0; $bytes]);\n\n        #[cfg(target_arch = \"wasm32\")]\n        #[export_name = \"{export_name}\"]\n        pub extern \"C\" fn {function_name}({params}) -> i64 {{\n            let pointer = core::ptr::addr_of_mut!({buffer_name}.0).cast::<u8>();\n            if $bytes > u32::MAX as usize || pointer as usize > u32::MAX as usize {{\n                return ((u32::MAX as u64) << 32) as i64;\n            }}\n            // SAFETY: the host rejects nested generated string-result callins,\n            // so this one export has exclusive use of its static result buffer.\n            let output = unsafe {{ core::slice::from_raw_parts_mut(pointer, $bytes) }};\n            let used = {handler_call};\n            if used > $bytes || used > u32::MAX as usize {{\n                return ((u32::MAX as u64) << 32) as i64;\n            }}\n            (((used as u64) << 32) | pointer as u32 as u64) as i64\n        }}\n    }};\n}}\n",
        native_name = callin.entry.name,
        macro_name = macro_name,
        export_name = export_name,
        function_name = function_name,
        buffer_type = buffer_type,
        buffer_name = buffer_name,
        params = params,
        handler_call = handler_call,
    )
}

fn rust_raw_type(ty: &SemanticType) -> &'static str {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "f32" => "f32",
            "f64" => "f64",
            "i64" | "u64" | "isize" | "usize" => "i64",
            _ => "i32",
        },
        SemanticType::Enum { .. } => "i32",
        SemanticType::Handle { .. } => "i64",
        _ => unreachable!(),
    }
}

fn rust_handler_arg(ty: &SemanticType, name: &str) -> String {
    match ty {
        SemanticType::Scalar { name: scalar } => match scalar.as_str() {
            "bool" => format!("{name} != 0"),
            "i8" => format!("{name} as i8"),
            "i16" => format!("{name} as i16"),
            "i32" => name.to_owned(),
            "i64" => name.to_owned(),
            "u8" | "char" => format!("{name} as u8"),
            "u16" => format!("{name} as u16"),
            "u32" => format!("{name} as u32"),
            "u64" => format!("{name} as u64"),
            "isize" => format!("{name} as isize"),
            "usize" => format!("{name} as usize"),
            "f32" | "f64" => name.to_owned(),
            _ => name.to_owned(),
        },
        SemanticType::Enum { .. } => name.to_owned(),
        SemanticType::Handle { .. } => format!("{name} as u64"),
        _ => unreachable!(),
    }
}

fn rust_return_expr(ty: &SemanticType, value: &str) -> String {
    match ty {
        SemanticType::Scalar { name } => match name.as_str() {
            "bool" => format!("if {value} {{ 1 }} else {{ 0 }}"),
            "f32" | "f64" | "i32" | "i64" => value.to_owned(),
            "i8" | "i16" | "u8" | "char" | "u16" | "u32" => format!("{value} as i32"),
            "u64" | "isize" | "usize" => format!("{value} as i64"),
            _ => value.to_owned(),
        },
        SemanticType::Enum { .. } => format!("{value} as i32"),
        SemanticType::Handle { .. } => format!("{value} as i64"),
        _ => unreachable!(),
    }
}

fn rust_pack32_expr(ty: &SemanticType, value: &str) -> String {
    match ty {
        SemanticType::Scalar { name } if name == "bool" => {
            format!("if {value} {{ 1u32 }} else {{ 0u32 }}")
        }
        SemanticType::Scalar { name } if name == "f32" => format!("{value}.to_bits()"),
        SemanticType::Scalar { .. } | SemanticType::Enum { .. } => format!("{value} as u32"),
        _ => unreachable!(),
    }
}
