//! Core-only native metadata and NativeInterface paths.

use crate::model::{ApiModel, Environment, LoweringStatus};

pub fn render_registry(model: &ApiModel) -> String {
    let mut output = String::from(
        "/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */\n\n",
    );
    output.push_str("// @generated by spring-api-codegen; do not edit.\n");
    output.push_str("#pragma once\n\n#include <cstdint>\n#include <string_view>\n\n");
    output.push_str("namespace recoil::wasm::generated {\n");
    output.push_str(
        "enum class LoweringStatus : std::uint8_t { automatic, annotated, manual, unsupported };\n",
    );
    output.push_str("enum class Environment : std::uint8_t { rulesSynced, rulesUnsynced, gaiaSynced, gaiaUnsynced, ui };\n\n");
    output.push_str("struct CalloutDescriptor { const char* module; const char* name; std::uint32_t environmentMask; bool mutating; bool visibilitySensitive; LoweringStatus status; };\n\n");
    output.push_str("inline constexpr CalloutDescriptor kCallouts[] = {\n");
    for module in &model.modules {
        for function in &module.functions {
            let mask = function
                .environments
                .iter()
                .map(environment_mask)
                .sum::<u32>();
            let status = match function.status {
                LoweringStatus::Automatic => "LoweringStatus::automatic",
                LoweringStatus::Annotated => "LoweringStatus::annotated",
                LoweringStatus::Manual => "LoweringStatus::manual",
                LoweringStatus::Unsupported => "LoweringStatus::unsupported",
            };
            output.push_str(&format!(
                "\t{{\"{}\", \"{}\", {}u, {}, {}, {}}},\n",
                module.name,
                function.name,
                mask,
                function.mutating,
                function.visibility_sensitive,
                status
            ));
        }
    }
    output.push_str("};\n\n");
    output.push_str(
        "inline std::string_view CanonicalModule(std::string_view module) { return module; }\n}\n",
    );
    output
}

fn environment_mask(environment: &Environment) -> u32 {
    match environment {
        Environment::RulesSynced => 1,
        Environment::RulesUnsynced => 2,
        Environment::GaiaSynced => 4,
        Environment::GaiaUnsynced => 8,
        Environment::Ui => 16,
        Environment::Menu => 32,
        Environment::Intro => 64,
    }
}

/// Render the canonical callin/alias inventory used by the C++ dispatch seam.
pub fn render_callin_registry(model: &ApiModel) -> String {
    let mut output = String::from(
        "/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */\n\n",
    );
    output.push_str("// @generated by spring-api-codegen; do not edit.\n");
    output.push_str("#pragma once\n\n#include <cstdint>\n\n");
    output.push_str("namespace recoil::wasm::generated {\n");
    output.push_str("struct CallinDescriptor { const char* name; const char* canonical; const char* query; const char* result; const char* aggregation; std::uint32_t environmentMask; };\n\n");
    output.push_str("inline constexpr CallinDescriptor kCallins[] = {\n");
    for callin in &model.callins {
        render_callin_entry(&mut output, callin, &callin.name);
        for alias in &callin.aliases {
            render_callin_entry(&mut output, callin, alias);
        }
    }
    output.push_str("};\n}\n");
    output
}

fn render_callin_entry(output: &mut String, callin: &crate::model::CallinModel, name: &str) {
    let mask = callin
        .environments
        .iter()
        .map(environment_mask)
        .sum::<u32>();
    output.push_str(&format!(
        "\t{{\"{}\", \"{}\", \"{}\", \"{}\", \"{}\", {}u}},\n",
        name, callin.name, callin.query, callin.result, callin.aggregation, mask
    ));
}

/// Return the NativeInterface access path and corresponding API table type.
/// Nested control/rendering tables are explicit because they are not
/// top-level fields even though their C headers are separate modules.
pub fn native_api_path(module: &str) -> Option<(&'static str, &'static str)> {
    Some(match module {
        "units_query" => ("nativeInterface->unitsQuery", "UnitsQueryApi"),
        "units_info" => ("nativeInterface->unitsInfo", "UnitsInfoApi"),
        "units_weapons" => ("nativeInterface->unitsWeapons", "UnitsWeaponsApi"),
        "units_commands" => ("nativeInterface->unitsCommands", "UnitsCommandsApi"),
        "units_pieces" => ("nativeInterface->unitsPieces", "UnitsPiecesApi"),
        "teams" => ("nativeInterface->teams", "TeamsApi"),
        "features" => ("nativeInterface->features", "FeaturesApi"),
        "projectiles" => ("nativeInterface->projectiles", "ProjectilesApi"),
        "los" => ("nativeInterface->los", "LOSApi"),
        "unit_defs" => ("nativeInterface->unitDefs", "UnitDefsApi"),
        "feature_defs" => ("nativeInterface->featureDefs", "FeatureDefsApi"),
        "weapon_defs" => ("nativeInterface->weaponDefs", "WeaponDefsApi"),
        "game" => ("nativeInterface->game", "GameApi"),
        "terrain" => ("nativeInterface->terrain", "TerrainApi"),
        "player" => ("nativeInterface->player", "PlayerApi"),
        "math_extra" => ("nativeInterface->mathExtra", "MathExtraApi"),
        "encoding" => ("nativeInterface->encoding", "EncodingApi"),
        "metal_map" => ("nativeInterface->metalMap", "MetalMapApi"),
        "path_finder" => ("nativeInterface->pathFinder", "PathFinderApi"),
        "platform" => ("nativeInterface->platform", "PlatformApi"),
        "rules_params" => ("nativeInterface->rulesParams", "RulesParamsApi"),
        "move_ctrl" => ("nativeInterface->moveCtrl", "MoveCtrlApi"),
        "camera" => ("nativeInterface->cameraApi", "CameraApi"),
        "input" => ("nativeInterface->input", "InputApi"),
        "debug_input" => ("nativeInterface->debugInput", "DebugInputApi"),
        "display" => ("nativeInterface->display", "DisplayApi"),
        "selection" => ("nativeInterface->selection", "SelectionApi"),
        "sound" => ("nativeInterface->soundApi", "SoundApi"),
        "messages" => ("nativeInterface->messages", "MessagesApi"),
        "config" => ("nativeInterface->config", "ConfigApi"),
        "tracing" => ("nativeInterface->tracing", "TracingApi"),
        "utils" => ("nativeInterface->utils", "UtilsApi"),
        "memory" => ("nativeInterface->memory", "MemoryApi"),
        "unsynced_ctrl" => ("nativeInterface->unsyncedCtrl", "UnsyncedCtrlApi"),
        "gfx" => ("nativeInterface->gfx", "GfxApi"),
        "lights" => ("nativeInterface->lights", "LightsApi"),
        "icons" => ("nativeInterface->icons", "IconsApi"),
        "markers" => ("nativeInterface->markers", "MarkersApi"),
        "ground_decals" => ("nativeInterface->groundDecals", "GroundDecalsApi"),
        "system_control" => ("nativeInterface->systemControl", "SystemControlApi"),
        "profiling" => ("nativeInterface->profiling", "ProfilingApi"),
        "rml_ui" => ("nativeInterface->rmlUi", "RmlUiApi"),
        "vfs" => ("nativeInterface->vfs", "VFSApi"),
        "unsynced_read" => ("nativeInterface->unsyncedRead", "UnsyncedReadApi"),
        "team_control" => ("nativeInterface->syncedCtrl->team", "TeamControlApi"),
        "unit_control" => ("nativeInterface->syncedCtrl->unit", "UnitControlApi"),
        "feature_control" => ("nativeInterface->syncedCtrl->feature", "FeatureControlApi"),
        "terrain_control" => ("nativeInterface->syncedCtrl->terrain", "TerrainControlApi"),
        "projectile_control" => (
            "nativeInterface->syncedCtrl->projectile",
            "ProjectileControlApi",
        ),
        "effects_control" => ("nativeInterface->syncedCtrl->effects", "EffectsControlApi"),
        "game_config" => ("nativeInterface->syncedCtrl->gameConfig", "GameConfigApi"),
        "cob_script" => ("nativeInterface->syncedCtrl->cobScript", "COBScriptApi"),
        "unit_script" => ("nativeInterface->syncedCtrl->unitScript", "UnitScriptApi"),
        "unit_rendering" => (
            "nativeInterface->unsyncedRead->unitRendering",
            "UnitRenderingApi",
        ),
        _ => return None,
    })
}

/// Member path under `NativeInterface` for a Core binding, relative to
/// `state->native->`.
pub fn core_native_member(module: &str) -> Option<String> {
    let (path, _) = native_api_path(module)?;
    Some(path.trim_start_matches("nativeInterface->").to_owned())
}

/// Progressive null guard for `state->native-><member>`.
pub fn core_native_guard(module: &str) -> Option<String> {
    let member = core_native_member(module)?;
    let mut prefix = String::new();
    let mut checks = Vec::new();
    for segment in member.split("->") {
        if !prefix.is_empty() {
            prefix.push_str("->");
        }
        prefix.push_str(segment);
        checks.push(format!("state->native->{prefix} == nullptr"));
    }
    Some(checks.join(" || "))
}
