name: Spring Native Rust

on:
  workflow_dispatch:
  push:
    branches:
      - rust-wip
    paths:
      - .github/workflows/spring-native.yml
      - rust/**
      - rts/NativeInterface/**

permissions:
  contents: read

jobs:
  check:
    name: Check ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install libclang on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install --yes libclang-18-dev

      - name: Install LLVM 18 on Windows
        if: runner.os == 'Windows'
        uses: KyleMayes/install-llvm-action@ebc0426251bc40c7cd31162802432c68818ab8f0
        with:
          version: "18.1.8"
          directory: ${{ runner.temp }}/llvm

      - name: Locate libclang on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: echo "LIBCLANG_PATH=/usr/lib/llvm-18/lib" >> "$GITHUB_ENV"

      - name: Locate libclang on Windows
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          "LIBCLANG_PATH=$env:LLVM_PATH\bin" >> $env:GITHUB_ENV

      - name: Check formatting
        run: cargo fmt --manifest-path rust/Cargo.toml --all --check

      - name: Lint code generator
        run: cargo clippy --manifest-path rust/Cargo.toml --package spring-native-codegen --all-targets -- --deny warnings

      - name: Check workspace
        run: cargo check --manifest-path rust/Cargo.toml --workspace

      - name: Test workspace libraries
        run: cargo test --manifest-path rust/Cargo.toml --workspace --lib
